### ISSUE TITLE
Doesnt build.

### ISSUE THREAD

**Issue by TrevorBlythe** [google/leveldb#1004]
Says theres an error in the cmake file?
```
CMake Error at CMakeLists.txt:299 (add_subdirectory):
  The source directory

    /home/slave-master/Documents/leveldb/third_party/googletest

  does not contain a CMakeLists.txt file.



```

**Comment by cmumford** [comment]
Looks like when you fetched the leveldb source you didn't initialize the submodules as per the README:

```sh
git clone --recurse-submodules https://github.com/google/leveldb.git
```

You can do that, without re-cloning the source, as so:

```sh
git submodule update --init --recursive
```

Make sure you're at the top level of the source before running the command. Re-open if you still have issues.
