### ISSUE TITLE
Why we need `AddBoundaryInputs`?

### ISSUE THREAD

**Issue by RinChanNOWWW** [google/leveldb#1007]
1. Expect level-0, every SST is not overlapping with each others, and there should not exist a file's biggest user key equals to another file's smallest user key.
2. When picking files for compaction, `GetOverlappingInputs` will collect all the overlapping files including the boundary case.

**Comment by linfengsys** [comment]
AddBoundaryInputs is introduced to fix this problem: https://github.com/google/leveldb/issues/320.  When considering snapshots in leveldb, the first conclusion you said is not accuracy.

**Comment by RinChanNOWWW** [comment]
Sure, I found out the reason but forgot to close this issue. Thank you.
