### ISSUE TITLE
empty key assert failure during compaction

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#103]
Original [issue 97](https://code.google.com/p/leveldb/issues/detail?id=97) created by rexludorum on 2012-06-14T21:51:22.000Z:

On a clean build of: dd0d562b4d4fbd07db6a44f9e221f8d368fee8e4

```c++
$ cat check.cc
#include <set>
#include <map>
#include <string>
#include "leveldb/db.h"
#include "leveldb/write_batch.h"
#include "leveldb/slice.h"
#include <unistd.h>

int main(int args, char **argv) {
  leveldb::Options options;
  leveldb::DB *_db;
  leveldb::Status status = leveldb::DB::Open(options, argv[1], &amp;_db);
  while (1) {
    sleep(1);
  }
}
```

```
$ tar -xvf omap.tgz
$ g++ -g2 -pthread -Ileveldb/include check.cc leveldb/libleveldb.a
$ ./a.out omap
a.out: ./db/dbformat.h:96: leveldb::Slice leveldb::ExtractUserKey(const leveldb::Slice&): Assertion `internal_key.size() >= 8' failed.
Aborted

$ gdb --args ./a.out omap
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /home/samuelj/a.out...done.
(gdb) run
Starting program: /home/samuelj/a.out omap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6fef700 (LWP 1769)]
a.out: ./db/dbformat.h:96: leveldb::Slice leveldb::ExtractUserKey(const leveldb::Slice&): Assertion `internal_key.size() >= 8' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6fef700 (LWP 1769)]
0x00007ffff7320445 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
# 0  0x00007ffff7320445 in raise () from /lib/x86_64-linux-gnu/libc.so.6
# 1  0x00007ffff7323bab in abort () from /lib/x86_64-linux-gnu/libc.so.6
# 2  0x00007ffff731910e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
# 3  0x00007ffff73191b2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
# 4  0x000000000040a5be in leveldb::ExtractUserKey (internal_key=...) at ./db/dbformat.h:96
# 5  0x000000000042f1a3 in leveldb::InternalKeyComparator::Compare (this=0x658600, akey=..., bkey=...) at db/dbformat.cc:55
# 6  0x00000000004260f2 in leveldb::(anonymous namespace)::MergingIterator::FindSmallest (this=0x7ffff0001ad0) at table/merger.cc:162
# 7  0x0000000000425d18 in leveldb::(anonymous namespace)::MergingIterator::Next (this=0x7ffff0001ad0) at table/merger.cc:82
# 8  0x0000000000407479 in leveldb::DBImpl::DoCompactionWork (this=0x655390, compact=0x7ffff0000bb0) at db/db_impl.cc:951
# 9  0x0000000000405f66 in leveldb::DBImpl::BackgroundCompaction (this=0x655390) at db/db_impl.cc:681
# 10 0x00000000004058b4 in leveldb::DBImpl::BackgroundCall (this=0x655390) at db/db_impl.cc:611
# 11 0x0000000000405830 in leveldb::DBImpl::BGWork (db=0x655390) at db/db_impl.cc:604
# 12 0x00000000004358f2 in leveldb::(anonymous namespace)::PosixEnv::BGThread (this=0x655030) at util/env_posix.cc:572
# 13 0x0000000000435603 in leveldb::(anonymous namespace)::PosixEnv::BGThreadWrapper (arg=0x655030) at util/env_posix.cc:512
# 14 0x00007ffff76aee9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
# 15 0x00007ffff73dc4bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
# 16 0x0000000000000000 in ?? ()
```

**Comment by cmumford** [comment]
Last activity is ~3 years ago. Assuming this is no longer being seen - please reopen if still occurring.

**Comment by ayushgoel** [comment]
Hoping to get the real cause for this issue. Below is the stack trace we received in Firebase for a crash.
We are not directly dealing with leveldb, `Firebase` uses it as a dependency when we use Firestore in the app.

Let me know in case more details are required.

```
Crashed: com.google.firebase.firestore
0  libsystem_kernel.dylib         0x1bee21ec4 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1bed3d1d8 pthread_kill$VARIANT$mp + 136
2  libsystem_c.dylib              0x1bec91844 abort + 100
3  libsystem_c.dylib              0x1bec90c64 err + 286
4  leveldb                        0x106a821d8 leveldb::InternalKeyComparator::Compare(leveldb::Slice const&, leveldb::Slice const&) const (.cold.1) + 34
5  leveldb                        0x106a68c84 leveldb::InternalKeyComparator::Compare(leveldb::Slice const&, leveldb::Slice const&) const + 164
6  leveldb                        0x106a71ca4 leveldb::MemTable::KeyComparator::operator()(char const*, char const*) const + 64
7  leveldb                        0x106a72504 leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::FindGreaterOrEqual(char const* const&, leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Node**) const + 88
8  leveldb                        0x106a71eb4 leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Insert(char const* const&) + 52
9  leveldb                        0x106a71e58 leveldb::MemTable::Add(unsigned long long, leveldb::ValueType, leveldb::Slice const&, leveldb::Slice const&) + 252
10 leveldb                        0x106a7fea8 leveldb::(anonymous namespace)::MemTableInserter::Put(leveldb::Slice const&, leveldb::Slice const&) + 36
11 leveldb                        0x106a7fb44 leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const + 208
12 leveldb                        0x106a7fe48 leveldb::WriteBatchInternal::InsertInto(leveldb::WriteBatch const*, leveldb::MemTable*) + 60
13 leveldb                        0x106a64bec leveldb::DBImpl::Write(leveldb::WriteOptions const&, leveldb::WriteBatch*) + 576
14 Copilot                        0x104ebe4ec firebase::firestore::local::LevelDbTransaction::Commit() + 57 (status.h:57)
15 Copilot                        0x104eb7f9c firebase::firestore::local::LevelDbPersistence::RunInternal(absl::string_view, std::__1::function<void ()>) + 269 (leveldb_persistence.cc:269)
16 Copilot                        0x104ec5274 firebase::firestore::local::LocalStore::AcknowledgeBatch(firebase::firestore::model::MutationBatchResult const&) + 1757 (functional:1757)
17 Copilot                        0x104f0b14c firebase::firestore::core::SyncEngine::HandleSuccessfulWrite(firebase::firestore::model::MutationBatchResult const&) + 99 (optional.h:99)
18 Copilot                        0x104ef79e0 firebase::firestore::remote::RemoteStore::OnWriteStreamMutationResult(firebase::firestore::model::SnapshotVersion, std::__1::vector<firebase::firestore::model::MutationResult, std::__1::allocator<firebase::firestore::model::MutationResult> >) + 426 (remote_store.cc:426)
19 Copilot                        0x104f2b34c firebase::firestore::remote::WriteStream::NotifyStreamResponse(grpc::ByteBuffer const&) + 556 (vector:556)
20 Copilot                        0x104f05e38 firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) + 2637 (memory:2637)
21 Copilot                        0x104eaab20 std::__1::__function::__func<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3, std::__1::allocator<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3>, void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool&&, firebase::firestore::remote::GrpcCompletion const*&&) + 1799 (functional:1799)
22 Copilot                        0x104ea492c std::__1::function<void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool, firebase::firestore::remote::GrpcCompletion const*) const + 2347 (functional:2347)
23 Copilot                        0x104ea4814 std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() + 71 (grpc_completion.cc:71)
24 Copilot                        0x104e52a50 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 918 (atomic:918)
25 Copilot                        0x104e66b80 firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*) + 1757 (functional:1757)
26 libdispatch.dylib              0x1becf7184 _dispatch_client_callout + 16
27 libdispatch.dylib              0x1beca3404 _dispatch_lane_serial_drain$VARIANT$mp + 608
28 libdispatch.dylib              0x1beca3df8 _dispatch_lane_invoke$VARIANT$mp + 420
29 libdispatch.dylib              0x1becad314 _dispatch_workloop_worker_thread + 588
30 libsystem_pthread.dylib        0x1bed46b88 _pthread_wqthread + 276
31 libsystem_pthread.dylib        0x1bed49760 start_wqthread + 8
```

**Comment by rimsineman1** [comment]
> Hoping to get the real cause for this issue. Below is the stack trace we received in Firebase for a crash.
> We are not directly dealing with leveldb, `Firebase` uses it as a dependency when we use Firestore in the app.
> 
> Let me know in case more details are required.
> 
> ```
> Crashed: com.google.firebase.firestore
> 0  libsystem_kernel.dylib         0x1bee21ec4 __pthread_kill + 8
> 1  libsystem_pthread.dylib        0x1bed3d1d8 pthread_kill$VARIANT$mp + 136
> 2  libsystem_c.dylib              0x1bec91844 abort + 100
> 3  libsystem_c.dylib              0x1bec90c64 err + 286
> 4  leveldb                        0x106a821d8 leveldb::InternalKeyComparator::Compare(leveldb::Slice const&, leveldb::Slice const&) const (.cold.1) + 34
> 5  leveldb                        0x106a68c84 leveldb::InternalKeyComparator::Compare(leveldb::Slice const&, leveldb::Slice const&) const + 164
> 6  leveldb                        0x106a71ca4 leveldb::MemTable::KeyComparator::operator()(char const*, char const*) const + 64
> 7  leveldb                        0x106a72504 leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::FindGreaterOrEqual(char const* const&, leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Node**) const + 88
> 8  leveldb                        0x106a71eb4 leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Insert(char const* const&) + 52
> 9  leveldb                        0x106a71e58 leveldb::MemTable::Add(unsigned long long, leveldb::ValueType, leveldb::Slice const&, leveldb::Slice const&) + 252
> 10 leveldb                        0x106a7fea8 leveldb::(anonymous namespace)::MemTableInserter::Put(leveldb::Slice const&, leveldb::Slice const&) + 36
> 11 leveldb                        0x106a7fb44 leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const + 208
> 12 leveldb                        0x106a7fe48 leveldb::WriteBatchInternal::InsertInto(leveldb::WriteBatch const*, leveldb::MemTable*) + 60
> 13 leveldb                        0x106a64bec leveldb::DBImpl::Write(leveldb::WriteOptions const&, leveldb::WriteBatch*) + 576
> 14 Copilot                        0x104ebe4ec firebase::firestore::local::LevelDbTransaction::Commit() + 57 (status.h:57)
> 15 Copilot                        0x104eb7f9c firebase::firestore::local::LevelDbPersistence::RunInternal(absl::string_view, std::__1::function<void ()>) + 269 (leveldb_persistence.cc:269)
> 16 Copilot                        0x104ec5274 firebase::firestore::local::LocalStore::AcknowledgeBatch(firebase::firestore::model::MutationBatchResult const&) + 1757 (functional:1757)
> 17 Copilot                        0x104f0b14c firebase::firestore::core::SyncEngine::HandleSuccessfulWrite(firebase::firestore::model::MutationBatchResult const&) + 99 (optional.h:99)
> 18 Copilot                        0x104ef79e0 firebase::firestore::remote::RemoteStore::OnWriteStreamMutationResult(firebase::firestore::model::SnapshotVersion, std::__1::vector<firebase::firestore::model::MutationResult, std::__1::allocator<firebase::firestore::model::MutationResult> >) + 426 (remote_store.cc:426)
> 19 Copilot                        0x104f2b34c firebase::firestore::remote::WriteStream::NotifyStreamResponse(grpc::ByteBuffer const&) + 556 (vector:556)
> 20 Copilot                        0x104f05e38 firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) + 2637 (memory:2637)
> 21 Copilot                        0x104eaab20 std::__1::__function::__func<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3, std::__1::allocator<firebase::firestore::remote::GrpcStream::NewCompletion(firebase::firestore::remote::GrpcCompletion::Type, std::__1::function<void (firebase::firestore::remote::GrpcCompletion const*)> const&)::$_3>, void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool&&, firebase::firestore::remote::GrpcCompletion const*&&) + 1799 (functional:1799)
> 22 Copilot                        0x104ea492c std::__1::function<void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool, firebase::firestore::remote::GrpcCompletion const*) const + 2347 (functional:2347)
> 23 Copilot                        0x104ea4814 std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() + 71 (grpc_completion.cc:71)
> 24 Copilot                        0x104e52a50 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 918 (atomic:918)
> 25 Copilot                        0x104e66b80 firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*) + 1757 (functional:1757)
> 26 libdispatch.dylib              0x1becf7184 _dispatch_client_callout + 16
> 27 libdispatch.dylib              0x1beca3404 _dispatch_lane_serial_drain$VARIANT$mp + 608
> 28 libdispatch.dylib              0x1beca3df8 _dispatch_lane_invoke$VARIANT$mp + 420
> 29 libdispatch.dylib              0x1becad314 _dispatch_workloop_worker_thread + 588
> 30 libsystem_pthread.dylib        0x1bed46b88 _pthread_wqthread + 276
> 31 libsystem_pthread.dylib        0x1bed49760 start_wqthread + 8
> ```
