### ISSUE TITLE
Unused warn in `third_party/benchmark/src/complexity.cc`

### ISSUE THREAD

**Issue by JasonkayZK** [google/leveldb#1074]
I tried to build the source shortly after i clone the repo:

```bash
[ 71%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/complexity.cc.o
leveldb/third_party/benchmark/src/complexity.cc:85:10: error: variable 'sigma_gn' set but not used [-Werror,-Wunused-but-set-variable]
  double sigma_gn = 0.0;
         ^
1 error generated.
make[2]: *** [third_party/benchmark/src/CMakeFiles/benchmark.dir/complexity.cc.o] Error 1
make[1]: *** [third_party/benchmark/src/CMakeFiles/benchmark.dir/all] Error 2
make: *** [all] Error 2
```

It seems that the `sigma_gn` did not get used at any place.

And the solution is to simply remove this two lines:

```diff
LeastSq MinimalLeastSq(const std::vector<int64_t>& n,
                       const std::vector<double>& time,
                       BigOFunc* fitting_curve) {
-  double sigma_gn = 0.0;
+ //  double sigma_gn = 0.0;
  double sigma_gn_squared = 0.0;
  double sigma_time = 0.0;
  double sigma_time_gn = 0.0;

  // Calculate least square fitting parameter
  for (size_t i = 0; i < n.size(); ++i) {
    double gn_i = fitting_curve(n[i]);
-     sigma_gn += gn_i;
+ //    sigma_gn += gn_i;
    sigma_gn_squared += gn_i * gn_i;
    sigma_time += time[i];
    sigma_time_gn += time[i] * gn_i;
  }
```

**Comment by krishnacx** [comment]
I have the commit ready. Can anyone assist me in generating the PR. 

I am recieving the error:
`git push -u origin kv_warning_fix
remote: Permission to google/benchmark.git denied to krishnacx.
fatal: unable to access 'https://github.com/google/benchmark/': The requested URL returned error: 403


`

**Comment by JasonkayZK** [comment]
This is because the `benchmark` under the `third_party` dir is managed by git-submodule, and its source code is locked by the git commit id [benchmark @7d0d906](https://github.com/google/benchmark/tree/7d0d9061d83b663ce05d9de5da3d5865a3845b79).

I think we have to first take a PR based on [benchmark @7d0d906](https://github.com/google/benchmark/tree/7d0d9061d83b663ce05d9de5da3d5865a3845b79), then update the submodule's version. 😢

**Comment by verdy-p** [comment]
THis looks like a generic code copy-pasted for computing Khi2 or other variance-mean fitting metrics. But given this function, that sum is not needed. If there's a need of additional metrics, such sums should be computed on demand and cached with some hash  or timestamp indicating when it needs to be refreshed (to avoid repeating this summation loop if that function is used repeatedly to get multiple benchmark metrics). However as this function is specific to benchmarks, it has no impact on the normal use of leveldb at runtime. Such warning emitted by the compiler is harmless and should not be treated as an error blocking benchmarks to be performed, when it also does not impact at all the measurements already registered made on the normal API (that function is just to render the results of these benchmarks).
