### ISSUE TITLE
DoNotOverwrite - feature request

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#139]
Original [issue 133](https://code.google.com/p/leveldb/issues/detail?id=133) created by doppelbauer on 2012-12-27T21:21:37.000Z:

It would be great to have a WriteOption &quot;DoNotOverwrite&quot;.
If two threads append a new record (new_key = last_key + 1), they would overwrite their records.

**Comment by cmumford** [comment]
If I'm understanding correctly this can be easily fixed by application code to synchronize these two threads. This doesn't sound like a feature that should be in the database.

**Comment by jessetane** [comment]
Personally I think it would be convenient to have this as a WriteOption. The issue can be worked around in application code, but it can still be a bit of a [pain / gotcha](https://github.com/substack/level-lock).

IndexedDB appears to specify this functionality: 
https://www.w3.org/TR/IndexedDB/#widl-IDBObjectStore-add-IDBRequest-any-value-any-key

so, in addition to being handy for Node peoples, having this feature here might even simplify Chromium's implementation?
https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/indexed_db/indexed_db_database.cc&rcl=1453854707&l=995
