### ISSUE TITLE
install target would be useful in Makefile

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#144]
Original [issue 138](https://code.google.com/p/leveldb/issues/detail?id=138) created by jussi.kukkonen@intel.com on 2013-01-09T09:08:32.000Z:

An install target in the Makefile would be useful, currently all linux OSes wishing to distribute leveldb must carry patch doing that.

I'll attach a patch.

**Comment by cmumford** [comment]
If this can be tested on travis-ci then we can add it.

**Comment by antran89** [comment]
Hi @cmumford,
Any good things on this request. I found that this request is very useful for normal user. Please merge it as possible.

**Comment by cmumford** [comment]
N/A now that leveldb uses CMake.
