### ISSUE TITLE
A .pc file pkg-config would be useful for linux OSes

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#145]
Original [issue 139](https://code.google.com/p/leveldb/issues/detail?id=139) created by jussi.kukkonen@intel.com on 2013-01-09T09:36:29.000Z:

Another thing most linux distributors would find very useful: a leveldb.pc file to describe the shared library.

I will attach a patch.

**Comment by awalton** [comment]
Ping? Can we please get this merged?

**Comment by kirilltitov** [comment]
Please implement it, we in Swift community are having huge problems with it.

**Comment by JaapWijnen** [comment]
Indeed waiting for something like this!

**Comment by cmumford** [comment]
Closing this issue and will track under issue #658 which has a bit more information relevant to implementing this feature using CMake.
