### ISSUE TITLE
build_detect_platform line ending error

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#147]
Original [issue 141](https://code.google.com/p/leveldb/issues/detail?id=141) created by gmargari on 2013-01-22T13:41:16.000Z:

<b>What steps will reproduce the problem?</b>
1. git clone https://code.google.com/p/leveldb/
2. cd leveldb
3. make

<b>What is the expected output? What do you see instead?</b>
It should compile. I get an error:
$ make
/bin/sh: 1: ./build_detect_platform: not found
Makefile:18: build_config.mk: No such file or directory
make: **\* No rule to make target `build_config.mk'.  Stop.

./build_detect_platform actually exists, but when executed it prints:
$ ./build_detect_platform 
bash: ./build_detect_platform: /bin/sh^M: bad interpreter: No such file or directory

<b>What version of the product are you using? On what operating system?</b>
leveldb 1.9, Ubuntu 12.04.

<b>Please provide any additional information below.</b>
'dos2unix build_detect_platform' fixes the problem

**Comment by phantanthanh1996** [comment]
Hi sir, i am having same proplem with you, could you pls tell me how to fix it? Thank you
