### ISSUE TITLE
Error if directory we're trying to create the database in doesn't exist

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#173]
Original [issue 167](https://code.google.com/p/leveldb/issues/detail?id=167) created by kkooporation on 2013-05-11T09:57:47.000Z:

<b>What steps will reproduce the problem?</b>
1. open a database
2. bazinga!

(we should ditch the standard questions here..)

/*What is the expected output? What do you see instead?
<b>What version of the product are you using? On what operating system?</b>
Please provide any additional information below.*/

When a database is being opened in a folder which itself does not exist, LevelDB errors with a dubious error message:

```
OpenError: IO error: ./db/root.db/LOCK: No such file or directory
    at [..]/levelup.js:113:25
```

As this came up quite some times, we discussed the process here; either the path will recursively be created or instead an error being thrown indicating the specific issue.

We've been talking about this issue on GitHub regarding LevelDOWN / UP [the NodeJS bindings for LDB] (https://github.com/rvagg/node-levelup/issues/135) and came to the conclusion this would have to be implemented in LevelDB itself.

Of course, I'd welcome a discussion here — thanks!

**Comment by hgqislub** [comment]
you shall use absolute path, because the shell+leveldb may can't figure out  "./" and "~/" relative path correctly.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by cmumford** [comment]
Agree with commentors - using relative paths (which are platform specific) is not a good idea.
