### ISSUE TITLE
Concurrency support for multiple processes (1 exclusive initializer / n readers)

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#182]
Original [issue 176](https://code.google.com/p/leveldb/issues/detail?id=176) created by shri314 on 2013-06-10T20:03:38.000Z:

Can the designers of leveldb explain the rational behind the design decision of not supporting multiple processes in leveldb implementation?

The documentation clearly says, under Concurrency section that: &quot;A database may only be opened by one process at a time. The leveldb implementation acquires a lock from the operating system to prevent misuse.&quot;

Currently I can see that when one process opens level db, it uses fcntl with RW lock (exclusive lock). However this is a severely limiting, as no other process can ever open the same database even if it wants to just inspect the database contents for RDONLY purposes. 

The use case for example is - one process exclusively opens leveldb database and fills up the database, then closes it. Then n different processes start reading that database.

**Comment by fatso83** [comment]
@sguada couldn't this be fixed by using Unix domain sockets? One process doing the bidding of the others through sockets.

**Comment by sguada** [comment]
@fatso83 that will make things quite complicated, I think just not blocking the DB when having multiple readers will be far easier.

**Comment by juliangruber** [comment]
for node.js, we solved this through github.com/juliangruber/multilevel, a library that exposes the local leveldb api over the network, so you don't need to change any code. maybe that works for you as well?

**Comment by sguada** [comment]
@juliangruber thanks for the pointer, but we need a really fast access to leveldb, since typically have 200Gb DB with sequential readings speeds over 10Mb/s. Therefore a native access to leveldb will be the best.

**Comment by samritchie** [comment]
I’d also be interested in this - I’d like to use leveldb in an iOS App Group container. This is a sandboxed directory that can be accessed by different apps (or an app & its extensions), but generally the processes can’t communicate with each other at all. An 'open read-only' option like SQLite would be ideal.

**Comment by rightgenius** [comment]
Multiple processes scenario for Service and Activity is very common in Android. The lock strategy limits the app's background service accessing the database. It would be great if leveldb supports this.

**Comment by davidblurton** [comment]
I'd really like the option to open a leveldb read only. Even if it wasn't enforced, it would be nice to get a connection without creating the lock file, or override checking if the lock file exists.

**Comment by tamsky** [comment]
I'm interested in using leveldb as a static lookup table.  Guaranteed to be read-only at all times.  Can I get a connection without a lock file?

**Comment by emschwartz** [comment]
Any word on this issue? I also have a use case like those above where it would be really useful to be able to read from a leveldb instance from a separate process.

**Comment by pwnall** [comment]
One writer / multiple readers: seems like it'd require serious changes to the system.

No writer / multiple readers: you _might_ be able to do this with a read-only env and manifest reuse turned on. If you have a lot of reads and no writes, a different storage system might be more suitable.

In either case, this issue has been open for a while, and it seems like none of the maintainers is interested in implementing this. Sorry!

**Comment by emschwartz** [comment]
Ok, guess we have to switch to using rocksdb instead :/

**Comment by forgetso** [comment]
This is pretty frustrating. I've just learned enough Go to build a sharded LevelDB reader to find out that I can't create the DB instances in the partitions. Should've been testing with more than 1 partition, I guess...

**Comment by ohhmm** [comment]
Hi,

Maybe someone interested to know that shared_lock is implementable using single atomic.
With limitation of maximum read and write attempters accordingly at time of course.

Thanks,
Serg

**Comment by ohhmm** [comment]
> Ok, guess we have to switch to using rocksdb instead :/

Actually somewhat comparable performance for multithreading addition. Thanks!
I think that LevelDB maintainers do have good competitor to do more profiling.
https://www.influxdata.com/blog/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/
