### ISSUE TITLE
Add DB::SuspendCompactions() and DB:: ResumeCompactions() methods

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#190]
Original [issue 184](https://code.google.com/p/leveldb/issues/detail?id=184) created by chirino on 2013-07-01T13:33:37.000Z:

If an application wants to take a consistent backup of the leveldb data files, it needs to ensure that the background compaction threads are not modifying those files.

**Comment by dmitryduka** [comment]
On Windows, the .log file is opened in such a way, that the proposed solution breaks - it is opened with the sharing bit set to 0, which prevents the application from opening this file on read or copying it.
