### ISSUE TITLE
Lock operation not supported on afp share

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#211]
Original [issue 205](https://code.google.com/p/leveldb/issues/detail?id=205) created by renconbv on 2013-09-29T09:52:32.000Z:

When trying to open a database on a afp share, the following error is thrown:
IO error: lock db/LOCK: Operation not supported

When the db is located on a local file system everything works as expected.

While my code is based on levelup, leveldown and node.js I am pretty sure the issue is caused by the leveldb main code.

I am experiencing this on OSX using version 1.11.0 of leveldb which comes with leveldown  0.8.3.

**Comment by cmumford** [comment]
We've had several reports of leveldb issues locking/syncing with network filesystems. This is not a supported configuration.

**Comment by OJFord** [comment]
This seems also to affect FUSE filesystems. I'm not sure if it's a new limitation, or if the applications I noticed it in (keybase/client#24544 & Spotify) recently-ish started using leveldb.

In both cases they're using leveldb for cache/local storage in my home directory; which is decrypted on login and mounted with FUSE.

End-user workaround (that somewhat validates that's what's happening) is to symlink them or containing directory to somewhere outside the FUSE fs:
```
$ rm -r ~/.cache/spotify
$ ln -s /tmp/spotify ~/.cache/spotify
$ mkdir /tmp/spotify
```
