### ISSUE TITLE
leveldb does not compile with g++ 4.8.2

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#233]
Original [issue 227](https://code.google.com/p/leveldb/issues/detail?id=227) created by yair.toaff on 2014-03-03T15:03:48.000Z:

<b>What steps will reproduce the problem?</b>
1.run make with g++ 4.8.2
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
the expected result is make finished ok but i get errors &quot;ssize_t does not name a type&quot; from db/db_iter.cc

<b>What version of the product are you using? On what operating system?</b>
tried it both with 1.14 &amp; 1.15

<b>Please provide any additional information below.</b>

**Comment by tfarina** [comment]
I just cloned it now and built with no issues.

$ g++ --version
g++ (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Should we close this bug?

**Comment by cmumford** [comment]
Sounds good - please do.

**Comment by tfarina** [comment]
Unfortunately I can't close this issue myself. The 'Close' button is not available for me. :/

**Comment by g1itch** [comment]
Maybe the problem not in gcc but in uClibc. I cannot build leveldb for openwrt without ```#include <sys/types.h>```.
