### ISSUE TITLE
libmemenv should be available as a shared library

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#236]
Original [issue 230](https://code.google.com/p/leveldb/issues/detail?id=230) created by luke@dashjr.org on 2014-03-22T20:12:34.000Z:

nt

**Comment by sbraz** [comment]
Hi @cmumford @pwnall is there any chance to see this implemented upstream?

**Comment by cmumford** [comment]
Hi @sbraz. I'm not sure I understand why this would be needed. Can you explain your interest in it being in its own shared library?

**Comment by sbraz** [comment]
@cmumford It's used by the bitcoin code. That's why Gentoo reported this bug, here is ours:
https://bugs.gentoo.org/show_bug.cgi?id=505320
On my system, all the bitcoin binaries are linked with libmemenv.so.
```
scanelf -n /usr/bin/bitcoind |grep libmem
ET_DYN libunivalue.so.0,libleveldb.so.1,libmemenv.so.1,libsecp256k1.so.0,libboost_system.so.1.65.0,libboost_filesystem.so.1.65.0,libboost_program_options.so.1.65.0,libboost_thread.so.1.65.0,libboost_chrono.so.1.65.0,libdb_cxx-4.8.so,libpthread.so.0,libcrypto.so.1.0.0,libevent_pthreads-2.1.so.6,libevent-2.1.so.6,libstdc++.so.6,libm.so.6,libgcc_s.so.1,libc.so.6 /usr/bin/bitcoind
```

It's already available as a static library, it seems to make sense to include it as a dynamic one too.

**Comment by cmumford** [comment]
Thanks @sbraz. We created a shared library for leveldb a while ago and NewMemEnv is one of the exported functions. See https://github.com/google/leveldb/blob/master/helpers/memenv/memenv.h. I believe that you are probably using an old fork of leveldb that just needs to be brought up to date.

If you can confirm I will probably mark this bug as closed. Thx.

**Comment by sbraz** [comment]
@luke-jr can you confirm that we no longer need the separate libmemenv.so?

**Comment by luke-jr** [comment]
dev-libs/leveldb-1.18-r2 installs a libleveldb.so.1 that doesn't seem to export any symbols matching `/memenv/i`. Furthermore, the configure script for obvious reasons actually checks that it can link to `-lmemenv`, and fails if it isn't available (when/if `-lleveldb` actually exports NewMemEnv, perhaps this can be changed, but it won't work as-is today).

**Comment by cmumford** [comment]
@luke-jr that's either a fork of this repo, or a configuration that comes from a distribution as the history in this project doesn't contain `lmemenv`. I built the shared library and it does contain this symbol:

```
0000000000058700 T _ZN7leveldb9NewMemEnvEPNS_3EnvE
```

I think you'll just need to update that reference to 1.20 (but possibly origin/master/HEAD) to get this symbol.

**Comment by luke-jr** [comment]
@cmumford I was referring to [Bitcoin Knots](http://bitcoinknots.org/), which bundles LevelDB, but can also be told to link to the system library if configured `--with-system-leveldb`

**Comment by cmumford** [comment]
Looks like Bitcoin Knots is using a forked/old version of leveldb. Closing this issue as this project currently exports NewMemEnv.

**Comment by luke-jr** [comment]
Building master, NewMemEnv still does not exist in any of the installed include files.

**Comment by luke-jr** [comment]
3fdd76bd14ff122c6881d7f15ec5cb2629241e7a didn't fix this (nor does it seem to be fixed otherwise); please reopen
