### ISSUE TITLE
Provide autotools or cmake buildsystem

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#237]
Original [issue 231](https://code.google.com/p/leveldb/issues/detail?id=231) created by tolga.dalman on 2014-03-22T20:50:09.000Z:

LevelDB is a great library, but cross-compiling is always a pain. Also, there are particular issues that stem from the custom makefiles provided by LevelDB (e.g., issue #&nbsp;230 probably could have been avoided with a proper buildsystem).

**Comment by cmumford** [comment]
leveldb is currently POSIX on Linux (or similar) platform. No current plans for autotools or cmake support.

**Comment by pwnall** [comment]
For folks who might happen to land here -- we now have CMake support.
