### ISSUE TITLE
Not worwing with make install and autoreconf

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#255]
Original [issue 249](https://code.google.com/p/leveldb/issues/detail?id=249) created by swojskichlopak@wp.pl on 2014-08-15T22:16:55.000Z:

PCLinuxOS 32bit

+ cd leveldb-1.15.0
+ '[' 1 -eq 1 ']'
+ make install DESTDIR=/home/gg/src/rpm/BUILDROOT/leveldb-1.15.0-1.i386
make: *** No rule to make target 'install'.  Stop.
error: Bad exit status from /home/gg/src/tmp/rpm-tmp.9GF1rG (%install)

Ok I can try use autoreconf, but not working ...

autoreconf -ivf
./configure 
make %{?_smp_mflags}

+ cd leveldb-1.15.0
+ '[' 1 -eq 1 ']'
+ '[' 1 -eq 1 ']'
+ autoreconf -ivf
autoreconf: 'configure.ac' or 'configure.in' is required
error: Bad exit status from /home/gg/src/tmp/rpm-tmp.Oa2vFm (%build)

I see OpenSuse use debian path, I will try

**Comment by cmumford** [comment]
Hi @willnorris:

Thanks for submitting this issue. Our goal is to keep both the source/build/docs as minimal as possible. Installation is platform dependent so will probably not be supported by our Makefile.

**Comment by willnorris** [comment]
huh?  why did I get mentioned on this?

**Comment by cmumford** [comment]
Wow - I have no idea. Something wrong with auto-completion (user error?). Sorry Will.
