### ISSUE TITLE
leveldb on ios jailbreak app will raise exception code :0x00000000dead10cc

### ISSUE THREAD

**Issue by dhckang** [google/leveldb#265]
hello everyone,I'm a ios developer from china.i got something trouble

leveldb on ios jailbreak app will raise exception code :0x00000000dead10cc

here is Exectption Info:
Incident Identifier: 36BCFFE2-8553-4CC0-8E09-B5CD1240D88C
CrashReporter Key:   f5e5670138123e620e94da83d6faa52f3ab087ab
Hardware Model:      iPhone7,2
Process:             Process [2878]
Path:                /Applications/Process.app/Process
Identifier:          Process
Version:             ???
Code Type:           ARM (Native)
Parent Process:      launchd [1]
Date/Time:           2014-08-09 21:03:29.418 +0800
Launch Time:         2014-08-09 21:03:28.826 +0800
OS Version:          iOS 8.1 (12B411)
Report Version:      105
Exception Type:  00000020
Exception Codes: 0x00000000dead10cc
Highlighted Thread:  0
Application Specific Information:
<FBApplicationProcess: 0x143217810; Process; pid: 2878> was suspended with locked system files: 
/private/var/mobile/Library/Process/Library/$dbname/LOCK

here is apple's description for this exception code:
The exception code 0xdead10cc indicates that an application has been terminated by iOS because it held on to a system resource (like the address book database) while running in the background.

it's happen when app in background write or read database and cause the app crash then relaunch then crash then relaunch...forever

why ios treat my own db as system resource. is it the db path cause? I can't understand

anyone can help?
orz

ps: sqplite is ok.

**Comment by cmumford** [comment]
Hi @dhckang:

leveldb doesn't directly support iOS. Good luck with your port.
