### ISSUE TITLE
Unit test failed on iOS platform using gtest

### ISSUE THREAD

**Issue by lovelpeople** [google/leveldb#267]
I make a simple iOS app as a target and replace main.mm with code below:

```
#include <gtest/gtest.h>

int main(int argc, char * argv[])
{
    testing::InitGoogleTest(&argc, (char **)argv);
    return RUN_ALL_TESTS();
}
```

and add a unittest.mm with code below:

```
TEST(LevelDBTest, InitOrDie) {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentPath = ([paths count] > 0) ? [paths objectAtIndex:0] : nil;
    NSString *dbPath = [NSString stringWithFormat:@"%@/testPath", documentPath];
    NSLog(@"Document path %@", documentPath);
    
    leveldb::DB *db;
    leveldb::Options options;
    options.create_if_missing = true;
    leveldb::Status status = leveldb::DB::Open(options, [dbPath UTF8String], &db);
    EXPECT_TRUE(status.ok());
}
```

Then it crashed at leveldb:DB:Open(...).

(Xcode 6.2 with iOS 8.2 SDK, OS X 10.10.1)

**Comment by cmumford** [comment]
Hi @lovelpeople:

Thank you for submitting this issue. For the time being the leveldb project intends to maintain support only for POSIX (on Linux). Please see [Contributing to the leveldb Project](https://github.com/google/leveldb#contributing-to-the-leveldb-project) for more details.
