### ISSUE TITLE
Multiple source files passed to the compiler are inconvenient for low-end hardware

### ISSUE THREAD

**Issue by mgorny** [google/leveldb#279]
The leveldb Makefile passes all source files to a single compiler call. This unnecessarily increases memory use and makes it impossible to benefit e.g. from distcc.

It would be preferably to instead compile source files separately and then link them together. If further optimization is desired, LTO can be used.

**Comment by cmumford** [comment]
Agreed. It first makes libleveldb.so.1.18 in a single call to g++, and then compiles the *.cc files individually into object files before linking libleveldb.a. Doesn't seem very efficient.

**Comment by cmumford** [comment]
Compiles nicely on my Raspberry Pi model 1
