### ISSUE TITLE
Potential typo in documentation

### ISSUE THREAD

**Issue by wouterbeek** [google/leveldb#280]
On the [documentation page](http://htmlpreview.github.io/?https://github.com/google/leveldb/blob/master/doc/index.html) the following code snippet is mentioned:

```cpp
#include <assert>
```

According to a clever colleague of mine this should be `cassert` instead. Could this me a typo in the docs?

**Comment by cmumford** [comment]
Thx wouterbeek. Fixed, and should be in the next code push.
