### ISSUE TITLE
When input data out of Disk?

### ISSUE THREAD

**Issue by Jui-Yu-Hsieh** [google/leveldb#287]
1.Is any APIs of levelDB that could delete data or SSTable where disk is not enough?
( It will stop writeopration at Write-Ahead-Log step)

2.All Levels is full by SSTable , Can program update new row-key into LevelDB ?

3.Can turn off Write-Ahead-Log of levelDB?

**Comment by cmumford** [comment]
Please post questions to the discussion forum https://groups.google.com/forum/#!forum/leveldb
