### ISSUE TITLE
[BigProblem]leveldb(cpp) && leveldb(python) open the same db will lose data!!!!

### ISSUE THREAD

**Issue by w359405949** [google/leveldb#292]
step:

1, use leveldb[cpp] create and write some data.
2, use leveldb[python](pip install leveldb) read and write new data.
3, use leveldb[cpp] read the data failed, get nothing.

currently, we use https://github.com/forhappy/cpy-leveldb instead of the pip package.

**Comment by cmumford** [comment]
I'm assuming that if step 2 (python) is omitted then data can be read a second time? Do you have any logs, or additional information as to what is going wrong?

**Comment by cmumford** [comment]
Please reopen if this can be reproduced with the leveldb library only.
