### ISSUE TITLE
port.h missing windows includes

### ISSUE THREAD

**Issue by dtmoodie** [google/leveldb#293]
port.h should include the following:

#if defined(LEVELDB_PLATFORM_WINDOWS)
#include "port/port_win.h"

**Comment by ralphtheninja** [comment]
:+1:

**Comment by cmumford** [comment]
The intent is to only include port*.h files that actually exist in the library which has no port_win.h.

**Comment by nslay** [comment]
I forked this over the weekend and made {port,env}_win32.{h,cc} files as needed.

**Comment by chfast** [comment]
@nslay can you files be send as a PR?

is it something like https://github.com/justmoon/leveldb-mingw/blob/master/port/port_win.h ?

**Comment by cmumford** [comment]
Hi @dtmoodie 

Thank you for submitting this pull request. For the time being the leveldb project intends to maintain support only for POSIX (on Linux). Please see [Contributing to the leveldb Project](https://github.com/google/leveldb#contributing-to-the-leveldb-project) for more details.
