### ISSUE TITLE
Can not compile and link on Mac OS X (Golang)

### ISSUE THREAD

**Issue by mkhadilk** [google/leveldb#302]
I am trying to compile and link the leveldb lib to Golang using CGO. It works on Linux distro but on Mac OS x, we get following error.
 "_leveldb_writeoptions_destroy", referenced from:
      __cgo_e4dde6ef3f21_Cfunc_leveldb_writeoptions_destroy in leveldblib.cgo2.o
     (maybe you meant: __cgo_e4dde6ef3f21_Cfunc_leveldb_writeoptions_destroy)
ld: symbol(s) not found for architecture x86_64

I am able to build (compile) leveldb but when I link using cgo, it gives above errors.

**Comment by cmumford** [comment]
I haven't used CGO. This project does link on OSX - we have Travis-CI building via gcc and clang on OSX. Is this something with CGO? I will close this issue, but if you feel there's an actual issue with leveldb on OSX feel free to reopen with additional information.
