### ISSUE TITLE
Any plans on releasing 1.19 soon?

### ISSUE THREAD

**Issue by ralphtheninja** [google/leveldb#305]
The support for `arm64` is a nice thing to have and I wouldn't mind a new release 1.19 :) Any thoughts on this?

**Comment by Diapolo** [comment]
Is this project still actively developed?

**Comment by Enkin** [comment]
@Diapolo Apparently yes !

**Comment by Enkin** [comment]
https://github.com/google/leveldb/issues/321

**Comment by cmumford** [comment]
I discussed with Sanjay and our thought was that there wasn't done after 1.18 to warrant a release. The new manifest/log reuse feature appears to increase corruption slightly, so our thought was to fix that, and then do a 1.19 release.

**Comment by ralphtheninja** [comment]
> I discussed with Sanjay and our thought was that there wasn't done after 1.18 to warrant a release. The new manifest/log reuse feature appears to increase corruption slightly, so our thought was to fix that, and then do a 1.19 release.

That sounds good. Happy things have started to move again! :)

**Comment by davidlt** [comment]
+1, would be nice to see official tag sooner then later due to arm64/aarch64 support. Especially considering that distributions tend to pack software based on release tags.

**Comment by cmumford** [comment]
OK. I'm working to merge pull request #309, afterwards I think we can probably mint a 1.19 release.
