### ISSUE TITLE
How to get records by insertion order？

### ISSUE THREAD

**Issue by psychoss** [google/leveldb#312]
i very like the leveldb's power of  the fastest high-performce and its easy to deploy. but still have a problem, how to get records by insertion order？

i have a database with variety  of prefixes. like:

```
aaa-
bbb-
ccc-
```

i want to get the last updated records ,use the SeekToLast() method then iterate the keys by 20 or whatever else。but the result always same. how to slove the problem. hope you help.

**Comment by juliangruber** [comment]
You need to create an index yourself, something like DATE!ID => ROW

**Comment by cmumford** [comment]
Closing as answered.
