### ISSUE TITLE
Need an api GetDbSize

### ISSUE THREAD

**Issue by ketor** [google/leveldb#318]
In some usercases, we need to get the totol file size of leveldb, and we need to get this information in our C++ programs directly.

But there is no function in db.h that provide total file size of all level files.
I would like to create a PR to fix this. Please help to review.

Thanks.

**Comment by ketor** [comment]
Fixed in PR: 319

**Comment by cmumford** [comment]
We'd like to keep the leveldb API small. Any program can easily calculate the database size by stat'ing the files in the leveldb database directory - and do so more accurately than this function which omits logs, etc. leveldb::DB::GetApproximateSizes() is warranted given that it supports a key range, but this looks easy to implement within the client. Please let me know if I've overlooked anything.

**Comment by cmumford** [comment]
Can you explain why leveldb::DB::GetApproximateSizes isn't sufficient? It measures the disk space of the key range (potentially all keys) and ignores files not in the db.

**Comment by cmumford** [comment]
Closing because it is unclear why `leveldb::DB::GetApproximateSizes` and filesystem size aren't sufficient. Feel free to reopen if necessary.
