### ISSUE TITLE
Support & Development (?)

### ISSUE THREAD

**Issue by Enkin** [google/leveldb#321]
Hello,

The project seems "dead" no update since a year now... it would be great if owners can give us some news :)

Did someone plans to handle the project ? ...If there are some  volunteers, i'm ready to help...

**Comment by turbopape** [comment]
+1 for me... Seems that not activity has been spotted since a while now...

**Comment by ralphtheninja** [comment]
+1 There are over 100 issues and 25 pull requests and there are many implementations depending on this code base :)

**Comment by codeVerySlow** [comment]
+1

**Comment by Enkin** [comment]
Even if there are good forks out there, LevelDB provides something that nothing else provides = a simple kernel... it would be very sad to loose it !!!

**Comment by pww1971** [comment]
https://sourceforge.net/projects/pwwhashmap/files/stats/timeline

it is update

**Comment by luoxn28** [comment]
+1, it is good for studing and using.

**Comment by cmumford** [comment]
Hi everyone. leveldb isn't dead, and sorry for letting things back up. We are currently writing up some guidelines for contributing to the leveldb project. This will help developers know what kinds of changes we're likely to accept or reject. At the moment leveldb is just POSIX, so any Windows ports will have to live in a leveldb fork somewhere. Once these guidelines are out I'll start to work through the backlog of pull requests and issues. I'll also close this issue once that new section is published.

**Comment by cmumford** [comment]
Contribution section has been updated: https://github.com/google/leveldb#contributing-to-the-leveldb-project. I will start the process of getting caught up on the pull requests/issues.
