### ISSUE TITLE
pwwMap is better than leveldb

### ISSUE THREAD

**Issue by pww1971** [google/leveldb#337]
http://sourceforge.net/projects/pwwhashmap/?source=navbar

**Comment by juliangruber** [comment]
no software is ever better than another software. if you want to be helpful you could highlight in which way pwwhashmap is superior and spark a healthy discussion. however i'm quite confident leveldb's architecture is here to stay for a long time.

**Comment by chai2010** [comment]
Mark :)

**Comment by pww1971** [comment]
think your advise
