### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [google/leveldb#338]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in the function "[Table::Open](https://github.com/google/leveldb/blob/77948e7eec0613fb5cbecb7e320b9498607030b5/table/table.cc#L85 "Table::Open function")".

**Comment by cmumford** [comment]
Are you referring to:

```c++
if (index_block) delete index_block;
```

**Comment by elfring** [comment]
@cmumford: Yes.

**Comment by cmumford** [comment]
Has been fixed in our internal repo. Will push this change out (hopefully) this week.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/google/leveldb/commit/32113439095d148fa93c7581a15f52ff26a389d3 "Deletion of an unnecessary check").
