### ISSUE TITLE
compile fail under android env near std::uint64_t

### ISSUE THREAD

**Issue by proller** [google/leveldb#340]
`
db/recovery_test.cc:110:17: error: 'uint64_t' is not a member of 'std'
     std::vector<std::uint64_t> result;
`

detail:
`
arm-linux-androideabi-g++  -Wl,--no-warn-mismatch -lm_hard  -I. -I./include -D_REENTRANT -DOS_ANDROID -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG db/recovery_test.cc out-static/db/builder.o out-static/db/c.o out-static/db/dbformat.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/table/block_builder.o out-static/table/block.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table_builder.o out-static/table/table.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env.o out-static/util/env_posix.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/port/port_posix.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/recovery_test 
db/recovery_test.cc:107:15: error: 'uint64_t' is not a member of 'std'
   std::vector<std::uint64_t> GetFiles(FileType t) {
               ^
db/recovery_test.cc:107:15: note: suggested alternative:
In file included from /tmp/ndk-arm-linux-leveldb/lib/gcc/arm-linux-androideabi/4.9/include/stdint.h:9:0,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/sys/types.h:34,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdio.h:50,
                 from ./db/dbformat.h:8,
                 from ./db/db_impl.h:10,
                 from db/recovery_test.cc:5:
/tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdint.h:49:23: note:   'uint64_t'
 typedef __uint64_t    uint64_t;
                       ^
db/recovery_test.cc:107:15: error: 'uint64_t' is not a member of 'std'
   std::vector<std::uint64_t> GetFiles(FileType t) {
               ^
db/recovery_test.cc:107:15: note: suggested alternative:
In file included from /tmp/ndk-arm-linux-leveldb/lib/gcc/arm-linux-androideabi/4.9/include/stdint.h:9:0,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/sys/types.h:34,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdio.h:50,
                 from ./db/dbformat.h:8,
                 from ./db/db_impl.h:10,
                 from db/recovery_test.cc:5:
/tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdint.h:49:23: note:   'uint64_t'
 typedef __uint64_t    uint64_t;
                       ^
db/recovery_test.cc:107:28: error: template argument 1 is invalid
   std::vector<std::uint64_t> GetFiles(FileType t) {
                            ^
db/recovery_test.cc:107:28: error: template argument 2 is invalid
db/recovery_test.cc: In member function 'size_t leveldb::RecoveryTest::DeleteLogFiles()':
db/recovery_test.cc:96:51: error: conversion from 'int' to non-scalar type 'std::vector<long long unsigned int>' requested
     std::vector<uint64_t> logs = GetFiles(kLogFile);
                                                   ^
db/recovery_test.cc: In member function 'uint64_t leveldb::RecoveryTest::FirstLogFile()':
db/recovery_test.cc:104:32: error: invalid types 'int[int]' for array subscript
     return GetFiles(kLogFile)[0];
                                ^
db/recovery_test.cc: In member function 'int leveldb::RecoveryTest::GetFiles(leveldb::FileType)':
db/recovery_test.cc:110:17: error: 'uint64_t' is not a member of 'std'
     std::vector<std::uint64_t> result;
                 ^
db/recovery_test.cc:110:17: note: suggested alternative:
In file included from /tmp/ndk-arm-linux-leveldb/lib/gcc/arm-linux-androideabi/4.9/include/stdint.h:9:0,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/sys/types.h:34,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdio.h:50,
                 from ./db/dbformat.h:8,
                 from ./db/db_impl.h:10,
                 from db/recovery_test.cc:5:
/tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdint.h:49:23: note:   'uint64_t'
 typedef __uint64_t    uint64_t;
                       ^
db/recovery_test.cc:110:17: error: 'uint64_t' is not a member of 'std'
     std::vector<std::uint64_t> result;
                 ^
db/recovery_test.cc:110:17: note: suggested alternative:
In file included from /tmp/ndk-arm-linux-leveldb/lib/gcc/arm-linux-androideabi/4.9/include/stdint.h:9:0,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/sys/types.h:34,
                 from /tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdio.h:50,
                 from ./db/dbformat.h:8,
                 from ./db/db_impl.h:10,
                 from db/recovery_test.cc:5:
/tmp/ndk-arm-linux-leveldb/sysroot/usr/include/stdint.h:49:23: note:   'uint64_t'
 typedef __uint64_t    uint64_t;
                       ^
db/recovery_test.cc:110:30: error: template argument 1 is invalid
     std::vector<std::uint64_t> result;
                              ^
db/recovery_test.cc:110:30: error: template argument 2 is invalid
db/recovery_test.cc:110:38: error: invalid type in declaration before ';' token
     std::vector<std::uint64_t> result;
                                      ^
db/recovery_test.cc:115:16: error: request for member 'push_back' in 'result', which is of non-class type 'int'
         result.push_back(number);
                ^
db/recovery_test.cc: In member function 'int leveldb::RecoveryTest::NumLogs()':
db/recovery_test.cc:122:31: error: request for member 'size' in 'leveldb::RecoveryTest::GetFiles((leveldb::FileType)0u)', which is of non-class type 'int'
     return GetFiles(kLogFile).size();
                               ^
db/recovery_test.cc: In member function 'int leveldb::RecoveryTest::NumTables()':
db/recovery_test.cc:126:33: error: request for member 'size' in 'leveldb::RecoveryTest::GetFiles((leveldb::FileType)2u)', which is of non-class type 'int'
     return GetFiles(kTableFile).size();
                                 ^
Makefile:365: recipe for target 'out-static/recovery_test' failed
make[2]: *** [out-static/recovery_test] Error 1
make[2]: Leaving directory '/home/proller/games/freeminer_android/build/android/deps/leveldb'
Makefile:412: recipe for target 
`

**Comment by cmumford** [comment]
Technically Android support is in an older branch - not at tip-of-tree, but this is a pretty reasonable request so will accommodate.

**Comment by est31** [comment]
It would be really nice if this got fixed, the code on the android branch is 4 years old, let's this not become a second [httpclient](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html).

**Comment by proller** [comment]
https://github.com/google/leveldb/commit/ea992b467b9f3c892ae87267ba908e97d532b1b2
