### ISSUE TITLE
Is it a good idea to use memcmp in starts_with function in slice.h?

### ISSUE THREAD

**Issue by Velconia** [google/leveldb#349]
when the starts_with implementation of slice.h
`bool starts_with(const Slice& x) const {                                         
      return ((size_ >= x.size_) &&                                                                                               
              (memcmp(data_, x.data_, x.size_) == 0));                                                               
 }  `
meets the usage:
`const char* s = "foo"; Slice slice_a(s, 0); Slice slice_b(s, 2); slice_a.starts_with(slice_b);`

something goes wrong then, because slice_a is NOT starts_with slice_b actually.

**Comment by Liuchang0812** [comment]
slice_a.starts_with(slice_b) return False. because len(a) < len(b).
