### ISSUE TITLE
is leveldb for me?

### ISSUE THREAD

**Issue by foice** [google/leveldb#356]
Hello,
 I need to keep records of runs of code I do, to later fetch the results of subsets of these runs without re-running my code each time.

I need to store entries of the type

``` <|par1 -> value11, par2-> value21|>  ->  number1```
where in reality I have tens of par and there will be millions of entries in the table.

Later I would like to do retrieve values for either full specification of

``` <|par1 -> value11, par2-> value21|>```
or by some sort of query where I ask for all entries that have par1 equal to some value

 ```<|par1 -> value11, par2-> *|> ```
I need to add entries to this table from a C++ program or something with minimal dependencies to be run on a cluster (prefer to avoid Python due to big pain for availability/installation of packages on cluster computing nodes), this is how I ended up on LevelDB.

I am not sure however LevelDB can do all this. In particular

I do not see how to make a query which is not just getting an entry from its full specification via the Get method;
it seems the key in LevelDB has to be a C++ type, so my type of entry would be not supported (what I am using is something like a Python dictionary).
Does LevelDB support these two features and I missed it? What else could I use instead of LevelDB?

Would be a big bonus if this library/database would support features like adding a new par to all keys or things like that.

I can do such thing in Wolfram Mathematica, but when I have more than 100K elements it gets slow. I could also use XML, but I suspect that dealing with a XML file of millions of entries will be horribly slow.

Thanks for the advice,
Roberto

**Comment by juliangruber** [comment]
You're right that leveldb only has a slice type for keys, but together with the lexicographic sorting it employs you should still be able to meet your requirements.

Encode a key to `"par1\x00value11\x00par2\x00value21"`, then you can for example query `<|par1 -> value11, par2-> *|>` by setting your iterator to `"par1\x00value11\x00par2\x00"` and reading until `"par1\x00value11\x00par2\x00\xff"`.

You see how the way you structure your keys in leveldb is an essential design decision.

> Would be a big bonus if this library/database would support features like adding a new par to all keys or things like that.

You can make it support it by the way you design your key space. Just store each pair under a separate keys and use iteration to combine them when reading.

> I can do such thing in Wolfram Mathematica, but when I have more than 100K elements it gets slow. I could also use XML, but I suspect that dealing with a XML file of millions of entries will be horribly slow.

You're damn right!

**Comment by cmumford** [comment]
This question seems answered to me. Please direct other questions to the [leveldb discussion group](https://groups.google.com/forum/#!forum/leveldb)
