### ISSUE TITLE
compile fail under centos6.7 

### ISSUE THREAD

**Issue by maishi** [google/leveldb#357]
db/recovery_test.cc:107: error: ‘uint64_t’ is not a member of ‘std’
db/recovery_test.cc:107: error: ‘uint64_t’ is not a member of ‘std’
db/recovery_test.cc:107: error: template argument 1 is invalid
db/recovery_test.cc:107: error: template argument 2 is invalid
db/recovery_test.cc: In member function ‘size_t leveldb::RecoveryTest::DeleteLogFiles()’:
db/recovery_test.cc:96: error: conversion from ‘int’ to non-scalar type ‘std::vector<long unsigned int, std::allocator<long unsigned int> >’ requested
db/recovery_test.cc: In member function ‘uint64_t leveldb::RecoveryTest::FirstLogFile()’:
db/recovery_test.cc:104: error: invalid types ‘int[int]’ for array subscript
db/recovery_test.cc: In member function ‘int leveldb::RecoveryTest::GetFiles(leveldb::FileType)’:
db/recovery_test.cc:110: error: ‘uint64_t’ is not a member of ‘std’
db/recovery_test.cc:110: error: ‘uint64_t’ is not a member of ‘std’
db/recovery_test.cc:110: error: template argument 1 is invalid
db/recovery_test.cc:110: error: template argument 2 is invalid
db/recovery_test.cc:110: error: invalid type in declaration before ‘;’ token
db/recovery_test.cc:115: error: request for member ‘push_back’ in ‘result’, which is of non-class type ‘int’
db/recovery_test.cc: In member function ‘int leveldb::RecoveryTest::NumLogs()’:
db/recovery_test.cc:122: error: request for member ‘size’ in ‘leveldb::RecoveryTest::GetFiles((leveldb::FileType)0u)’, which is of non-class type ‘int’
db/recovery_test.cc: In member function ‘int leveldb::RecoveryTest::NumTables()’:
db/recovery_test.cc:126: error: request for member ‘size’ in ‘leveldb::RecoveryTest::GetFiles((leveldb::FileType)2u)’, which is of non-class type ‘int’
make: *** [out-static/recovery_test] Error 1

**Comment by cjc211322** [comment]
Hello, I met the same problem. Do you solve it? Thank you!

**Comment by maishi** [comment]
@JianchaoCao  no

**Comment by cmumford** [comment]
Fixed in ea992b4.
