### ISSUE TITLE
Please add PhoneGap/Cordova support

### ISSUE THREAD

**Issue by SunboX** [google/leveldb#358]
Could you please provide a PhoneGap/Cordova wrapper for LevelDB so we can use it as data storage in hybrid apps?

**Comment by cmumford** [comment]
Not familiar with the details of adding this wrapper. Is this something that ban be tested on Linux and OSX? One of our feature requirements is that they all be testable (via Travis CI) to prevent regression.

**Comment by pwnall** [comment]
A cordova plugin for LevelDB would be fairly complex and should definitely live outside this repository. If you target reasonably modern WebViews, I suggest looking into IndexedDB.
