### ISSUE TITLE
Is it possible to seek to the first key less than a given key

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#36]
Original [issue 30](https://code.google.com/p/leveldb/issues/detail?id=30) created by john.carrino on 2011-08-13T18:34:17.000Z:

I would like to find the first key that is less than a given key. I can only think of two ways to achieve this goal and they both fail.
1. seek to key then go back one.  This fails because if the key you want is the last key, then you have an invalid iterator and you get a segfault.
2. seek to key, then check if iterator is invalid (because we are past the end), then set to seekToLast and do the read.  This fails because if a key comes in before the seekToLast, then you get the wrong value.

I have attached tests to try each one.  Is there an easier way I don't know about?

TEST(DBTest, IterPastEndThenPrev) { 
  ASSERT_OK(Put(&quot;a&quot;, &quot;va&quot;));
  Iterator\* iter = db_-&gt;NewIterator(ReadOptions());

  iter-&gt;Seek(&quot;b&quot;);
  ASSERT_EQ(IterStatus(iter), &quot;(invalid)&quot;);
  iter-&gt;Prev();
  ASSERT_EQ(IterStatus(iter), &quot;a-&gt;va&quot;);
}

TEST(DBTest, IterSnapshotViewSeekToEnd) { 
  ASSERT_OK(Put(&quot;a&quot;, &quot;va&quot;));
  Iterator\* iter = db_-&gt;NewIterator(ReadOptions());

  iter-&gt;Seek(&quot;b&quot;);
  ASSERT_EQ(IterStatus(iter), &quot;(invalid)&quot;);
  ASSERT_OK(Put(&quot;c&quot;, &quot;vc&quot;));
  iter-&gt;SeekToLast();
  ASSERT_EQ(IterStatus(iter), &quot;a-&gt;va&quot;);
}

**Comment by trylle** [comment]
I've run into the same issue re Prev on an "end" iterator (when Seek runs past the last key).

I tried John's tests on the latest code in master (7035af5fc36657447054617759854a726d31dbe0) and they both fail there.

On ab323f7e1ec53749653967e7d6a2fa1c922334f2, which was supposed to fix this issue, IterSnapshotViewSeekToEnd passes, but not IterPastEndThenPrev.

I currently have to use the dummy key approach suggested by David to get around it.
