### ISSUE TITLE
Mac Symbol Not Found for the Options Class

### ISSUE THREAD

**Issue by HarriBellThomas** [google/leveldb#360]
Hi all. I'm running the following code (cloned from this repo today) and am getting the symbol not found error described. I'm using the latest version of OSX (10.11.4) with the latest build of the Xcode Command Line tools, and have also tested this Ubuntu 14.04 (with the latest build of g++) and had the same error. Any help will be greatly appreciated.

```c++
#include "leveldb/db.h"
#include "leveldb/options.h"
#include "leveldb/write_batch.h"
#include <cassert>

...

leveldb::DB* db;
leveldb::Options options;
options.create_if_missing = true;
leveldb::Status status = leveldb::DB::Open(options, "./tmp/testdb", &db);
assert(status.ok()); 
```

```
dyld: lazy symbol binding failed: Symbol not found: __ZN7leveldb7OptionsC1Ev
  Referenced from: /Users/Harri/Sites/RAILS/CitIO/citio/CitIO/citio.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN7leveldb7OptionsC1Ev
  Referenced from: /Users/Harri/Sites/RAILS/CitIO/citio/CitIO/citio.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```

The line causing the error is `leveldb::Options options;`, found by trial and error testing each line individually.

**Comment by cmumford** [comment]
Are you saying that you cannot build any of the stock leveldb applications (like if you ran `make check`) - or you having difficulty linking your program that's trying to use leveldb?

**Comment by cmumford** [comment]
Issue seems abandoned - closing.
