### ISSUE TITLE
uint64_t is not a member of "std"

### ISSUE THREAD

**Issue by mrmiywj** [google/leveldb#361]
Caused by  [LC107](https://github.com/google/leveldb/blob/master/db/recovery_test.cc#L107) and 
[LC110](https://github.com/google/leveldb/blob/master/db/recovery_test.cc#L110)

**Comment by mrmiywj** [comment]
Arch linux64  GCC 5.3.0

**Comment by cmumford** [comment]
Fixed in ea992b4
