### ISSUE TITLE
Key with larger sequence got compacted to elder level, while its smaller sequence incarnation stays in younger level

### ISSUE THREAD

**Issue by kezhuw** [google/leveldb#376]
[DBImpl::DoCompactionWork](https://github.com/google/leveldb/blob/master/db/db_impl.cc#L886) decides to finish current output if current output file is big enough or has too much overlap with its grandparents. Seems that keys with same user key but different sequence part may spread to multiple output files in compaction. If this happens, new level compaction may pick the file with newer version key and compact it to elder level. From now on, the key's newer version, which has larger sequence number, is stored in level greater than its old incarnation. If we try to get that key, we will get its old incarnation. See [Version::Get](https://github.com/google/leveldb/blob/master/db/version_set.cc#L323) for implementation details.

I push a pull request #375 to fix this. Any maintainer here to review that pull request ?

**Comment by kezhuw** [comment]
@cmumford Can you take a look at this issue and review #375 ? Thanks!

**Comment by bwzhang2011** [comment]
@cmumford, any update with such issue ?

**Comment by kezhuw** [comment]
Closes this due to duplication of #320, see corresponding pull request #339 for fix.
