### ISSUE TITLE
LevelDB for Windows

### ISSUE THREAD

**Issue by David-Haim** [google/leveldb#379]
I wonder why there is not built in port for Windows OS in this repository (or there was one, but was forsaken), and is it OK for me to PR a Windows port?  

Plus, I wonder why do we need a special port for each OS when the current C++ standard has everything we need (mutex, condition variable, atomic variables and init_once) , is it because of historical reasons?

**Comment by cmumford** [comment]
We have lots of requests for a Windows port. We won't add an official Windows port without continuous integration support, and Travis CI doesn't yet support Windows. Regarding C++ features, that would require that we limit support to only more modern compilers (C++ 11).
