### ISSUE TITLE
db open,   recover spend a lot of time

### ISSUE THREAD

**Issue by dalent** [google/leveldb#380]
I restart the leveldb but the log show recover versionset end. count 1148642, cost: 51941024.
It cost 51 seconds ,Why this happened  ?

**Comment by dalent** [comment]
I seems that the MANIFEST get bigger and bigger , when re open , the levedb will parse it ,cause it very slow? Why ?

**Comment by cmumford** [comment]
leveldb currently compacts the database upon open if there is a non-empty log. v1.19 has a new feature to reuse the manifest - which avoids this. The manifest should not grow as a new one is created for each database compaction.
