### ISSUE TITLE
crash on leveldb::Block::NewIterator(leveldb::Comparator const*)

### ISSUE THREAD

**Issue by starFelix** [google/leveldb#388]
<img width="943" alt="a" src="https://cloud.githubusercontent.com/assets/5734060/16371155/3f23e63e-3c77-11e6-9ff3-3b579281f632.png">

the crash stack like above

**Comment by cmumford** [comment]
@starFelix Is this reproducible?

**Comment by starFelix** [comment]
@cmumford

**Comment by starFelix** [comment]
@cmumford 
The crash stack was collected online. I can't reproduce this bug on my device, but it really crash a lot.
I used leveled on an iOS project. May be some bug in File IO?

**Comment by cmumford** [comment]
@starFelix I'm scrubbing old bugs. Even though iOS isn't officially supported, if you have a reproduction case on the current release I can probably look into this. I'm going to close this issue, but please reopen if you have a repro that you can attach.

**Comment by mrrobo1510** [comment]
@starFelix did you resolved it?
