### ISSUE TITLE
Compiling a wallet on ubuntu

### ISSUE THREAD

**Issue by ghost** [google/leveldb#389]
Hello, i am trying to compile a wallet on a ubuntu 14 32-bit wallet and i always get a strenge error, i looked everywhere in the web but i found nothing.

lcrypto -lgdi32 -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 
/home/ubuntu/build/blumedtoken/src/leveldb/libmemenv.a: could not read symbols: Archive has no index; run ranlib to add one
collect2: ld returned 1 exit status
make[1]: *** [release/blumedtoken-qt.exe] Error 1
make[1]: Leaving directory `/home/ubuntu/build/blumedtoken'
make: *** [release] Error 2

The coin in question is blumedtoken.

**Comment by cmumford** [comment]
My guess is that libmemenv.a is an archive for a different platform. Try:

`file /home/ubuntu/build/blumedtoken/src/leveldb/libmemenv.a`

and see what it reports. Further questions are better asked on the [discussion group](https://groups.google.com/forum/#!forum/leveldb).

**Comment by blockchaintrainer** [comment]
I am also facing the same issue, did you find any solution?
