### ISSUE TITLE
stretch: powerloss resulted in corruption. General recovery procedure? 

### ISSUE THREAD

**Issue by seapasulli** [google/leveldb#402]
I use ceph which has 3 leveldb databases (one on each monitor node). We recently had a power outage at our datacenter and all 3 leveldb databases are corrupt. I tried recovery via leveldb.recovery() but this doesn't seem to have worked.

I made a copy of the original directory just in case prior to attempting to recover. Is there any recovery guidelines or procedures?

I am getting the following errors which may be more ceph related:
`2016-08-10 21:21:48.298232 7f2fe195d8c0  0 ceph version 0.94.7 (d56bdf93ced6b80b07397d57e3fa68fe68304432), process ceph-mon, pid 79794
Corruption: error in middle of record
2016-08-10 21:21:52.963409 7f2fe195d8c0 -1 error opening mon data directory at '/var/lib/ceph/mon/ceph-kh08-8': (22) Invalid argument
`

is there a way to continue or recover/remove the record based on the files in the other 2 ceph monitors. If not is there a general procedure for recovery?

**Comment by andreasbaumann** [comment]
Wieder klingelt da etwas bei mir...

On August 11, 2016 5:02:58 AM CEST, Look Crabs <notifications@github.com> wrote:
>I use ceph which has 3 leveldb databases (one on each monitor node). We
>recently had a power outage at our datacenter and all 3 leveldb
>databases are corrupt. I tried recovery via leveldb.recovery() but this
>doesn't seem to have worked.
>
>I made a copy of the original directory just in case prior to
>attempting to recover. Is there any recovery guidelines or procedures?
>
>I am getting the following errors which may be more ceph related:
>`2016-08-10 21:21:48.298232 7f2fe195d8c0  0 ceph version 0.94.7
>(d56bdf93ced6b80b07397d57e3fa68fe68304432), process ceph-mon, pid 79794
>Corruption: error in middle of record
>2016-08-10 21:21:52.963409 7f2fe195d8c0 -1 error opening mon data
>directory at '/var/lib/ceph/mon/ceph-kh08-8': (22) Invalid argument
>`
>
>is there a way to continue or recover/remove the record based on the
>files in the other 2 ceph monitors. If not is there a general procedure
>for recovery? 
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/google/leveldb/issues/402

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by juliangruber** [comment]
> Wieder klingelt da etwas bei mir...

is it your banana phone? 😮

**Comment by andreasbaumann** [comment]
On Thu, Aug 11, 2016 at 12:43:17AM -0700, Julian Gruber wrote:
> > Wieder klingelt da etwas bei mir...
> 
> is it your banana phone? 😮 

Yeah. Sorry about that. Completly mis-posted.

Cheers

Andreas

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/leveldb/issues/402#issuecomment-239093374

-- 
Andreas Baumann
Trottenstrasse 20
CH-8037 Zuerich
Telefon: +41(0)76/373 01 29
E-mail: mail@andreasbaumann.cc
Homepage: www.andreasbaumann.cc

**Comment by cmumford** [comment]
I suspect filesystem corruption. Sorry I've never managed ceph cluster before. leveldb is used in Chrome which runs on many many phones so lots of unplanned power-down's. I suggest asking this question on the [leveldb discussion group](https://groups.google.com/forum/#!forum/leveldb). Your mention of "leveldb.recovery()" sounds like maybe you're using a wrapper library (Python?). If there's an option to enable paranoid checks I suggest using that.
