### ISSUE TITLE
bg compact cost a lot of time

### ISSUE THREAD

**Issue by dalent** [google/leveldb#414]
The backgroup compact task , sometimes cost a lot of time ,I don't know why, it is a  random event. from the log I have  found: 
`20:01:40  Compacting 1@2 + 3@3 files` 
after 18 second , print the first generated table:
`20:01:58 Generated table #9013756: 209064 keys, 8833088 bytes`
any suggestion?
the log:
2016/10/07-20:01:40.638415 7fd6475fe700 seek com
2016/10/07-20:01:40.639843 7fd6475fe700 Compacting 1@2 + 3@3 files
2016/10/07-20:01:58.657461 7fd6475fe700 Generated table #9013756: 209064 keys, 8833088 bytes
2016/10/07-20:01:59.199870 7fd6475fe700 Generated table #9013757: 13062 keys, 8594234 bytes
2016/10/07-20:01:59.775536 7fd6475fe700 Generated table #9013758: 39561 keys, 8661310 bytes
2016/10/07-20:01:59.815346 7fd6475fe700 Generated table #9013759: 22 keys, 21015 bytes
2016/10/07-20:01:59.815366 7fd6475fe700 Compacted 1@2 + 3@3 files => 26109647 bytes, [0 + 19175522]
2016/10/07-20:01:59.857105 7fd6475fe700 compacted to: files[ 0 54 455 7228 0 0 0 ]

**Comment by cmumford** [comment]
Normally leveldb compacts when:

1. The database is opened.
2. When the log gets full.
3. When CompactRange is called.

It shouldn't be random. You could enlarge the write_buffer_size (see options.h) to have compaction does less frequently.

**Comment by dalent** [comment]
It may caused by the hardware(bios version too low according to dell),  I migrated the leveldb to        another machine , It never happened .

  And there is any suggestion for the settings (options.h).
for example, I have a server:
    32     cores
    128G MEM
    4.5T  HD
what is the reasonable configure for the following ：
     write_buffer_size                    (32M)
     block_cache_size                   (104M)
     block_size                               (default)
     block_restart_interval            (default)
     kL0_CompactionTrigger        (2)
     kMaxMemCompactLevel       (default)
     kTargetFileSize                      (8M)
     kBaseLevelSize                      (134M)
     kUseMmapRandomAccess    (false)
     kDoSeekCompaction              (0)
It is OK?
