### ISSUE TITLE
build leveldb libraries for windows

### ISSUE THREAD

**Issue by bellaj** [google/leveldb#418]
Hi, is there any up to date documentation about how to build leveldb libraries for windows?

**Comment by delaneyj** [comment]
I build the [Node.js bindings](https://github.com/Level/leveldown) on Windows all the time.  You need windows sdk (forget if its 8.1 or 10) and visual studio 2015 installed.   Run this from the vs studio dev console, would have to have node installed.

```
npm init -y test_leveldb
cd test_leveldb
npm install --save levelup leveldown
```

If that works you should be able to see how they built it for your needs.

**Comment by bellaj** [comment]
Thank you I've used the leveldb from the bitcoin project

**Comment by cmumford** [comment]
There are leveldb forks that have Windows ports, but not one officially supported. See issue #363
