### ISSUE TITLE
what size of SStable is suitable?

### ISSUE THREAD

**Issue by CaixinGong** [google/leveldb#423]
Is any reason that the  default SStable size is 2MB?  the bigger size such as 64MB can make the disk throughput  higher and get a better random write performance. what's more, the simultaneously-open file number is limited by the system, the bigger size will have less files so that the table cache can cache more file to improve the random read performance. @cmumford @ghemawat

**Comment by cmumford** [comment]
As of a2fb086d07 you can now change the table file size. Note, not all tables are the same size. level-0 is the smaller size, but the file sizes grow as the levels increase. More info at https://rawgit.com/google/leveldb/master/doc/impl.html.
