### ISSUE TITLE
Move particular key range

### ISSUE THREAD

**Issue by pradeepanumala** [google/leveldb#424]
I would like to move a particular key range from one db instance to another. 
Can I directly move all the .sst files to the new db location and do a factory.repair on it ?
How can the cached data i.e data in .log file be moved ? If I move the .log files to new db and do a repair , the .log files are getting deleted. Whats the best way to move particular key range to another db ?

**Comment by cmumford** [comment]
*.log files only contain the most recent db changes. During database open (or repair) a db compaction is done which merges the log file into the tables (*.sst), and creates a new log file.

You can't solve this problem by copying files. You will need to write a program to open up both databases, iterate all key/values in one database, and write them to the other database.
