### ISSUE TITLE
what's the meaning  of the file extensions  like  "xxx.ldb" , "xxx.LOG" and so on  ?

### ISSUE THREAD

**Issue by 450606975** [google/leveldb#426]
I  create  a database  named testdb and write some records into , then  I  find  some  file in the testdb, include   000005.ldb, LOCK, LOG,000021.log,LOG.old, MANIFEST-000019 and CURRENT。

what's the purpose of them ?

**Comment by cmumford** [comment]
https://rawgit.com/google/leveldb/master/doc/impl.html

**Comment by mobitar** [comment]
Updated link: https://github.com/google/leveldb/blob/master/doc/impl.md
