### ISSUE TITLE
Question: Does LevelDB support a "floorEntry" operation?

### ISSUE THREAD

**Issue by MartinHaeusler** [google/leveldb#431]
Hello everyone,
I am currently checking out LevelDB, and since keys are explicitly ordered, I was wondering if LevelDB has support for the "floorEntry(key)" operation, as found for example in [Javas Navigable Map](http://docs.oracle.com/javase/7/docs/api/java/util/NavigableMap.html#floorEntry(K)). The semantics of this operation are as follows:

Given a key k, return the entry with the **largest** key **less than or equal** to k.

The interesting bit here is that the given key does not need to exist in the keyspace at all, in which case the operation returns the next-smaller entry. Can his be done efficiently in LevelDB without too much linear iteration over the keyspace?

Thanks,
Martin

**Comment by juliangruber** [comment]
you should be able to achieve this the simple way by:

1) create an iterator
2) seek to the target key
3) if valid, you found your value. otherwise
4) seeking backwards and you have your value
