### ISSUE TITLE
Use Google Test

### ISSUE THREAD

**Issue by fsareshwala** [google/leveldb#434]
LevelDB seems to implement its own testing framework. Why doesn't it use Google Test instead? I imagine that it is to avoid an extra dependency externally. Some of the other libraries open sourced by Google use Google Test, e.g. snappy. If Google has already open sourced Google Test, why reimplement it here? 

Wondering what the community or the original authors think of this. I couldn't find a discussion in the GitHub Issues regarding Google Test or a pull request asking to pull it in. Just wanted to start a discussion on it to see if there was support. If there is, I'm happy to do the work to port the tests over to Google Test.

Let me know 😬.

**Comment by pwnall** [comment]
We switched to googletest in https://github.com/google/leveldb/commit/1c58902bdcc8d129f3883606bbd8e59085b48878
