### ISSUE TITLE
New max file size option is not available from C API

### ISSUE THREAD

**Issue by olt** [google/leveldb#439]
The C API misses a `leveldb_options_set_max_file_size` function.
Pull requests is coming up. 

BTW: The new max_file_size works great and gives us a big performance boost for multi-GB datasets.

**Comment by cmumford** [comment]
A belated thank you @olt. Am pushing your change into the internal Google repo and it should appear here on GitHub fairly soon.

**Comment by olt** [comment]
The patch tickled back from internal Google repo via 47cb9e2a211e1d7157078ba7bab536beb29e56dc
