### ISSUE TITLE
Make Error on TACC Stampede

### ISSUE THREAD

**Issue by bmgroth** [google/leveldb#443]
Hello leveldb devs,

I have encountered an error while trying to install leveldb on the TACC Stampede supercomputer (Linux OS) with a fresh download.  After using make, I get an error compiling util/env_posix.o:

g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG -fPIC -c util/env_posix.cc -o out-shared/util/env_posix.o

util/env_posix.cc: In function ‘intptr_t leveldb::<unnamed>::MaxOpenFiles()’:
util/env_posix.cc:593: error: ‘numeric_limits’ is not a member of ‘std’
util/env_posix.cc:593: error: expected primary-expression before ‘int’
util/env_posix.cc:593: error: expected ‘;’ before ‘int’
make: *** [out-shared/util/env_posix.o] Error 1

I looked, and it appears that some compilers (eg g++ on Linux) require using the header <limits> when using std::numeric_limits:
[http://stackoverflow.com/questions/4798936/numeric-limits-was-not-declared-in-this-scope-no-matching-function-for-call-t](url)

I added #include <limits> to the header of this file and it compiled successfully.  I would recommend adding this to util/env_posix.o for other people using Linux.

Best,
Brandon Groth

**Comment by cmumford** [comment]
Thanks for reporting. Fixed in 95cd743
