### ISSUE TITLE
Data Change Notification Callbacks

### ISSUE THREAD

**Issue by qywx** [google/leveldb#445]
Hello. I am looking for database ability *notify me when value updated/changed*.
Here is my view of interface/usage pseudo-code:
```
db.addEvent("keyname", EventType::UPDATE, [](newVal){cout<<newVal;} );
db.addEvent("keyname", EventType::UPDATE, [](newVal,changerDbConnectionId){cout<<newVal;} );
```
SQLite has [Data Change Notification Callbacks](https://sqlite.org/c3ref/update_hook.html)

If there is now such feature, I would like to implement. So any help is welcome.

**Comment by cmumford** [comment]
Thanks @qywx. One of leveldb's goals is to remain simple and to provide a stable API. I think that if this is desired it would either need to be done in the app itself, or possibly switch to a different database engine.
