### ISSUE TITLE
compilation is error when changing OPT ?= -O2 -DNDEBUG to OPT ?= -g2 in Makefile

### ISSUE THREAD

**Issue by andyli029** [google/leveldb#447]
`g++ -I/usr/include -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DSNAPPY -g -c helpers/memenv/memenv.cc -o out-static/helpers/memenv/memenv.o
helpers/memenv/memenv.cc: In member function ‘leveldb::Status leveldb::<unnamed>::FileState::Read(uint64_t, size_t, leveldb::Slice*, char*) const’:
helpers/memenv/memenv.cc:67: error: ‘SIZE_MAX’ was not declared in this scope
make: *** [out-static/helpers/memenv/memenv.o] Error 1`

**Comment by andyli029** [comment]
the issue is fixed #448

**Comment by cmumford** [comment]
N/A now that we've switched to CMake.
