### ISSUE TITLE
How to make a multi-thread application with C, accessing a LevelDB?

### ISSUE THREAD

**Issue by loantonusi** [google/leveldb#452]
Hi,
I am a new with leveldb. 
Is there another option to make a multi-thread application accessing a LevelDB Database?
Any ideas or sample code would be extremely helpful. 
Thank you so much

**Comment by cmumford** [comment]
See the [concurrency](https://github.com/google/leveldb/blob/master/doc/index.md#concurrency) section of the documentation.

**Comment by htotvs** [comment]
Hello, @cmumford ! Thanks for your great work with `leveldb`.

I'm not a native speaker of either English or `leveldb`. So, I'm confused by the phrasing about Concurrency in the text that you quoted: there's _"different threads may write into or fetch iterators or call Get on the same database without any external synchronization"_, but there's also _"However other objects (like Iterator and WriteBatch) may require external synchronization."_

So, my question is: Is there a way to use `leveldb`'s concurrent abilities while using iterators ?

Could you please be as kind as to point me to a sample code where this question is enlightened ?

Thank you, 
Hilton

**Comment by pwnall** [comment]
Requests for specific sample code are best suited for StackOverflow.

**Comment by htotvs** [comment]
Hi, @pwnall  !

What about requests for explanation of documentation ? Are they fit for these issues ?
