### ISSUE TITLE
UnlockFile : is it meant to be used at all?

### ISSUE THREAD

**Issue by HeinrichGit** [google/leveldb#453]
With the current code, I have
`Status UnlockFile(FileLock* lock)`
and
`Status LockFile(const std::string& fname, FileLock** lock)`

`LockFile` returns `FileLock` NULL if the file has already been locked.

If I want to `UnlockFile` a specific file, how/where from do I obtain the needed `FileLock` for this specific file, i.e. how is it usage meant to be? Is `UnlockFile` meant to be used at all?

**Comment by hljyunxi** [comment]
file lock is used to ensure that we can open only one db instance per leveldb database.
