### ISSUE TITLE
Lock lost on double fork

### ISSUE THREAD

**Issue by p1ng0o** [google/leveldb#455]
When an app self detach, using double fork, or daemon, flock is lost, and anyone can re-attach database.

exemple:
initApp()
  initLevelDb()
detach()
-> Anyone own the LOCK file

maybe with pthread_atfork() we can attach an callback to renew the lock.

**Comment by ghemawat** [comment]
Hi Antoine,

I recommend that you fork before opening leveldb (or actually initializing
any common libraries).

flock is only one of the potential problems.  Any mutexes in the program,
as well as all the invariants they protect would have to be fixed up in the
child process.  E.g., suppose somebody has a hash-table and a linked-list
that are updated in lock-step protected by a mutex.  The owner of that
library would also have to provide a pthread_atfork handler to fix things
up.

And pthread_atfork is very hard to use correctly in a program that is
composed of libraries written by different authors.  There is no
well-define order in which to grab locks across such libraries, so the
locks that would need to be acquired via pthread_atfork before forking
would be very prone to deadlock.

Some background reading:
http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them
http://stackoverflow.com/questions/6078712/is-it-safe-to-fork-from-within-a-thread
https://thorstenball.com/blog/2014/10/13/why-threads-cant-fork/

**Comment by p1ng0o** [comment]
Thanks for your answer. 

Unfortunately, in on particular project, I'm not able to initialize before fork. (by design)
As I understand, the "best" way can be:
* open leveldb
* do init stuff inside first pid
* doublefork
* closing leveldb previously opened in child
* re-open a fresh leveldb in child process
* use leveldb 👍

**Comment by ghemawat** [comment]
On Tue, Mar 7, 2017 at 9:28 AM, Antoine Aubert <notifications@github.com>
wrote:

> Thanks for your answer.
>
> Unfortunately, in on particular project, I'm not able to initialize before
> fork. (by design)
> As I understand, the "best" way can be:
>
>    - open leveldb
>    - do init stuff inside first pid
>    - doublefork
>    - closing leveldb previously opened in child
>    - re-open a fresh leveldb in child process
>    - use leveldb 👍
>
> —
>

The preceding state leaves leveldb open in both the initial process, and in
the child process.  That is not allowed (a single leveldb database must
only be used by one process at a time).  The whole flock business is an
attempt to prevent such mistakes.

Perhaps the parent can close leveldb before it forks.  Though even then,
the general issues I mentioned about thread/fork apply.

**Comment by p1ng0o** [comment]
Thanks for your help. Solved
