### ISSUE TITLE
mmap use too much memory when increase max_file_size

### ISSUE THREAD

**Issue by hoganfan** [google/leveldb#463]
if set options.max_file_size to a big value like 512 << 20, mmap will use too much memory when open too many PosixMmapReadableFile.
will leveldb add mmap_limit to Options?

**Comment by adam-azarchs** [comment]
Why would you make 512mb files?  As the [documentation](https://github.com/google/leveldb/blob/master/doc/index.md#block-size) states, "There isn't much benefit in using blocks smaller than one kilobyte, or larger than a few megabytes."
