### ISSUE TITLE
can't compile env_boost with mingw 

### ISSUE THREAD

**Issue by mxmxlwlw** [google/leveldb#465]
Here's my command:
gcc -ID:\caffe\leveldb-windows -ID:\caffe\leveldb-windows\include -ID:\caffe\Boost\include\boost-1_63 -DLEVELDB_PLATFORM_WINDOWS -DOS_WIN -D_WIN32 -DWIN32 -DBOOST_ALL_DYN_LINK -LD:\caffe\Boost\lib -c env_boost.cc
And I get following errors:
`In file included from D:\caffe\Boost\include\boost-1_63/boost/interprocess/errors.hpp:41:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/exceptions.hpp:24,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/sync/file_lock.hpp:24,
                 from env_boost.cc:63:
D:\caffe\Boost\include\boost-1_63/boost/interprocess/detail/win32_api.hpp:878:116: warning: declaration of 'void* boost::interprocess::winapi::CreateMutexA(boost::interprocess::winapi::interprocess_security_attributes*, int, const char*)' with C language linkage
 extern "C" __declspec(dllimport) void * __stdcall CreateMutexA(interprocess_security_attributes*, int, const char *);
                                                                                                                    ^
In file included from D:\caffe\Boost\include\boost-1_63/boost/thread/win32/once.hpp:19:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/thread/once.hpp:15,
                 from env_boost.cc:59:
D:\caffe\Boost\include\boost-1_63/boost/thread/win32/thread_primitives.hpp:172:55: warning: conflicts with previous declaration 'void* boost::detail::win32::CreateMutexA(boost::detail::win32::_SECURITY_ATTRIBUTES*, int, const char*)'
                 __declspec(dllimport) void* __stdcall CreateMutexA(_SECURITY_ATTRIBUTES*,int,char const*);
                                                       ^~~~~~~~~~~~
In file included from D:\caffe\Boost\include\boost-1_63/boost/interprocess/errors.hpp:41:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/exceptions.hpp:24,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/sync/file_lock.hpp:24,
                 from env_boost.cc:63:
D:\caffe\Boost\include\boost-1_63/boost/interprocess/detail/win32_api.hpp:883:127: warning: declaration of 'void* boost::interprocess::winapi::CreateSemaphoreA(boost::interprocess::winapi::interprocess_security_attributes*, long int, long int, const char*)' with C language linkage
 extern "C" __declspec(dllimport) void * __stdcall CreateSemaphoreA(interprocess_security_attributes*, long, long, const char *);
                                                                                                                               ^
In file included from D:\caffe\Boost\include\boost-1_63/boost/thread/win32/once.hpp:19:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/thread/once.hpp:15,
                 from env_boost.cc:59:
D:\caffe\Boost\include\boost-1_63/boost/thread/win32/thread_primitives.hpp:173:55: warning: conflicts with previous declaration 'void* boost::detail::win32::CreateSemaphoreA(boost::detail::win32::_SECURITY_ATTRIBUTES*, long int, long int, const char*)'
                 __declspec(dllimport) void* __stdcall CreateSemaphoreA(_SECURITY_ATTRIBUTES*,long,long,char const*);
                                                       ^~~~~~~~~~~~~~~~
In file included from D:\caffe\Boost\include\boost-1_63/boost/interprocess/errors.hpp:41:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/exceptions.hpp:24,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/sync/file_lock.hpp:24,
                 from env_boost.cc:63:
D:\caffe\Boost\include\boost-1_63/boost/interprocess/detail/win32_api.hpp:890:84: warning: declaration of 'void boost::interprocess::winapi::GetSystemInfo(boost::interprocess::winapi::system_info*)' with C language linkage
 extern "C" __declspec(dllimport) void __stdcall GetSystemInfo (struct system_info *);
                                                                                    ^
In file included from D:\caffe\Boost\include\boost-1_63/boost/thread/win32/once.hpp:19:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/thread/once.hpp:15,
                 from env_boost.cc:59:
D:\caffe\Boost\include\boost-1_63/boost/thread/win32/thread_primitives.hpp:182:54: warning: conflicts with previous declaration 'void boost::detail::win32::GetSystemInfo(_SYSTEM_INFO*)'
                 __declspec(dllimport) void __stdcall GetSystemInfo(_SYSTEM_INFO*);
                                                      ^~~~~~~~~~~~~
In file included from D:\caffe\Boost\include\boost-1_63/boost/interprocess/errors.hpp:41:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/exceptions.hpp:24,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/sync/file_lock.hpp:24,
                 from env_boost.cc:63:
D:\caffe\Boost\include\boost-1_63/boost/interprocess/detail/win32_api.hpp:919:88: warning: declaration of 'long long int (* boost::interprocess::winapi::GetProcAddress(void*, const char*))()' with C language linkage
 extern "C" __declspec(dllimport) farproc_t __stdcall GetProcAddress(void *, const char*);
                                                                                        ^
In file included from D:\caffe\Boost\include\boost-1_63/boost/thread/win32/once.hpp:19:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/thread/once.hpp:15,
                 from env_boost.cc:59:
D:\caffe\Boost\include\boost-1_63/boost/thread/win32/thread_primitives.hpp:196:59: warning: conflicts with previous declaration 'int (* boost::detail::win32::GetProcAddress(void*, const char*))()'
                 __declspec(dllimport) farproc_t __stdcall GetProcAddress(void *, const char *);
                                                           ^~~~~~~~~~~~~~
In file included from D:\caffe\Boost\include\boost-1_63/boost/interprocess/errors.hpp:41:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/exceptions.hpp:24,
                 from D:\caffe\Boost\include\boost-1_63/boost/interprocess/sync/file_lock.hpp:24,
                 from env_boost.cc:63:
D:\caffe\Boost\include\boost-1_63/boost/interprocess/detail/win32_api.hpp:920:80: warning: declaration of 'boost::interprocess::winapi::hinstance_struct* boost::interprocess::winapi::GetModuleHandleA(const char*)' with C language linkage
 extern "C" __declspec(dllimport) hmodule __stdcall GetModuleHandleA(const char*);
                                                                                ^
In file included from D:\caffe\Boost\include\boost-1_63/boost/thread/win32/once.hpp:19:0,
                 from D:\caffe\Boost\include\boost-1_63/boost/thread/once.hpp:15,
                 from env_boost.cc:59:
D:\caffe\Boost\include\boost-1_63/boost/thread/win32/thread_primitives.hpp:176:55: warning: conflicts with previous declaration 'void* boost::detail::win32::GetModuleHandleA(const char*)'
                 __declspec(dllimport) void* __stdcall GetModuleHandleA(char const*);`

I know I can build leveldb with vs. But I want to build shared library of leveldb. And mingw can help me out.
And I build boost library with vs, so I guess maybe that's the problem. I don't want to build another boost to address this issue. It's just a library, my vs version of boost should works. And I think maybe I can turn on some kind of define to avoid this issue.
Can you help me out?

**Comment by cmumford** [comment]
If by "vs" you mean Visual Studio keep in mind that we don't yet have an official Windows port, but it can be done with some work on your part.

Regarding creating a shared library please look at 4a7e7f50dcf6 which recently added the `LEVELDB_EXPORT` macro. This should do what you want.
