### ISSUE TITLE
make PLATFORM=IOS fails (macOS 10.12.4, Xcode 8.3.1)

### ISSUE THREAD

**Issue by iutinvg** [google/leveldb#467]
`make PLATFORM=IOS` fails with error message:

```
mkdir /db
mkdir: /db: Permission denied
make: *** [/db] Error 1
```

because `SHARED_OUTDIR` is not set for the platform. There are two solutions:
* build with `make PLATFORM=IOS SHARED_OUTDIR=out-shared`
* fix `Makefile`: add line `SHARED_OUTDIR=out-shared` to `ifeq` block to make it look as below (starting from line 72)
```
ifeq ($(PLATFORM), IOS)
# Note: iOS should probably be using libtool, not ar.
AR=xcrun ar
SIMULATORSDK=$(shell xcrun -sdk iphonesimulator --show-sdk-path)
DEVICESDK=$(shell xcrun -sdk iphoneos --show-sdk-path)
DEVICE_CFLAGS = -isysroot "$(DEVICESDK)" -arch armv6 -arch armv7 -arch armv7s -arch arm64
SIMULATOR_CFLAGS = -isysroot "$(SIMULATORSDK)" -arch i686 -arch x86_64
STATIC_OUTDIR=out-ios-universal
SHARED_OUTDIR=out-shared
else
```

**Comment by pwnall** [comment]
We're using CMake now.

I don't know the best way to cross-compile to iOS from CMake -- if this still interests you, could you please give it a try, and file a new bug if things still don't work?

I'm fairly optimistic because cross-compiling to Android only required setting a few CMake flags.
