### ISSUE TITLE
start leveldb error: ssdb.cpp(109) open main_db failed

### ISSUE THREAD

**Issue by skyearthsong** [google/leveldb#468]
because of the linux server crushed, when I reboot the linux server ,and try to start leveldb, I got this error message in log.txt. My leveldb version is 1.6.8.8, if it's impossible to start the server, can I 
 use another way to get the data back?

**Comment by cmumford** [comment]
This leveldb project is only a library (ignoring test applications). You must be using some other project's binaries.
