### ISSUE TITLE
iOS support, bitcode

### ISSUE THREAD

**Issue by iutinvg** [google/leveldb#476]
The library won't be linked for device build in projects created in the latest Xcode because of default `ENABLE_BITCODE` setting (which is `ON`).

The setting can be disabled for the project or it's possible to set more flags in `Makefile`:
```
DEVICE_CFLAGS = -fembed-bitcode -isysroot "$(DEVICESDK)" -arch armv6 -arch armv7 -arch armv7s -arch arm64
```

**Comment by pwnall** [comment]
Please open a new issue if the CMake build still requires work for iOS.
