### ISSUE TITLE
Implement support for ARM64 crc32 instructions

### ISSUE THREAD

**Issue by zorrorffm** [google/leveldb#478]
ARM64 supports crc32 instructions which can use to accelerate crc32 computation.

**Comment by cmumford** [comment]
This is currently implemented in the [crc32c library](https://github.com/google/crc32c) which will be integrated into the 1.21 release (see [announcement](https://groups.google.com/forum/#!topic/leveldb/GTDiWvgizMU)). Will leave open until implemented.

**Comment by cmumford** [comment]
1.21 is released - closing.
