### ISSUE TITLE
about the HandleTable's FindPointer function

### ISSUE THREAD

**Issue by rwen2012** [google/leveldb#482]
hi, 
 I am reading the source code and the FindPointer's while loop confuses me a little.
First, we get the list by the hash value, but why does the loop check the hash value again?
I think that the '(*ptr)->hash == hash' is always TRUE.  NOT right?

  LRUHandle** FindPointer(const Slice& key, uint32_t hash) {
    LRUHandle** ptr = &list_[hash & (length_ - 1)];
    while (*ptr != NULL &&
           ((*ptr)->hash != hash || key != (*ptr)->key())) {
      ptr = &(*ptr)->next_hash;
    }
    return ptr;
  }

**Comment by ghemawat** [comment]
On Mon, Jul 10, 2017 at 7:14 PM, rwen2012 <notifications@github.com> wrote:

> hi,
> I am reading the source code and the FindPointer's while loop confuses me
> a little.
> First, we get the list by the hash value, but why does the loop check the
> hash value again?
> I think that the '(*ptr)->hash == hash' is always TRUE. NOT right?
>
> LRUHandle** FindPointer(const Slice& key, uint32_t hash) {
> LRUHandle** ptr = &list_[hash & (length_ - 1)];
>

The preceding line only uses the bottom bits of the hash to get the list.
So the list can contain many different hash values, all with the same
bottom bits.

**Comment by rwen2012** [comment]
I see,  thank you very much!
