### ISSUE TITLE
How to start leveldb

### ISSUE THREAD

**Issue by gwendolau** [google/leveldb#483]
Hi!

I would like to use leveldb for a node.js project, but I don't find instructions on how to launch or start the database. I would like to find a GUI app to work in my DB, what app could I use to see the DB and work into it?

**Comment by Liuchang0812** [comment]
leveldb is a library, not a service. you should search nodejs binding of leveldb

**Comment by topilski** [comment]
LevelDB working only on local machines, if you want to see content of database you can use [FastoNoSQL](http://fastonosql.com)

**Comment by chidelmun** [comment]
@gwendolau You can take a look at the project [HERE](https://github.com/Level/levelup). Hope its what you are looking for.
