### ISSUE TITLE
64 bit Compilation

### ISSUE THREAD

**Issue by handoyog** [google/leveldb#485]
I try to install into OpenIndiana Hipster 201705, which is a OpenSolaris / Solaris 10 derived OS

I downloaded leveldb-master.zip from Github
Unzip the item

runs :
$ gmake

and finally, copied the resulted gmake objects :
$ cp out-static/lib* out-shared/lib* /usr/local/lib
$ cd include
$ cp -r leveldb /usr/local/include

Somehow, the following "Linux Installation Guide for leveldb" were unable to be executed, due to unavailability of that command :
$ ldconfig

So, after this, I tried to compile imposm3, which uses leveldb as one of its requirements.

But it seems the installed objects were 32 bit, as the errors were :

ld: fatal: file /usr/local/lib/libleveldb.so: wrong ELF class: ELFCLASS32
collect2: error: ld returned 1 exit status

These were the compilation string :

g++  -I. -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_SOLARIS -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -O2 -DNDEBUG db/autocompact_test.cc out-static/db/builder.o out-static/db/c.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dbformat.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/table/block_builder.o out-static/table/block.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table_builder.o out-static/table/table.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env_posix.o out-static/util/env.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/port/port_posix.o out-static/port/port_posix_sse.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/autocompact_test -lpthread -lrt

cc -I. -I./include -fno-builtin-memcmp -D_REENTRANT -DOS_SOLARIS -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -O2 -DNDEBUG -c db/c_test.c -o out-static/db/c_test.o
cc: Warning: Option -fno-builtin-memcmp passed to ld, if ld is invoked, ignored otherwise

So, how do I set up "configure" command, as "configure.ac" or "configure.in" were missing ? So I can compile into 64 bit ?

Thank you,

Handojo

**Comment by adam-azarchs** [comment]
Since this bug was filed, the project has moved to `cmake` to configure the build.  That may or may not improve the situation for building on Solaris, as `cmake` puts less of the burden of maintaining compiler options for different platforms on the project that's trying to build.  If this is still relevant to you, you should probably try building the current master with `cmake`.

**Comment by pwnall** [comment]
@adam-azarchs great point.

Going to close the issue. OpenSolaris is not supported so, while we'd be willing to review patches, we won't be investing into fixing this ourselves.
