### ISSUE TITLE
add support for DeleteAllKeys update operation

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#49]
Original [issue 43](https://code.google.com/p/leveldb/issues/detail?id=43) created by josephwnorton on 2011-10-01T05:55:50.000Z:

It would be handy to have a new update operation that can delete all keys atomically without having to close, to delete, and then to re-open the database.

**Comment by genki** [comment]
@cmumford You mean deleting by iteration on a range is equivalent to Delete(range)?
Or there is something other way to accomplish it?
