### ISSUE TITLE
endlessly created new sst files after opening database

### ISSUE THREAD

**Issue by tomekbiernat** [google/leveldb#498]
I have experienced such issue: in my application, after opening some levelDb database, new .sst files with subsequent numbers in names are being created, a few per second, until they fill whole disk space. Those files have exactly the same content. After restarting the application, on next DB::Open, those files are removed at the beginning, but immediately the process of creation starts.

When I tried to debug that, I noticed that in manifest there is information about 4 tables at level 0, but one of these files is not present in db folder (I don't know why). Then, during opening, function DBImpl::MaybeScheduleCompaction() is invoked, and it schedules compaction because there are 4 files at level 0. Compaction logs error about missing file, and at the end it invokes MaybeScheduleCompaction(), which still has 4 files at level 0, so it schedules next compaction, and it falls in an endless loop...

Had anybody encountered such behaviour? I can provide broken database if needed.

**Comment by cmumford** [comment]
With 0b9a89f40ef back in 2013 leveldb switched from *.sst to the *.ldb extension. Can you verify this is still an issue with the latest (1.20) release?

**Comment by tomekbiernat** [comment]
Ehh the problem is that I was using Windows branch... When I switched to master and finally managed to build leveldb on Windows, there was no such problem, so the bug is invalid. Thanks for hint!
