### ISSUE TITLE
Potential issue in port_android.h that won't compile

### ISSUE THREAD

**Issue by royguo** [google/leveldb#501]
I am trying to build leveldb on android(using the android branch).

These lines won't compile and warns me `; is expected after definition`.

```
#ifndef ARMV6_OR_7
// On ARM chipsets < V6, 0xffff0fa0 is the hard coded address of a
// memory barrier function provided by the kernel.

typedef void (*LinuxKernelMemoryBarrierFunc)(void);
LinuxKernelMemoryBarrierFunc pLinuxKernelMemoryBarrier WEAK_ATTRIBUTE =
    (LinuxKernelMemoryBarrierFunc) 0xffff0fa0;
#endif
```

so I changed the `WEAK_ATTRIBUET` to `__attribute__((weak))` and it works fine.

I haven't read all of the code yet, Is this a bug here? If not please close this issue.

**Comment by pwnall** [comment]
Master cross-builds to Android. We now have a `port_stdcxx` that should build with any C++11 compiler. Thank you for reporting the issue, and sorry it took us so long to respond!
