### ISSUE TITLE
Big Data read speed.

### ISSUE THREAD

**Issue by DENjjA** [google/leveldb#507]
Hi,
When creating a 2 GB database (922 files), the reading speed of 10K random values is ~ 0.18 s.
With a base of 106 GB (44000 files), the speed drops to ~ 6 minutes.
Why, and how to be in this case? Is it possible to speed up the reading with large amounts of data?
Ubuntu 14.04
python levelDB 0.194
Thanks!

**Comment by dwing4g** [comment]
Try increase max_open_files and max_file_size in Options for big data

**Comment by pwnall** [comment]
Closing because there's nothing actionable for us to do there.

@cmumford I think we should direct folks to the [leveldb Stackoverflow tag](https://stackoverflow.com/questions/tagged/leveldb) for questions. The community there appears to have more resources than we do for answering questions.
