### ISSUE TITLE
I found no use of prev_log_number_

### ISSUE THREAD

**Issue by cooljiansir** [google/leveldb#509]
I think there's no use of `prev_log_number_` since the following commit deleted `edit.SetPrevLogNumber(versions_->LogNumber());`
https://github.com/google/leveldb/commit/ccf0fcd5c2946f9228068d657a56d91af9671575#commitcomment-24211423

**Comment by cmumford** [comment]
Both VersionEdit::prev_log_number_ and VersionSet::prev_log_number_ are set and read in several places from what I can see.

**Comment by pwnall** [comment]
What @cmumford  said :smile: 

You can use the cross-reference functionality in Chromium's codesearch:

* VersionEdit: https://cs.chromium.org/chromium/src/third_party/leveldatabase/src/db/version_edit.h?q=prev_log_number&l=91
* VersionSet: https://cs.chromium.org/chromium/src/third_party/leveldatabase/src/db/version_set.h?q=prev_log_number&l=306
