### ISSUE TITLE
question is possible to use transaction

### ISSUE THREAD

**Issue by publicocean0** [google/leveldb#511]
hi is is possible to use transaction and two-phase transaction ?

**Comment by pwnall** [comment]
@publicocean0 WriteBatch gives you the ability to commit multiple operations atomically. You're on your own for isolation.

Chrome implements IndexedDB transactions as a wrapper around WriteBatch. You might find the code around this file helpful: https://cs.chromium.org/chromium/src/content/browser/indexed_db/leveldb/leveldb_transaction.h
