### ISSUE TITLE
Docker image for leveldb

### ISSUE THREAD

**Issue by vaibhavsood** [google/leveldb#513]
Hi, 

Want to check if there is a docker image/Dockerfile for leveldb which is officially supported? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official leveldb image to dockerhub?  https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by pwnall** [comment]
At the moment, we have no plans for supporting a docker image. Sorry!

**Comment by aidan-plenert-macdonald** [comment]
Have plans changed in the past year?

**Comment by pwnall** [comment]
Nope, sorry.

**Comment by 0zAND1z** [comment]
Are we revisiting this decision in 2020?
Or is there an official docker image I am not aware of?

Awaiting response from maintainers :) 

PS: Great job with LevelDB, keep it up!! 🙌

**Comment by cmumford** [comment]
Sorry @0zAND1z. We've decided to keep the project clear from any and all forms of packaging, install, and alternative build systems. Feel free to check back in 2021 if you want :-)

**Comment by Gulats** [comment]
any updates on it..?

**Comment by beeyev** [comment]
Checking in 2022

**Comment by yangmingli08** [comment]
Checking in 2023

**Comment by SohelAhmedJoni** [comment]
Checking in 2024
