### ISSUE TITLE
Keep atomic for multi-batch commit

### ISSUE THREAD

**Issue by rjl493456442** [google/leveldb#514]
If i use two databases(each one has it own file directory), and want to keep atomic for flushing two batches(each batch related with a database), how can i achieve that?  It there any suggestions?

Thanks.

**Comment by pwnall** [comment]
LevelDB doesn't provide any atomicity across database boundaries, so you have to regard them as different systems. If you're stuck with this design and can't move the data in the same database, you'll have to implement some form of two-phase commit.
