### ISSUE TITLE
'string' file not found

### ISSUE THREAD

**Issue by ritesh-chandora** [google/leveldb#515]
![screen shot 2017-10-10 at 20 44 59](https://user-images.githubusercontent.com/1570905/31394564-3c93eea8-adfc-11e7-965d-c3c6962dd082.png)

Getting this Error while compiling IOS project. Looks like some CPP code is there in project which is not being complied properly.

/Users/cvi/Desktop/Ritesh/quintessence-learning/iOSApp/Pods/leveldb-library/include/leveldb/slice.h:21:10: error: 'string' file not found
#include <string>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'

**Comment by pwnall** [comment]
You're probably trying to use the C++ API in Objective C (.m). Either use Objective C++ (.mm) or use the C API.

**Comment by weibel** [comment]
We have this exact problem while trying to integrate the latest Firebase. It's a mixed ObjC/Swift project. 

The error emerges while Xcode is compiling the Swift code.

We have been digging quite a lot so any pointers to how to make the project compile would be appreciated.

Excerpt of our Podfile.lock

```
 - leveldb-library (1.20)
 - Firebase/Core (4.5.0):
    - FirebaseAnalytics (= 4.0.4)
    - FirebaseCore (= 4.0.10)
  - Firebase/Database (4.5.0):
    - Firebase/Core
    - FirebaseDatabase (= 4.1.0)
  - Firebase/RemoteConfig (4.5.0):
    - Firebase/Core
    - FirebaseRemoteConfig (= 2.1.0)
  - FirebaseABTesting (1.0.0):
    - FirebaseCore (~> 4.0)
    - Protobuf (~> 3.1)
  - FirebaseAnalytics (4.0.4):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.10):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - nanopb (~> 0.3)
  - FirebaseDatabase (4.1.0):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - leveldb-library (~> 1.18)
  - FirebaseInstanceID (2.0.5)
  - FirebaseRemoteConfig (2.1.0):
    - FirebaseABTesting (~> 1.0)
    - FirebaseAnalytics (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
    - Protobuf (~> 3.1)
```

**Comment by ritesh-chandora** [comment]
I did most stupid thing and it works.. Removed the  "- leveldb-library (~> 1.18)" manually and updated the pod. It works :+1:

**Comment by jonesthai** [comment]
<img width="1280" alt="screen shot 2017-11-07 at 12 58 59 pm" src="https://user-images.githubusercontent.com/10720704/32509503-7b96306e-c3bb-11e7-8abf-7a55aa5ec903.png">
<img width="994" alt="screen shot 2017-11-07 at 12 15 55 pm" src="https://user-images.githubusercontent.com/10720704/32509509-7ef76dae-c3bb-11e7-86d0-eea2295ea71f.png">
Have same issue as weibel. Was working and building fine in Xcode 8 and previous Firebase but had this issue when updated to Xcode 9 and the most current Firebase. Deintegrated pods, went back to Xcode 8, and couldn't find a solution that pwnall proposed (Should this be the solution for Firebase?).

**Comment by weibel** [comment]
For our Firebase install we ended up solved it by not using Cocoapods but adding the necessary libraries manually to the project.

**Comment by jonesthai** [comment]
Thank you weibel! I manually added the frameworks (http://www.mokacoding.com/blog/setting-up-firebase-without-cocoapods/) and all is installed, imports, and builds!

**Comment by niazoff** [comment]
Hi guys 👋. Getting this error running the new Xcode 10.1 that was released today. It particularly happens when trying to build my test target. On my main app target things are fine. Just have the basic Firebase dependency in my pod. Any help appreciated.

**Comment by InfiniteEdge** [comment]
@niazoff Getting the same exact error as you. Just started working on it today. Any resolution?

**Comment by InfiniteEdge** [comment]
I was able to fix that specific issue but now I've run into another unrelated issue. Not sure if this will help but under Target > "Appname" > Build Settings there's a "Search Paths" section. I had manually created header search paths under "user header search paths" and once I deleted them I was able to get past this specific error.

**Comment by 7er0** [comment]
Same issue here. Where is the problem? With the swift bridging header? Firebase version?

https://stackoverflow.com/questions/54186492/string-file-not-found-compiling-swift-file-in-objective-c-project

I have posted that problem on stackoverflow twice, no one seems to know the issue.
Have also contacted Firebase support, they couldn't locate the issue either.

**Comment by peteralen** [comment]
Fixed my issue:
https://github.com/firebase/firebase-ios-sdk/issues/2260#issuecomment-457498779

**Comment by kbonner1977** [comment]
I'm having the same issue. Did you just delete the leveldb-library folder from the pod file
?
