### ISSUE TITLE
fail to make 

### ISSUE THREAD

**Issue by JianchengZh** [google/leveldb#516]
util/crc32c.cc:246 : error: expected initializer before ‘const’
util/crc32c.cc:257 : error: expected constructor, destructor, or type conversion before ‘inline’
util/crc32c.cc : In function ‘uint32_t leveldb::crc32c::Extend(uint32_t, const char*, size_t)’:
util/crc32c.cc:284 : error: ‘kCRC32Xor’ was not declared in this scope
util/crc32c.cc:324 : error: ‘RoundUp’ was not declared in this scope

**Comment by pwnall** [comment]
Sorry! I've introduced `constexpr`, which requires C++11, in bcd9a8ea4a8aad23a3e101a23c61615bab2a093f, and Travis didn't catch it.

We're currently discussing about whether LevelDB will require C++11 support. If that's the case, 1.20 will be the last release that builds without C++11, and I'll fix the Makefile. If that's not the case, I'll remove `constexpr` from the crc32c code.

**Comment by pwnall** [comment]
The upcoming release will require C++11. I will update the build files and README soon. Sorry!
