### ISSUE TITLE
unistd.h not available on Windows

### ISSUE THREAD

**Issue by sipsorcery** [google/leveldb#521]
When compiling with msvc on Windows unistd.h is not available in leveldb/c.cc. 

Excluding the header and also adding a definition for ssize_t and undefining _snprintf in port_win.h allows compilation to succeed.

db/c.cc
```c
#include <stdlib.h>
#ifndef WIN32
#include <unistd.h>
#endif
#include "leveldb/cache.h"
```

port/port_win.h
```c
#ifdef _MSC_VER
//#define snprintf _snprintf
#define close _close
#define fread_unlocked _fread_nolock
#include <stdint.h>
#ifdef _WIN64
typedef int64_t ssize_t;
#else
typedef int32_t ssize_t;
#endif
#endif

#include <string>
```

**Comment by cmumford** [comment]
Thanks for the issue. At present Windows is not an officially supported platform. We are currently working on adding this as it is frequently asked for.
