### ISSUE TITLE
Xcode 9.1 - Dead store errors

### ISSUE THREAD

**Issue by saldous** [google/leveldb#530]
When analyzing my project in Xcode 9.1 using leveldb v1.20, I'm seeing the below issues:

![image](https://user-images.githubusercontent.com/3334306/32994163-81f715c0-cd31-11e7-8254-8d1e6387c7ae.png)

**Comment by ghemawat** [comment]
I suspect something is wrong with the analysis.  E.g., the following code fragment is inconsistent with the offset_in_block complaint:

  const size_t offset_in_block = initial_offset_ % kBlockSize;
  uint64_t block_start_location = initial_offset_ - offset_in_block;

  // Don't search a block if we'd be in the trailer
  if (offset_in_block > kBlockSize - 6) {
    block_start_location += kBlockSize;
  }
