### ISSUE TITLE
fillsync is extremely slow ( 31476.103 micros/op;    0.0 MB/s (1000 ops)) on Ubuntu 16.04

### ISSUE THREAD

**Issue by wangli1426** [google/leveldb#533]
I run the benchmark on my desktop with Ubuntu 16.04. I found that fillsync is extremely slow. 

```fillsync     :   31476.103 micros/op;    0.0 MB/s (1000 ops)```

This is normal? I did not read the source code, but I believe a `sync` or similar synchronous function is called at the end of each operation. I wrote some test code on my computer, and found `sync` always takes around 30 ms to complete. By the way, is it better to open the file with O_DIRECT flag so that the expensive `sync` can be avoided?

Thanks.

**Comment by pwnall** [comment]
You can start following the code trail from here: https://cs.chromium.org/chromium/src/third_party/leveldatabase/src/db/db_bench.cc?type=cs&q=file:third_party/leveldatabase+fillsync&sq=package:chromium&l=477

`sync` is needed to get durability guarantees (the D in ACID). In database systems that are not under heavy load, `sync` is the biggest contributor to transaction commit latency. Unfortunately, it can't be avoided, if you want durability guarantees.

As a LevelDB user, you can avoid the `sync` call (at the expense of losing durability guarantees) via the sync flag in WriteOptions.
