### ISSUE TITLE
Why not use binary search when traverse data block

### ISSUE THREAD

**Issue by rjl493456442** [google/leveldb#534]
When search in data block, leveldb traverse the data and improve the search efficiency by restart point. 

Why not use binary search to improve the efficiency simply? May i ask the idea behind it?

**Comment by ghemawat** [comment]
Between restart points, keys are delta-encoded (prefix shared with the
previous key can be dropped).  Therefore, between restart points, it is not
possible to do a binary search (which requires random access).
