### ISSUE TITLE
Version 1.20 broke ABI without bumping SONAME

### ISSUE THREAD

**Issue by fsateler** [google/leveldb#536]
Version 1.20 has added `max_file_size` field to `Option` struct. This breaks the ABI because:

1. Options is no longer the same size. Any functions/methods that take or return Option objects are now suspect, as caller and calle will be expecting objects of different sizes.
2. It was added in the middle, thus breaking offsets for all users of subsequent fields.

Please bump the SONAME, as now all callers need to be recompiled.

Forwarded from downstream bug report: https://bugs.debian.org/877773

**Comment by sbraz** [comment]
@cmumford Hi, can you look into this?

**Comment by sbraz** [comment]
@pwnall This is rather inconvenient for downstream, is there any chance that you or some other maintainer could look into this?

**Comment by sbraz** [comment]
@cmumford sorry for the spam but since you replied to the other issue, is there any chance that you could look into this? Unlike the memenv issue, this affects more than bitcoin and Gentoo users.

**Comment by pwnall** [comment]
@sbraz Thank you for bringing this to our attention. We got your pings.

If you have concrete data that you think would help prioritize this, please share it. Otherwise, please assume we're doing our best to tackle everything we see with the limited resources we have.

**Comment by sbraz** [comment]
@pwnall I apologise, as you can see I commented 4 months ago and didn't see any response so I was a bit worried that the maintainers hadn't seen the bug. I thought the Debian bug report was enough evidence that this can cause breakage.

If we know for sure that SOVERSION is going to be changed, we can add 1.20 to Gentoo with a patch to match your change and we know that we will never risk a mismatch.

If that helps, I can probably make a pull request that sets SOVERSION to 2 for the current cmake-based build system (which doesn't seem to add a SOVERSION to the shared library at all). Or should it be 3? I haven't looked at the changes between 1.20 and HEAD so I don't know if there was another API change.

**Comment by shirishag75** [comment]
I am guessing this would be resolved only if somebody makes a new release or somebody does a git package with @sbraz 's recent commits (i.e. after it was shown downstream in debian's bug report.)

**Comment by cmumford** [comment]
Version 1.21 is released.
