### ISSUE TITLE
Can anyone tell me why memory_useage_ is cast to void* in arena.cc?

### ISSUE THREAD

**Issue by fengyindiehun** [google/leveldb#537]
The type of memory_usage_ is size_t, why it is reinterpre_cast to void* in  arena.cc?

**Comment by ghemawat** [comment]
memory_usage_ relies on AtomicPointer class to allow a reader to access it without holding a lock.  AtomicPointer is a portability layer that only supports void*.

If/when we require C++11, we can replace AtomicPointer with std::atomic<> and then clean up the memory_usage_ type to be std::atomic<size_t>.
