### ISSUE TITLE
issue with opening db

### ISSUE THREAD

**Issue by pokal4u** [google/leveldb#548]
Hi,
Using the below code I am getting error:

InitializationError: Must provide db
    at new LevelUP (/node_modules/levelup/lib/levelup.js:49:13)

Mycode:

var level = require('levelup');
var db = level('./myDb');
db.put('name', 'levelup', function (err) {
  if (err) return console.log('Ooops!', err) // some kind of I/O error
  // 3) Fetch by key
  db.get('name', function (err, value) {
    if (err) return console.log('Ooops!', err) // likely the key was not found
    // Ta da!
    console.log('name=' + value)
  })
})

Thanks
Srinivas

**Comment by ralphtheninja** [comment]
You are reporting this on the wrong repository. This is the google c++ lib for leveldb and has nothing to do with javascript.

**Comment by ralphtheninja** [comment]
I might as well answer you here. Use `level` instead of `levelup`:

```js
var level = require('level')
var db = level('./myDb')
```

**Comment by ralphtheninja** [comment]
@cmumford You could add me as collab if you like and I can take care of issues like this, close etc. I'll make sure to not touch anything else.
