### ISSUE TITLE
Background compaction cross-dependency between DBs?

### ISSUE THREAD

**Issue by iljaiwas** [google/leveldb#549]
I'm using two different leveldb databases within a single process on macOS (previously called Mac OS X).

In my scenario, Put requests to database A are stalling in bg_cv_.Wait() forever, presumably because BackgroundCompaction() is run for database B (~12 GB on disk).

Is this cross-dependency between open databases LevelDB's indented design, am I reading the stack trace wrong, or is there something wrong with the macOS port?

Any ideas on how to work around this issue?

<img width="1242" alt="screen shot 2018-01-29 at 14 42 17" src="https://user-images.githubusercontent.com/2284114/35513269-c258c0ba-0502-11e8-838b-3484e7e37848.png">

<img width="1242" alt="screen shot 2018-01-29 at 14 42 38" src="https://user-images.githubusercontent.com/2284114/35513426-42fa9f18-0503-11e8-8906-170c76363db6.png">

**Comment by iljaiwas** [comment]
Okay, seems I might have found a solution: You need to pass in a seperate Env object for each leveldb object during Open() in the options param.
 
Otherwise the shared DefaultEnv object is used the lock is shared between databases.

**Comment by cmumford** [comment]
No, you can (and probably should) use a single Env for as many open databases as you want. I think your problem lies elsewhere, but don't see any underlying cause in the two screen captures provided.

**Comment by iljaiwas** [comment]
Thanks for your response. I think you are right, my problem seems to be related to using GCD queues to offload Put()-requests to a background queue. Once I performed the Put() on the same thread as the database was created one, the problem went away.
