### ISSUE TITLE
memory barrier on s390

### ISSUE THREAD

**Issue by WandyLau** [google/leveldb#550]
when I try to compile on s390, error says: #error Please implement AtomicPointer for this platform.

I am not sure how to enable this. Is there any clue on this?

**Comment by pwnall** [comment]
Here is how you find the error in the code:
https://github.com/google/leveldb/search?q=Please+implement+AtomicPointer+for+this+platform

If your compiler is compatible with C++11, <atomic> should provide an implementation that AtomicPointer would pick up.

**Comment by WandyLau** [comment]
@pwnall emm， actually I have read the source code you in your link. Just have no idea how to implement it.  I will have an deeper look at this. 

BTW, can I just replace the leveldb with other one? If I can, could you please give some advice on this? thanks

**Comment by pwnall** [comment]
I don't know how the S390 works, sorry. You either need a compiler with C++11 support, or a very good knowledge of the hardware.

Linux seems to have some code for atomic ops on Z390 that you can use as inspiration:
https://github.com/torvalds/linux/blob/master/arch/s390/include/asm/atomic.h
https://github.com/torvalds/linux/blob/master/arch/s390/include/asm/atomic_ops.h

As for LevelDB alternatives, the benchmarks for alternative databases show how to get operations similar to LevelDB with 2 alternatives:
https://github.com/google/leveldb/tree/master/doc/bench

Compare the code against:
https://github.com/google/leveldb/blob/master/db/db_bench.cc

**Comment by WandyLau** [comment]
I have enable memory barrier. I will send the patch.

**Comment by WandyLau** [comment]
@pwnall I have pushed the patch, please help review it. Thanks.

**Comment by WandyLau** [comment]
How can I push my patch to this repo? I have no access to this origin. So I wonder how can I push my patch?
