### ISSUE TITLE
db_bench does not support --help

### ISSUE THREAD

**Issue by Pascal666** [google/leveldb#564]
db_bench has lots of command line options, but it does not have an option to list them all.

**Comment by pwnall** [comment]
That's a reasonable request.

However, the target audience for `db_bench` is developers (who should be able to read the top of the source file), so I don't think that fixing this is worth the recurring extra work of keeping help strings in sync.

Sorry this isn't the answer you wanted, but I hope you understand the reasoning behind it.

**Comment by Pascal666** [comment]
Normally help strings are automatically kept in sync using something like gflags.

**Comment by pwnall** [comment]
Completely agreed!

This repository is currently set up to be built & tested without any dependency. Ideally, we'd use submodules to import repositories like google/googletest and google/benchmark, and remove our stubs at util/tes{tharness,util}.{h,cc}. gflags/gflags would follow soon after that.

Sadly, figuring out the submodule story requires some work in the internal repository that we don't have bandwidth for -- at the moment, we're much more excited about adding a Windows port and taking advantage of C++11 to simplify the codebase. (no promises though)

**Comment by Pascal666** [comment]
Should this issue be left open so it doesn't get forgotten about at that time?

**Comment by pwnall** [comment]
I think the issue should remain closed because we don't have any concrete plans / timeline for fixing it, and we can't accept a community contribution, since the blocker is in the internal repository.

I realize this is inconsistent with the slew of open issues, but we'll tackle the large backlog one bit at a time.

/cc @cmumford because I'm guessing you'd like a second opinion.

**Comment by Pascal666** [comment]
LOL.  Thank you, but I'm fine with your opinion.
