### ISSUE TITLE
the default size of the log file in  leveldb/doc/impl.md is contradiction

### ISSUE THREAD

**Issue by wjnodejs** [google/leveldb#566]
In "Log files" section , say "When the log file reaches a pre-determined size (approximately 4MB by default), it is converted to a sorted table (see below) and a new log file is created for future updates."
But In "Level 0" section ,say "When the log file grows above a certain size (1MB by default): Create a brand new memtable and log file and direct future updates here In the background"
i want to kown what's the size about the default size of the log file.

**Comment by cmumford** [comment]
The default size started out at 1MB, but changed (in f779e7a5d89f853fc5224f9eb8103ca2b8f2f555) to be 4MB, but the documentation was not updated. I'll take care of that.
