### ISSUE TITLE
build fail in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by esanchma** [google/leveldb#569]
Building in Ubuntu 16.04 LTS with `build-essential` installed throws the following error: 

```mkdir out-shared
mkdir out-shared/db
mkdir out-shared/port
mkdir out-shared/table
mkdir out-shared/util
mkdir -p out-shared/helpers/memenv
g++ -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX=1 -DLEVELDB_ATOMIC_PRESENT -DHAVE_CRC32C=0 -DHAVE_SNAPPY=0 -O2 -DNDEBUG -DLEVELDB_SHARED_LIBRARY -DLEVELDB_COMPILE_LIBRARY -fPIC -fvisibility=hidden -c db/builder.cc -o out-shared/db/builder.o
In file included from ./port/port.h:14:0,
                 from ./db/filename.h:14,
                 from db/builder.cc:7:
./port/port_posix.h:50:36: error: ‘LEVELDB_IS_BIG_ENDIAN’ was not declared in this scope
 static const bool kLittleEndian = !LEVELDB_IS_BIG_ENDIAN;
                                    ^
Makefile:425: recipe for target 'out-shared/db/builder.o' failed
make: *** [out-shared/db/builder.o] Error 1
```

I have bisected the error to the commit 739c25100e46576cdcdfff2d6f43f9f7008103c7

**Comment by pwnall** [comment]
Sorry for the confusion!

We switched to CMake. Removing the make configuration is in review in our internal repository, and will be published (hopefully soon).

**Comment by pwnall** [comment]
The make configuration has been removed.

Can you please try building with CMake? AFAIK the Linux tests on Travis run in a 16.04 container, so I'm fairly optimistic that you'll be able to build the project, once you have the prerequisites.

Alternatively, you should be able to build the 1.20 release with make.

I'll close this issue. If the suggestions above don't work for you, please comment here and I'll reopen.

**Comment by TonightGo** [comment]
I still have this problem with CMake.

**Comment by pwnall** [comment]
`LEVELDB_IS_BIG_ENDIAN` is defined in the CMake-generated file at `include/port/port_config.h` in your build directory.

Your other problem suggests that you're trying to build shared libraries without setting [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.9/variable/BUILD_SHARED_LIBS.html). If that variable is set, the CMake configuration should do the right thing.
