### ISSUE TITLE
catching exceptions thrown during DB::Put

### ISSUE THREAD

**Issue by RJVB** [google/leveldb#576]
Hi,

I made a stupid error and saw my app get terminated because of an uncatched std::bad_alloc from tcmalloc. So I wrapped the Put() call inside a try/catch:

```
leveldb::Status status;
try{
  status = levelDB->put(leveldb::WriteOptions(), key, value);
}
catch (const std::exception& e) {
  // handle exceptions gracefully
}
if (!status.ok()) {
  // handle normal errors
}
```

and then I realised that the default Status ctor creates an "OK" status object. IOW, `status.ok()` will be true if an exception occurred, and I don't see any way to avoid that, like a `status.invalidate()` method, or simply a dedicated, generic not-OK status object so one can do something like `leveldb::Status status = leveldb::Status::NotOK`.

Maybe LevelDB could catch exceptions internally and return a relevant error status when one occurs?

And FWIW, that try/catch may not always provide the intended protection (another error of mine?)  :-/

**Comment by pwnall** [comment]
Status has a copy assignment operator. Can you not do `status = leveldb::Status::IOError("Out of Memory")`? (granted IOError isn't perfect here, it's probably the closest we've got)

In general, handling exceptions is against the Google style guide, so we wouldn't accept any patches for that. Our CI builds (or at least I intend it to build) with exception support disabled.

**Comment by pwnall** [comment]
I've closed this, as it's an answered question. Please reply here if you still need to ask follow-up questions, as I will see updates to this thread.

**Comment by RJVB** [comment]
> Can you not do `status = leveldb::Status::IOError("Out of Memory")`?

I must admit I stopped at the observation that there is no ctor that takes a parameter (except for the copy ctor), and simply used an extra state variable of my own.

If handling exceptions is against Google guidelines, what about throwing them? AFAIK tcmalloc is also a Google product, and even if the exception isn't thrown directly by any of your code it might not either if exceptions are turned off by default in the gperftool build system?
