### ISSUE TITLE
Assertion `status.ok()' failed.

### ISSUE THREAD

**Issue by madiha95** [google/leveldb#581]
**Hello , 
I was using leveldb in my debian version with no problem , and then suddendly it's not working anymore , when I try to execute a simple code of for example the db connexion i got that message 
Assertion `status.ok()' failed.
what should I verify , can anybody help ?**

**Comment by cmumford** [comment]
I'm assuming the assertion is in your code which probably came from the leveldb documentation: [Opening A Database](https://github.com/google/leveldb/blob/master/doc/index.md#opening-a-database)? If so can you print out status.ToString() to see why it is failing?

**Comment by madiha95** [comment]
Exactly its about opening a Database , and I guess in this two days , I understood the cause, actually , in leveldb you can open the database only one time  ,like  if for example you do execute two times , either for writing and reading , the first execution work , the second one , won't work , and the error that I had is, Assertion `status.ok()' failed. ,I would love to know how can I resolve that , because I will be in need of using my db many times , like for reading and writing in it in from a GUI that I m creating .

**Comment by cmumford** [comment]
My guess is that you have the `error_if_exists` option set to true. Did you print the value returned by `status.ToString()`?

**Comment by madiha95** [comment]
Hi , I updated my code this by adding this line : 
**if (!s.ok()) cerr << s.ToString() << endl**
And actually when clicking on the button of leveldb connexion , it gives me this messag on the command line :  Invalid argument: /tmp/MyDb: exists (error_if_exists is true) , but its not ending any more , like I can do it many time , which I guess its good , if you confirm that for me for sure ! 
Thanks for your answer by the way !
