### ISSUE TITLE
Compile a shared library for luajit on OSX 64

### ISSUE THREAD

**Issue by xiejiangzhi** [google/leveldb#583]
I got a libleveldb.dylib by `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 .. ` on OSX 64. But I unable use it in LuaJIT by FFI. 

it's seems that I should add some link flag according to LuaJIT document http://luajit.org/install.html#embed

I tried add link flag, but I got `ld: -pagezero_size option can only be used when linking a main executable` when `cmake --build .`,

Please help me, thank you.

---------------
Update: sorry for this question, it seems that I understand that luajit's documentation is wrong, it is for embedded luajit.

I'll got a error "Segmentation fault: 11" when I load libleveldb.dylib 1.20 on osx. I just load it.  when I load other lib, I didn't get the error

luajit 2.0.5, leveldb 1.20. I installed them by `brew install xx`

```
ffi = require 'ffi'
ffi.load('leveldb')
-- I'll get "Segmentation fault: 11"
```

```
ffi = require 'ffi'
ffi.load('png')
ffi.load('sqlite3')
-- it's ok if I try to load other shared library
```

**Comment by cmumford** [comment]
I suggest making sure that libleveldb.dylib is in a path that is in LD_LIBRARY_PATH.
