### ISSUE TITLE
Unable to compile on mac os

### ISSUE THREAD

**Issue by amitdesai03** [google/leveldb#584]
Trying to compile level db from source using conan.
Getting below error:

> leveldb/1.20.0@demo/dev: WARN: Forced build from source
leveldb/1.20.0@demo/dev: Building your package in /Users/amdesai/.conan/data/leveldb/1.20.0/demo/dev/build/778dd063b1b9e211644882c4f3516ef82ced5b23
leveldb/1.20.0@demo/dev: Copying sources to build folder
leveldb/1.20.0@demo/dev: Generator compiler_args created conanbuildinfo.args
leveldb/1.20.0@demo/dev: Calling build()
sed: 1: "./build_detect_platform": invalid command code .
leveldb/1.20.0@demo/dev: 
leveldb/1.20.0@demo/dev: ERROR: Package '778dd063b1b9e211644882c4f3516ef82ced5b23' build failed
leveldb/1.20.0@demo/dev: WARN: Build folder /Users/amdesai/.conan/data/leveldb/1.20.0/demo/dev/build/778dd063b1b9e211644882c4f3516ef82ced5b23
ERROR: leveldb/1.20.0@demo/dev: Error in build() method, line 22
	self.run("cd leveldb-1.20 && sed -i 's,0x,1z,' ./build_detect_platform")
	ConanException: Error 256 while executing cd leveldb-1.20 && sed -i 's,0x,1z,' ./build_detect_platform

- Settings: arch=x86_64, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=9.0, os=Macos

**Comment by pwnall** [comment]
Conan packaging is not supported by this project. You may have better luck asking the conan maintainers for help.
