### ISSUE TITLE
use leveldb put funciton, Normal in mac, exception in linux

### ISSUE THREAD

**Issue by whynotAC** [google/leveldb#597]
![error png](https://user-images.githubusercontent.com/11408428/41334321-c831476c-6f17-11e8-81c3-42c3763b6e14.jpg)

just use put function,

leveldb::Slice sliceKey = std::to_string(key);
leveldb::Slice sliceValue = std::to_string(value);
leveldb::Status status = mdb->Put(leveldb::WriteOptions(), sliceKey, sliceValue);

status.ok()  is always true. but leveldb file isn't worked.

**Comment by whynotAC** [comment]
run the same program in my mac is ok, generate all ldb files.
![1528872884316](https://user-images.githubusercontent.com/11408428/41334958-d1561e6a-6f19-11e8-9bab-67875ddf21ac.jpg)

**Comment by whynotAC** [comment]
I think problem in compacting,  env set error?
<img width="688" alt="dx-20180613 2x" src="https://user-images.githubusercontent.com/11408428/41344449-c4788fb0-6f33-11e8-9934-ccbdc7523734.png">

**Comment by ghemawat** [comment]
I think there is a problem with how you are constructing key and value:
> leveldb::Slice sliceKey = std::to_string(key);

std::to_string(key) returns a temporary string.  The leveldb::Slice object just points into that std::string.  At the end of the statement, the string is destroyed and the leveldb::Slice object now points into deleted memory.

See the following comment from slice.h:
// Slice is a simple structure containing a pointer into some external
// storage and a size.  The user of a Slice must ensure that the slice
// is not used after the corresponding external storage has been
// deallocated.

I think you need something like:

std::string strKey = std::to_string(key);
std::string strValue = std::to_string(value);
... Put(options, strKey, strValue);

Also, try running your code using something like address sanitizer.  That will point out problems like this one.

**Comment by whynotAC** [comment]
ok, thks
