### ISSUE TITLE
Not working in snappy compressions

### ISSUE THREAD

**Issue by topilski** [google/leveldb#609]
Hello, i think now master branch not working with snappy compressed data, can you recheck it?

**Comment by topilski** [comment]
Here link why i think so: https://github.com/fastogt/fastonosql/issues/63

**Comment by pwnall** [comment]
You probably built the project without having snappy installed. Snappy is an optional dependency and the build can succeed without it, resulting in a binary that can't compress / decompress data blocks.

**Comment by topilski** [comment]
Hi @pwnall , you using snappy-c or snappy C++ bindings?

**Comment by topilski** [comment]
In Cmake i see you looking for `check_library_exists(snappy snappy_compress "" HAVE_SNAPPY)` but header should be snappy-c.h

**Comment by topilski** [comment]
Here my fix if you are interesting: https://github.com/fastogt/leveldb/commit/dd6e5ade4c5bdec44dfff80b6fc960c15ffdf6ce

**Comment by jl0x61** [comment]
I couldn't find snappy_compress in snappy 1.1.7 or 1.1.8, so I just comment `check_library_exists(snappy snappy_compress "" HAVE_SNAPPY)` and add `SET(HAVE_SNAPPY TRUE)` and that works well.
