### ISSUE TITLE
where libleveldb.so*

### ISSUE THREAD

**Issue by 237014845** [google/leveldb#614]
CXX src/caffe/util/db_leveldb.cpp
In file included from src/caffe/util/db_leveldb.cpp:2:0:
./include/caffe/util/db_leveldb.hpp:7:24: fatal error: leveldb/db.h: No such file or directory
compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/util/db_leveldb.o' failed
make: *** [.build_release/src/caffe/util/db_leveldb.o] Error 1

**Comment by pwnall** [comment]
You seem to be using a different project, which is embedding leveldb.

You'll have better chances of finding help on StackOverflow or at https://github.com/BVLC/caffe
