### ISSUE TITLE
CMake include path

### ISSUE THREAD

**Issue by Athius** [google/leveldb#617]
Hello everyone,

I try to use leveldb with a C++ project build with CMake.

I'd like to know the CMake variable of LevelDB.

I tried using the variable LEVELDB_INCLUDE_DIR, LEVELDB_LIRBARY but nothing work.

Is there any documentation on how to create a new project using CMake please?

**Comment by cmumford** [comment]
@Athius I'd recommend starting with https://cmake.org/cmake-tutorial/
