### ISSUE TITLE
About the InternalGet function.

### ISSUE THREAD

**Issue by geekbutton** [google/leveldb#622]
In table.cc, there is a function InternalGet which is used for searching the given key from the SSTables. It firstly search the index_block by using the Block iterator's seek function, but the Block iterator seek the last reastart point with a key < target , this will be fine for the data  block iterator, but I think it is wrong for the index_block while the index_block keeps the last key of the corresponding data block. By using the seek function, as I think, it will never find the right data_block.
Can anyone explain this for me?

**Comment by 12bucklemy34** [comment]
https://github.com/dotnet/coreclr/pulls

**Comment by 12bucklemy34** [comment]
https://github.com/dotnet/coreclr/pulls

**Comment by chosen0ne** [comment]
Block iterator's Seek will return the first key >= target, as it will firstly seek the last restart point with a key < target, and then search for the first key >= target within the restart block.
