### ISSUE TITLE
fdatasync() is not detected on Ubuntu Linux 18.04

### ISSUE THREAD

**Issue by chenshuo** [google/leveldb#629]
`fdatasync()` is available from `<unistd.h>` on Linux, but CMake doesn't detect it automatically.

Reason: Leveldb sets

```cmake
set(CMAKE_C_STANDARD 11) 
set(CMAKE_C_STANDARD_REQUIRED OFF)
set(CMAKE_C_EXTENSIONS OFF)
```

in its `CMakeLists.txt`, so `check_symbol_exists()` tries compiling using `cc -std=c11`, and hides `fdatasync()` in `<unistd.h>`.

**Comment by pwnall** [comment]
I was able to reproduce on my Fedora workstation. In my testing, `fdatasync` is found using `check_cxx_symbol_exists()`, so I plan to switch to that.
