### ISSUE TITLE
Linux gcc 4.4.7 compile failed 

### ISSUE THREAD

**Issue by 363568233** [google/leveldb#635]
The latest version in redhat gcc 4.4.7 compiled failed , because of not supporting C++11
How to compile it success not update gcc version?

**Comment by 363568233** [comment]
C++11 keyword:  noexcept、 &&、nullptr ...

**Comment by 363568233** [comment]
Could you tell me the latest leveldb version not using C++11?  GCC4.4.7 can compile it

**Comment by pwnall** [comment]
Release 1.20 is the last version that does not require C++11.
