### ISSUE TITLE
add LevelDB overload for Get and Put operations to take a std::vector<uint8_t>

### ISSUE THREAD

**Issue by chasephillips** [google/leveldb#636]
We would like to switch Chrome's IndexedDB implementation towards passing/receiving LevelDB data as std::vector<uint8_t>.  This would allow us to avoid bugs where std::string data is treated as strings rather than raw byte data.

The current LevelDB APIs don't support passing/receiving std::vector<uint8_t> data currently.  Please add an API overload to Get and Put operations to support using std::vector<uint8_t>.  Thanks!

**Comment by ghemawat** [comment]
Different people will want different convenience APIs.  E.g., somebody
might want decoding into a non-utf8 format when switching to
vector<uint8_t>.  Another may use the C++ uint8_t type which may be
different from the C uint8_t.  Yet another project may use a contain type
that is not std::vector but something else. I think it is best for leveldb
to stay out of this.  Instead, in your application code, I suggest writing
your wrapping helpers that do the right thing for your project.

Also note that leveldb::DB is a pure interface (no concrete method
implementations, just abstract methods).  I would rather not start blurring
the line by adding some actual code into that class.

**Comment by pwnall** [comment]
@ghemawat We can definitely wrap LevelDB, and already have.

The only tricky part is `DB::Get()`, which takes in a `std::string*`. AFAIK there's no way to get the buffer out of the string, so moving the data into a `std::vector<uint8_t>` requires a full value copy and an extra allocation. It would be nice to have an alternative that works for any format a project might need to use, just like `Slice` does.

The only solution I can think of (that doesn't require allocations or exposing internals) is having a `Get` that takes a function pointer and a `void*` and calls the function with the value as a `Slice`, and with the `void*`. The function is then responsible for synchronously copying the data in the `Slice` into the project's preferred format, using the `void*` to point to an instance of that format.

What do you this of this approach?

**Comment by ghemawat** [comment]
What you suggest is plausible and perhaps would have been the right API for DB::Get when it was first introduced.  However, I am reluctant to widen the DB interface now for the following reasons:

1. We will end up with overlapping methods in the API (the old string based Get and the new one).  Over time such duplication leads to confusion for users.
2. DB is an interface that others may have reimplemented. To avoid breaking those implementations, we will have to make the new method have a default implementation.

My inclination would be to keep using std::string unless there is some compelling evidence of significant performance wins in real-world workloads achievable by extending the API.
