### ISSUE TITLE
how to find_package leveldb in CMakeLists

### ISSUE THREAD

**Issue by kylejan** [google/leveldb#641]
how to find_package leveldb in CMakeLists

**Comment by cmumford** [comment]
leveldb doesn't yet have a pkg-config file. We are in the process of adding one now which will hopefully land shortly. Watch issue #658 for more info.

**Comment by ohhmm** [comment]
Hi @cmumford ,

find_package in CMake has only istorical relation to pkg-config

Thanks,
Serg
