### ISSUE TITLE
Stable release of 1.21

### ISSUE THREAD

**Issue by bashbug** [google/leveldb#642]
Any plans of releasing a stable release?
I want to build leveldb from source with conan, and cmake based build configuration would be beneficial.

**Comment by pwnall** [comment]
We want to roll all our significant changes for packagers (CMake, C++11, Windows) into one release. We'll cut the release when all that is done. Until then, perhaps you can use the master branch?

**Comment by bashbug** [comment]
Thanks for the information and suggestion. I'll could use the master with a specific commit to ensure all developers use the same source for development. But I'll stick to the latest version, since this is more convenient.
