### ISSUE TITLE
Question about `log_format.md`

### ISSUE THREAD

**Issue by chux0519** [google/leveldb#644]
In [doc/log_format.md](https://github.com/google/leveldb/blob/master/doc/log_format.md), it says

```
Example: consider a sequence of user records:

    A: length 1000
    B: length 97270
    C: length 8000

**A** will be stored as a FULL record in the first block.

**B** will be split into three fragments: first fragment occupies the rest of
the first block, second fragment occupies the entirety of the second block, and
the third fragment occupies a prefix of the third block.  This will leave six
bytes free in the third block, which will be left empty as the trailer.

**C** will be stored as a FULL record in the fourth block.
```
It seems the length of example B is wrong.

I assume example A and C  are both in hex, while B is in decimal.

According to the explanation below, (32K * 3 - 6B) should equals to 98298 in bytes, not 97270.

Should we modify the doc ? Maybe like:

```
...
    A: length 0x1000(4KB)
    B: length 0x17FFA(96KB - 6B)
    C: length 0x8000(32KB)
...
```

I'm willing to make a PR for this.

**Comment by ghemawat** [comment]
The documentation as written is correct and all numbers are in decimal.

First record contains
  header for A (7 bytes)
  A (1000 bytes)
  header for B.1 (7 bytes)
  B.1 (31754 bytes)
Note: the preceding all add up to 32768

Second record contains:
  header for B.2 (7 bytes)
  B.2 (32761 bytes)
Again, sum is 32768 bytes

Third record contains:
  header for B.3 (7 bytes)
  B.3 (32755 bytes) -- note this is 97270 - len(B.1) - len(B.2)
Sum is 32762, which leaves 6 bytes unused as the documentation states.

**Comment by chux0519** [comment]
> The documentation as written is correct and all numbers are in decimal.
> 
> First record contains
> header for A (7 bytes)
> A (1000 bytes)
> header for B.1 (7 bytes)
> B.1 (31754 bytes)
> Note: the preceding all add up to 32768
> 
> Second record contains:
> header for B.2 (7 bytes)
> B.2 (32761 bytes)
> Again, sum is 32768 bytes
> 
> Third record contains:
> header for B.3 (7 bytes)
> B.3 (32755 bytes) -- note this is 97270 - len(B.1) - len(B.2)
> Sum is 32762, which leaves 6 bytes unused as the documentation states.

Thank you for your reply, I see.
Misunderstood the document before.
