### ISSUE TITLE
sqlite3_wal_checkpoint_v2

### ISSUE THREAD

**Issue by hackland** [google/leveldb#649]
1.cmake .
2.make 
then happend the errors above,how to do

**Comment by pwnall** [comment]
Sorry, I don't understand the question. In general, you'll have better luck with questions on *using* LevelDB on the mailing list.

**Comment by 52fhy** [comment]
> Sorry, I don't understand the question. In general, you'll have better luck with questions on _using_ LevelDB on the mailing list.

```
/mnt/opt/leveldb/benchmarks/db_bench_sqlite3.cc:107:38: error: ‘sqlite3_wal_checkpoint_v2’ was not declared in this scope
                               nullptr);
```
