### ISSUE TITLE
leveldb can not put/get/del by multiple concurrent threads

### ISSUE THREAD

**Issue by rhettdyao** [google/leveldb#650]
I saw in the Concurrency section of the documentation that leveldb supports concurrent read and write operations. However, in actual applications, when millions of get/put/delete operations are performed on different keys at the same time, the coredump always appears as follows:
![image](https://user-images.githubusercontent.com/39986251/51024926-b8856000-15c5-11e9-97f9-531521655f88.png)

**Comment by pwnall** [comment]
Your stack trace appears to be using something on top of leveldb.

If you can supply a test case written directly against leveldb, which shows the same failure, please comment on this issue, and we'll take a look.
