### ISSUE TITLE
windows logger cause a crash

### ISSUE THREAD

**Issue by DennisXie** [google/leveldb#657]
https://github.com/google/leveldb/blob/master/util/windows_logger.h#L61
the format string  "%04d/%02d/%02d-%02d:%02d:%02d.%06d %s " need a string at last, but given a long long.
Microsoft Visual Studio Community 2017 15.2(26430.6) Release.

**Comment by pwnall** [comment]
@DennisXie yeah, sorry about that!

We'll have a fix out over the next few days. Until then, 
https://github.com/pwnall/leveldb/commit/3cdd7a8915960bd72d83a6b23ba213d082d55200 seems to work for me. Our fix will be based on that.
