### ISSUE TITLE
Why the write performance reduce?

### ISSUE THREAD

**Issue by liukun4515** [google/leveldb#660]
I use the `db_bench` to test the level db on my laptop.

My disk status：
```
dd bs=1M count=20000 if=/dev/zero of=test.dd conv=fdatasync
20000+0 records in
20000+0 records out
20971520000 bytes (21 GB, 20 GiB) copied, 124.703 s, 168 MB/s
```
The result is :

1 thread
```
./db_bench --benchmarks=fillseq --threads=1
LevelDB:    version 1.20
Date:       Wed Mar  6 10:38:28 2019
CPU:        8 * Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
CPUCache:   8192 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
WARNING: Snappy compression is not enabled
------------------------------------------------
fillseq      :       3.867 micros/op;   28.6 MB/s
```
4 threads
```
./db_bench --benchmarks=fillseq --threads=4
LevelDB:    version 1.20
Date:       Wed Mar  6 10:38:36 2019
CPU:        8 * Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
CPUCache:   8192 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
WARNING: Snappy compression is not enabled
------------------------------------------------
fillseq      :      26.079 micros/op;   16.9 MB/s
```

**Comment by philix** [comment]
I think since there is only one writer thread consuming the queue, having more threads for the benchmark only adds synchronization overhead and waits.

**Comment by cmumford** [comment]
@philix is partially correct. Writes are synchronized so there will be additional overhead due to having multiple write threads. However, the test reports the statistics for only the **first thread**. See:

https://github.com/google/leveldb/blob/7b1174519044339f07a023dc445b0d36425bd6db/db/db_bench.cc#L608

This report uses the call clock for calculations and only the bytes/ops for one of the four threads.

Feel free to reopen if you have further questions.

**Comment by youngk1019** [comment]
> @philix is partially correct. Writes are synchronized so there will be additional overhead due to having multiple write threads. However, the test reports the statistics for only the **first thread**. See:
> 
> https://github.com/google/leveldb/blob/7b1174519044339f07a023dc445b0d36425bd6db/db/db_bench.cc#L608
> 
> This report uses the call clock for calculations and only the bytes/ops for one of the four threads.
> 
> Feel free to reopen if you have further questions.

In fact, I have also encountered this problem. For delayed data, the display shows that the data from the first thread is correct, but the amount of data written per second is the total amount of data from all threads, which has already been merged before reporting

https://github.com/google/leveldb/blob/068d5ee1a3ac40dabd00d211d5013af44be55bea/benchmarks/db_bench.cc#L741

I have tested it on different machines. Some will decrease and then increase at the beginning of the second thread, some will maintain about half of the performance level from the second thread, and some will continue to decline as the number of threads increases
