### ISSUE TITLE
maps: [DEBUG] Open file '/proc/25929/maps' failed: Too many open files [DEBUG] Read self maps instead! [DEBUG] Open file '/proc/26070/maps' failed: Too many open files

### ISSUE THREAD

**Issue by baiguangliang123** [google/leveldb#663]
/data/data/xxxxx/files/leveldb/lm/001893.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 840 -> /data/data/xxxxx/files/leveldb/lm/001896.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 841 -> /data/data/xxxxx/files/leveldb/lm/001902.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 842 -> /data/data/xxxxx/files/leveldb/lm/001905.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 843 -> /data/data/xxxxx/files/leveldb/lm/001908.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 844 -> /data/data/xxxxx/files/leveldb/lm/001911.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 845 -> /data/data/xxxxx/files/leveldb/lm/001914.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 846 -> /data/data/xxxxx/files/leveldb/lm/001917.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 847 -> /data/data/xxxxx/files/leveldb/lm/001920.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 848 -> /data/data/xxxxx/files/leveldb/lm/001923.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 849 -> /data/data/xxxxx/files/leveldb/lm/001926.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 850 -> /data/data/xxxxx/files/leveldb/lm/001929.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 851 -> /data/data/xxxxx/files/leveldb/lm/001934.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 852 -> /data/data/xxxxx/files/leveldb/lm/001937.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 853 -> /data/data/xxxxx/files/leveldb/lm/001940.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 854 -> /data/data/xxxxx/files/leveldb/lm/001943.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 855 -> /data/data/xxxxx/files/leveldb/lm/001946.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 856 -> /data/data/xxxxx/files/leveldb/lm/001949.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 857 -> /data/data/xxxxx/files/leveldb/lm/001952.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 858 -> /data/data/xxxxx/files/leveldb/lm/001966.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 859 -> /data/data/xxxxx/files/leveldb/lm/001961.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 860 -> /data/data/xxxxx/files/leveldb/lm/001964.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 861 -> /data/data/xxxxx/files/leveldb/lm/001968.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 862 -> /data/data/xxxxx/files/leveldb/lm/001971.sst
03-08 16:43:57.516 25638 25638 E DEBUG   : 863 -> /data/data/xxxxx/files/leveldb/lm/001974.sst
......more logs.....

leveldb produced thousands of sst files，opened fd more than the limit of device . Did any body have a solution for the problem？

os：Android os platform

**Comment by cmumford** [comment]
Hi @baiguangliang123: leveldb switched from *.sst to *.ldb file extensions in 2013 first released in 1.14. leveldb also added a change in 646c3588de84ac53 to limit the number of file descriptors used. Upgrading should fix your problem.

**Comment by baiguangliang123** [comment]
@cmumford thank you! I'll have a try.

**Comment by cmumford** [comment]
I'm closing this issue, but please reopen this if still encountering this issue after upgrading. thx.

**Comment by baiguangliang123** [comment]
@cmumford hi,the latest version does not solve my problem.I'm confused, how did leveldb produce thousands of sst files? Reading data from sst while the system storing data on device could create so many fds?
