### ISSUE TITLE
Question: Does LevelDB have an exchanging dataset format?

### ISSUE THREAD

**Issue by dai-shuo** [google/leveldb#667]
Can I share data with others by zipping and sending LevelDB disk files? 
If the receiver has a golang version of LevelDB, can he open my files generated by C++ library?

**Comment by cmumford** [comment]
leveldb does not have an exchanging dataset format. I'm unfamiliar with the golang version and don't know if it is a simple wrapper around the C++ library, or if it is a full implementation in Go. If you use the default comparator and the golang version supports snappy compression, then you should be OK.
