### ISSUE TITLE
PVS-Studio report

### ISSUE THREAD

**Issue by pavel-pimenov** [google/leveldb#668]
PVS-Studio Version:	7.01.31225.1583
Total Warnings (GA):	36
Total Warnings (OP):	15
Total Warnings (64):	12
http://www.fly-server.ru/pvs-studio/leveldb/

**Comment by cmumford** [comment]
Thx for the report @pavel-pimenov

**Comment by cmumford** [comment]
There is one more fix coming for an array bounds. This will fix most of the high level issues flagged. Most of these issues are either in tests, utility programs, or cases where possible overflow would have been identified by now, and a large scale fix would be more likely to cause new issues than to fix any. Thx again for the report.
