### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by omulriain** [google/leveldb#671]
I admit I am somewhat newbie at this. I was trying build with CMake and I was able to build a sln file and also to build with VS. The dilemma is that I have no idea how to go from a built C++ project to using it in my python project. The CMake documentation does not shed light on how to do this and neither does the application I need this for quickUMLS. It would be nice if someone could describe the steps to build this and include it in a Windows python project like quickUMLS. Thank You for reading this request.

**Comment by cmumford** [comment]
leveldb is a C/C++ library and does not come with a Python wrapper. There are other projects that do this. If you search the web for "python wrapper leveldb" you should see several different projects. I've never used them so can't recommend one in particular. Good luck.
