### ISSUE TITLE
Written errors in code comments in comparator.h

### ISSUE THREAD

**Issue by JacobleeDJI** [google/leveldb#672]
// The name of the comparator.  Used to check for comparator
  **// mismatches (i.e., a DB created with one comparator is
  // accessed using a different comparator.**
  //
  // The client of this package should switch to a new name whenever
  // the comparator implementation changes in a way that will cause
  // the relative ordering of any two keys to change.
  //
  // Names starting with "leveldb." are reserved and should not be used
  // by any clients of this package.
  virtual const char* Name() const = 0;

i think it missing Right bracket，should be like this:
// The name of the comparator.  Used to check for comparator
  **// mismatches (i.e., a DB created with one comparator is
  // accessed using a different comparator.)**
  //
  // The client of this package should switch to a new name whenever
  // the comparator implementation changes in a way that will cause
  // the relative ordering of any two keys to change.
  //
  // Names starting with "leveldb." are reserved and should not be used
  // by any clients of this package.
  virtual const char* Name() const = 0;

**Comment by samuelbisson660** [comment]
very Smart n Wizzes!  Good Job !! annnnnd!! finally what i try to say is that : « I'm Impress!!

**Comment by cmumford** [comment]
@JacobleeDJI Am I understanding correctly that the following is what you are reporting as incorrect?

> // ... (i.e., a DB created with one comparator is
> // accessed using a different comparator

If so then that is supposed to be an example of a comparator mismatch. I think it is well worded, but technically should use e.g. (for example) instead of i.e. (in other words).
