### ISSUE TITLE
out-static/db/c_test.o:c_test.c:(.text.startup+0x3c): undefined reference to `geteuid'

### ISSUE THREAD

**Issue by D3m0nKingx** [google/leveldb#675]
Cross-compiling for Windows platform on Ubuntu 16.04 with the command:
`make clean;TARGET_OS=NATIVE_WINDOWS make CC=x86_64-w64-mingw32-gcc-posix CXX=x86_64-w64-mingw32-g++-posix`

It builds all and well until the tests:

```bash
/usr/bin/x86_64-w64-mingw32-g++  -I. -I./include -fno-builtin-memcmp -D_REENTRANT -DOS_WINDOWS -DLEVELDB_PLATFORM_WINDOWS -DWINVER=0x0500 -D__USE_MINGW_ANSI_STDIO=1 -Ofast db/autocompact_test.cc out-static/db/builder.o out-static/db/c.o out-static/db/dbformat.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/table/block_builder.o out-static/table/block.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table_builder.o out-static/table/table.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env.o out-static/util/env_posix.o out-static/util/env_win.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/port/port_win.o out-static/port/port_posix_sse.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/autocompact_test -lshlwapi
/usr/bin/x86_64-w64-mingw32-gcc -I. -I./include -fno-builtin-memcmp -D_REENTRANT -DOS_WINDOWS -DLEVELDB_PLATFORM_WINDOWS -DWINVER=0x0500 -D__USE_MINGW_ANSI_STDIO=1 -Ofast -c db/c_test.c -o out-static/db/c_test.o
db/c_test.c: In function ‘main’:
db/c_test.c:174:19: warning: implicit declaration of function ‘geteuid’ [-Wimplicit-function-declaration]
            ((int) geteuid()));
                   ^
/usr/bin/x86_64-w64-mingw32-g++  out-static/db/c_test.o out-static/db/builder.o out-static/db/c.o out-static/db/dbformat.o out-static/db/db_impl.o out-static/db/db_iter.o out-static/db/dumpfile.o out-static/db/filename.o out-static/db/log_reader.o out-static/db/log_writer.o out-static/db/memtable.o out-static/db/repair.o out-static/db/table_cache.o out-static/db/version_edit.o out-static/db/version_set.o out-static/db/write_batch.o out-static/table/block_builder.o out-static/table/block.o out-static/table/filter_block.o out-static/table/format.o out-static/table/iterator.o out-static/table/merger.o out-static/table/table_builder.o out-static/table/table.o out-static/table/two_level_iterator.o out-static/util/arena.o out-static/util/bloom.o out-static/util/cache.o out-static/util/coding.o out-static/util/comparator.o out-static/util/crc32c.o out-static/util/env.o out-static/util/env_posix.o out-static/util/env_win.o out-static/util/filter_policy.o out-static/util/hash.o out-static/util/histogram.o out-static/util/logging.o out-static/util/options.o out-static/util/status.o out-static/port/port_win.o out-static/port/port_posix_sse.o out-static/util/testharness.o out-static/util/testutil.o -o out-static/c_test -lshlwapi
out-static/db/c_test.o:c_test.c:(.text.startup+0x3c): undefined reference to `geteuid'
collect2: error: ld returned 1 exit status
Makefile:323: recipe for target 'out-static/c_test' failed
make: *** [out-static/c_test] Error 1
```

**Comment by cmumford** [comment]
@D3m0nKingx leveldb switched to CMake a little while ago. Can you try this with the tip-of-tree?

**Comment by D3m0nKingx** [comment]
@cmumford I'm using a Bitcoin's implementation of leveldb (version 1.20) (https://github.com/bitcoin-core/leveldb/commit/1bdf1c34c5d903e466673a15103124568d995db4)

The issue is the matter that _geteuid_ does not exist in Windows (mingw32). Some googling indicated the Win equivalent would be *GetUserName()* (see, https://stackoverflow.com/questions/1594746/win32-equivalent-of-getuid) or (https://stat.ethz.ch/pipermail/bioc-devel/2018-March/012907.html)

As a reminder I am **cross-compiling** on linux with x86_64-w64-mingw32-g++(and gcc)-posix compiler to produce a 64-bit binary.

There is no issue with just straight compiling for linux... and for windows (without compiling tests)
  
Any assistance would be appreciated. For the time being I've disabled compilation of the leveldb tests, and my program successfully compiles. Albeit, I would prefer this compiles properly with tests included. 

 Thank you for your assistance.

----
FYI I tried building for POSIX from master and resulted in an error:
![image](https://user-images.githubusercontent.com/18432686/56396936-5022cc00-620f-11e9-8fad-805420e03f04.png)
----

I've Attached (unistd.h) from linux and mingw32 headers. Only linux header defines geteuid not mingw32:
Locations of files are in:
/usr/x86_64-w64-mingw32/include/unistd.h
/usr/include/unistd.h
[unistd.h.zip](https://github.com/google/leveldb/files/3096482/unistd.h.zip)

**Comment by cmumford** [comment]
@D3m0nKingx Use of geteuid was removed from c_test.c in https://github.com/google/leveldb/commit/623d014a54f8cf9b74ad6aaba9181ca1e65c43a1. You should ping the team managing that leveldb fork over at https://github.com/bitcoin/bitcoin/tree/master/src/leveldb.

**Comment by cmumford** [comment]
Closing as this issue is already fixed in this project and now has an issue open on the other project.
