### ISSUE TITLE
leveldb built by g++ 8.2 but when test there comes undefined reference to `leveldb::DB::Open(leveldb::Options const&

### ISSUE THREAD

**Issue by tuhooo** [google/leveldb#680]
`cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
`
`
make install
`
then test with
`g++ -g -o my_level_db_test  my_level_db_test.cpp  -lleveldb -lpthread`

but here comes error 

/root/leveldb/build/my_level_db_test.cpp:9: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status

I try to google this, but it seems my g++ version not correct, any one can help me, thanks a lot~

**Comment by cmumford** [comment]
Is libleveldb.so in your path? What happens if you run this way?

```bash
LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH} my_level_db_test
```

**Comment by cmumford** [comment]
Oh, you have a linking problem instead of one at runtime. Add `-L/usr/local/lib` to your call to g++.

**Comment by tuhooo** [comment]
> Oh, you have a linking problem instead of one at runtime. Add `-L/usr/local/lib` to your call to g++.

after `make install`，static library `libleveldb.a` is installed into /usr/local/lib64 instead of `libleveldb.so`
```
[root@localhost build]# g++ -g -o my_level_db_test  my_level_db_test.cpp  -L/usr/local/lib64 -lleveldb -lpthread
/tmp/ccJDnkV1.o: In function 'main':
/root/leveldb/build/my_level_db_test.cpp:9: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status
```

here is my test code:

```
#include <cassert>
#include "leveldb/db.h"

int main() {

  leveldb::DB* db;
  leveldb::Options options;
  options.create_if_missing = true;
  leveldb::Status s = leveldb::DB::Open(options, "/tmp/testdb", &db);
  assert(s.ok());

  delete db;

  return 0;
}
```

thanks for replying !

**Comment by cmumford** [comment]
That links and runs on my system. Maybe you have another leveldb in your include/library paths somewhere. What does strace show?

```bash
strace -e trace=file -f g++ -g -o my_level_db_test  my_level_db_test.cpp  -L/usr/local/lib64 -lleveldb -lpthread
```

**Comment by cmumford** [comment]
Haven't heard back. I'm going to close this, but if you still have questions feel free to reopen.
