### ISSUE TITLE
Build for iOS failed after using CMake

### ISSUE THREAD

**Issue by L1MeN9Yu** [google/leveldb#684]
When I use this [toolchain](https://github.com/leetal/ios-cmake) to build for iOS static library,It checks "CRC32C" and "Snappy" not correctly.
If I change the port_config.h to `HAVE_CRC32C 0` and `HAVE_SNAPPY 0`,if fails for arm64 and the output is:
```
/leveldb/util/status.cc:23:29:error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wshorten-64-to-32]
  const uint32_t len1 = msg.size();
                 ~~~~   ~~~~^~~~~~
/leveldb/util/status.cc:24:30: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wshorten-64-to-32]
  const uint32_t len2 = msg2.size();
                 ~~~~   ~~~~~^~~~~~
```

Any suggestion for building for iOS?

**Comment by cmumford** [comment]
Hi @L1MeN9Yu leveldb doesn't officially support iOS, but hopefully another iOS developer here can offer you some advice. We are considering adding support for pkg-config (see issue #658) which *might* make iOS support easier.

**Comment by cmumford** [comment]
Fixed (at least warnings are) in https://github.com/google/leveldb/commit/ae49533210e96bdee9c9479a7fa547f375a39c8b.

**Comment by kkHAIKE** [comment]
https://github.com/leetal/ios-cmake/issues/47
