### ISSUE TITLE
CMake: Use find_package() to find snappy

### ISSUE THREAD

**Issue by chfast** [google/leveldb#685]
Create proper FindSnappy.cmake module and use `find_package()` to find the dependency. Create an imported target representing the library.

Also consider using `find_package(... CONFIG)` as snappy exports CMake package config files.

**Comment by pwnall** [comment]
Thank you for your contribution!

We're not currently interested in contributions to the build configuration. We now have a paragraph explaining the situation in  https://github.com/google/leveldb/blob/master/README.md#contributing-to-the-leveldb-project
