### ISSUE TITLE
LevelDb for Android

### ISSUE THREAD

**Issue by hashweather** [google/leveldb#689]
I am not too familiar with Jni but I would love to use LevelDb for my data intensive app which is meant to generate a huge database of data on the SD card. 

What's the recommended way to use LevelDb on Android from a Java perspective? 

Thanks alot.

**Comment by cmumford** [comment]
Not much discussion here as this project is only C/C++. Maybe throw a question up on StackExchange or maybe the [leveldb group](https://groups.google.com/forum/#!forum/leveldb).
