### ISSUE TITLE
Can atomic updates rollback?

### ISSUE THREAD

**Issue by ehds** [google/leveldb#691]
If I have an atomic update like that:
```
    leveldb::WriteBatch batch;
    batch.Put("key1","value");
    batch.Delete("key1");
    auto s = db->Write(leveldb::WriteOptions(), &batch);
```
If something wrong happened at the `put` operation process, the `delete` can't go on, but the key1 is added into the database. This is not user want, and user have no idea which operation fail,so they can't rollback it.

I modified the function `WriteBatch::Iterate`in [write_batch.cc](https://github.com/google/leveldb/blob/master/db/write_batch.cc), making it  corruption when the first put executed.
```
 if (GetLengthPrefixedSlice(&input, &key) &&
            GetLengthPrefixedSlice(&input, &value)) {
          handler->Put(key, value);
          return Status::Corruption("bad WriteBatch Put");
        } else {
          return Status::Corruption("bad WriteBatch Put");
}
```
Then I tried the atomic batch like above, obviously  I got corruption, but I have no idea which operation was wrong, Then I use `Get` function to get the value of `key1`, the status is ok,I successfully obtained the value. Which means the value was put into the database,it didn't rollback to the status before I executed the `Write` operation.

**Comment by cmumford** [comment]
The batch (from your example above) are only written to disk when `leveldb::DB::Write(const WriteOptions& options, WriteBatch* updates` is called - and that write is atomic so "key1" won't be in the database regardless of if Write fails or succeeds (assuming you haven't added it elsewhere).  There is no API for rolling back a writebatch.

**Comment by ehds** [comment]
> The batch (from your example above) are only written to disk when `leveldb::DB::Write(const WriteOptions& options, WriteBatch* updates` is called - and that write is atomic so "key1" won't be in the database regardless of if Write fails or succeeds (assuming you haven't added it elsewhere). There is no API for rolling back a writebatch.

ops I forgot to add `Write` operation.Like above example, the log is written to disk,the key1 is added into memory table, but something wrong happened, so the `delete` is not operated. After compaction, will the key1 be written to sstable?

**Comment by cmumford** [comment]
No, either the key/delete will be written, or nothing will. It is atomic.

**Comment by cmumford** [comment]
Closing as answered.

**Comment by CMCDragonkai** [comment]
Does this mean `WriteBatch` is purely in-memory? That is there's no journal on disk where the batch data is persisted?
