### ISSUE TITLE
VC++ MFC Detected memory leaks

### ISSUE THREAD

**Issue by libaineu2004** [google/leveldb#695]
**Expected Behavior**
I used VS2015 to create a new MFC multi-document project, and then introduced the leveldb
library into the project, only the private declaration in the class:
#include <leveldb/db.h>
leveldb::DB* db;
leveldb::Options options;
options.create_if_missing = true;

When the software exits, it prompts memory leaks.

**Current Behavior**
Detected memory leaks!
WARNING: Visual Leak Detector detected memory leaks!
---------- Block 326 at 0x00EBE7E0: 120 bytes ----------
  CRT Alloc ID: 553
  Leak Hash: 0xF90ED613, Count: 1, Total 120 bytes
  Call Stack (TID 14912):
    ucrtbased.dll!malloc()
    f:\dd\vctools\crt\vcstartup\src\heap\new_scalar.cpp (19): SmartDispenser.exe!operator new() + 0x9 bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\env_windows.cc (699): SmartDispenser.exe!leveldb::InitDefaultEnv() + 0x41 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits (1375): SmartDispenser.exe!std::_Invoker_functor::_Call<void (__cdecl&)(void)>() + 0x10 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits (1443): SmartDispenser.exe!std::invoke<void (__cdecl&)(void)>() + 0x12 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (470): SmartDispenser.exe!std::_Invoke_stored_explicit<void (__cdecl&)(void),std::exception_ptr &,0>() + 0x1B bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (497): SmartDispenser.exe!std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr &>,std::integer_sequence<unsigned int,0>,1>() + 0x17 bytes
    ntdll.dll!LdrEnumerateLoadedModules() + 0x95 bytes
    kernel32.dll!InitOnceExecuteOnce() + 0x17 bytes
    MSVCP140D.dll!_crtInitOnceExecuteOnce() + 0x41 bytes
    MSVCP140D.dll!std::_Execute_once() + 0x16 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (519): SmartDispenser.exe!std::call_once<void (__cdecl&)(void)>() + 0x1D bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\env_windows.cc (707): SmartDispenser.exe!leveldb::Env::Default() + 0xF bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\options.cc (12): SmartDispenser.exe!leveldb::Options::Options() + 0x5 bytes
    d:\my resources\2-part time\smartdispenser\smartdispenser 2019.6.1\smartdispenser\smartdispenser.cpp (525): SmartDispenser.exe!CSmartDispenserApp::InitSoft()
    d:\my resources\2-part time\smartdispenser\smartdispenser 2019.6.1\smartdispenser\smartdispenser.cpp (221): SmartDispenser.exe!CSmartDispenserApp::InitInstance() + 0x8 bytes
    mfc140d.dll!0x049BF961()
    f:\dd\vctools\vc7libs\ship\atlmfc\src\mfc\appmodul.cpp (26): SmartDispenser.exe!WinMain()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (99): SmartDispenser.exe!invoke_main()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (253): SmartDispenser.exe!__scrt_common_main_seh() + 0x5 bytes
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (296): SmartDispenser.exe!__scrt_common_main()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_winmain.cpp (17): SmartDispenser.exe!WinMainCRTStartup()
    kernel32.dll!BaseThreadInitThunk() + 0x12 bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0x63 bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0x36 bytes
  Data:
    E4 48 92 00    02 00 00 00    A8 85 8F 0F    00 00 00 00     .H...... ........
    CD CD CD CD    CD CD CD CD    CD CD CD CD    CD CD CD CD     ........ ........
    CD CD CD CD    CD CD CD CD    CD CD CD CD    FF FF FF FF     ........ ........
    00 00 00 00    24 85 8F 0F    00 00 00 00    CD CD CD CD     ....$... ........
    CD CD CD CD    CD CD CD CD    CD CD CD CD    CD CD CD CD     ........ ........
    CD CD CD CD    CD CD CD CD    CD CD CD CD    00 CD CD CD     ........ ........
    38 0D EC 00    00 00 00 00    00 00 00 00    00 00 00 00     8....... ........
    00 00 00 00    00 00 00 00                                   ........ ........

---------- Block 327 at 0x00EC0D38: 8 bytes ----------
  CRT Alloc ID: 554
  Leak Hash: 0xF02EA576, Count: 1, Total 8 bytes
  Call Stack (TID 14912):
    ucrtbased.dll!malloc()
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0 (977): SmartDispenser.exe!std::_Wrap_alloc<std::allocator<std::_Container_proxy> >::allocate()
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\deque (844): SmartDispenser.exe!std::_Deque_alloc<std::_Deque_base_types<leveldb::`anonymous namespace'::WindowsEnv::BGItem,std::allocator<leveldb::`anonymous namespace'::WindowsEnv::BGItem> > >::_Alloc_proxy() + 0xA bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\deque (810): SmartDispenser.exe!std::_Deque_alloc<std::_Deque_base_types<leveldb::`anonymous namespace'::WindowsEnv::BGItem,std::allocator<leveldb::`anonymous namespace'::WindowsEnv::BGItem> > >::_Deque_alloc<std::_Deque_base_types<leveldb::`anonymous namespace'::WindowsEnv::BGItem,std:()
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\deque (980): SmartDispenser.exe!std::deque<leveldb::`anonymous namespace'::WindowsEnv::BGItem,std::allocator<leveldb::`anonymous namespace'::WindowsEnv::BGItem> >::deque<leveldb::`anonymous namespace'::WindowsEnv::BGItem,std::allocator<leveldb::`anonymous namespace'::WindowsEnv::BGItem>()
    d:\my resources\7-cmakeprj\leveldb-1.22\util\env_windows.cc (656): SmartDispenser.exe!leveldb::`anonymous namespace'::WindowsEnv::WindowsEnv() + 0x12 bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\env_windows.cc (699): SmartDispenser.exe!leveldb::InitDefaultEnv() + 0x5C bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits (1375): SmartDispenser.exe!std::_Invoker_functor::_Call<void (__cdecl&)(void)>() + 0x10 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits (1443): SmartDispenser.exe!std::invoke<void (__cdecl&)(void)>() + 0x12 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (470): SmartDispenser.exe!std::_Invoke_stored_explicit<void (__cdecl&)(void),std::exception_ptr &,0>() + 0x1B bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (497): SmartDispenser.exe!std::_Callback_once<std::tuple<void (__cdecl&)(void),std::exception_ptr &>,std::integer_sequence<unsigned int,0>,1>() + 0x17 bytes
    ntdll.dll!LdrEnumerateLoadedModules() + 0x95 bytes
    kernel32.dll!InitOnceExecuteOnce() + 0x17 bytes
    MSVCP140D.dll!_crtInitOnceExecuteOnce() + 0x41 bytes
    MSVCP140D.dll!std::_Execute_once() + 0x16 bytes
    c:\program files (x86)\microsoft visual studio 14.0\vc\include\mutex (519): SmartDispenser.exe!std::call_once<void (__cdecl&)(void)>() + 0x1D bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\env_windows.cc (707): SmartDispenser.exe!leveldb::Env::Default() + 0xF bytes
    d:\my resources\7-cmakeprj\leveldb-1.22\util\options.cc (12): SmartDispenser.exe!leveldb::Options::Options() + 0x5 bytes
    d:\my resources\2-part time\smartdispenser\smartdispenser 2019.6.1\smartdispenser\smartdispenser.cpp (525): SmartDispenser.exe!CSmartDispenserApp::InitSoft()
    d:\my resources\2-part time\smartdispenser\smartdispenser 2019.6.1\smartdispenser\smartdispenser.cpp (221): SmartDispenser.exe!CSmartDispenserApp::InitInstance() + 0x8 bytes
    mfc140d.dll!0x049BF961()
    f:\dd\vctools\vc7libs\ship\atlmfc\src\mfc\appmodul.cpp (26): SmartDispenser.exe!WinMain()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (99): SmartDispenser.exe!invoke_main()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (253): SmartDispenser.exe!__scrt_common_main_seh() + 0x5 bytes
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (296): SmartDispenser.exe!__scrt_common_main()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_winmain.cpp (17): SmartDispenser.exe!WinMainCRTStartup()
    kernel32.dll!BaseThreadInitThunk() + 0x12 bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0x63 bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0x36 bytes
  Data:
    40 E8 EB 00    00 00 00 00                                   @....... ........

Visual Leak Detector detected 2 memory leaks (3500 bytes).
Largest number used: 38163216 bytes.
Total allocations: 75597675 bytes.
Visual Leak Detector is now exiting.

**Steps to Reproduce**
Use VS2015 to create an MFC app. Add:
#include <leveldb/db.h>
leveldb::DB* db;
leveldb::Options options;
options.create_if_missing = true;
leveldb::Status s = leveldb::DB::Open(options, "test", &db);
delete db;
Compile and run... on exit will show leaks

**Version:** 
leveldb-1.22

**Platform:** 
Win7,x64

**Compiler:** 
VS2015,Win32

**Comment by ghemawat** [comment]
If I understand correctly, it seems like the leak detector you are using complains about any allocation that is not deallocated.  LevelDB development (and many other projects) use a different definition of a leak: allocated objects that are not reachable from any global variables.  This is beneficial in that it does not require cleaning up allocations at exit when the operating system will do that for us much more efficiently and safely.  (Safely because it would be unsafe to deallocate things that might be in use by threads that are live when the process is exiting.)

The objects that are being reported here fall into this category and we will not attempt to deallocate them on process exit.  I suggest you switch to a leak detector that implements the reachability rule (Leak sanitizer is one such detector).
