### ISSUE TITLE
Are iterators thread safe or not ?

### ISSUE THREAD

**Issue by htotvs** [google/leveldb#697]
Dear all, 

1st of all. thanks for your great work with `leveldb`.

Unfortunately, I'm not a native speaker of either English or `leveldb`. 

I've read the [concurrency](https://github.com/google/leveldb/blob/master/doc/index.md#concurrency) section of the documentation, as suggested elsewhere, but I'm still confused by the phrasing in the text that quoted: there's _"different threads may write into or fetch iterators or call Get on the same database without any external synchronization"_, but there's also _"However other objects (like Iterator and WriteBatch) may require external synchronization."_

So, my question is: Is there a way to use `leveldb`'s concurrent abilities while using iterators ?

All the best,
Hilton

**Comment by pwnall** [comment]
There's a good point in this question. We should explicitly state thread safety for each class. At a minimum, we should do that for the public API.

Iterators are not thread-safe. You can use multiple iterators from separate threads, but each iterator's use has to be contained to a thread or protected  by a mutex. In other words, leveldb databases support concurrent access, but iterators don't.

**Comment by htotvs** [comment]
Thank you, @pwnall !

Your information will help me become more fluent in `leveldb`. I hope that soon I will have the sample source code that exemplifies these concepts.
