### ISSUE TITLE
Assertion failure in version_set.cc:776

### ISSUE THREAD

**Issue by tmm1** [google/leveldb#708]
I'm getting an assertion failure here:

https://github.com/google/leveldb/blob/53e280b56866ac4c90a9f5fcfe02ebdfd4a19832/db/version_set.cc#L776

What might cause this?

**Comment by ghemawat** [comment]
This is likely to happen if an iterator is live when the DB is destroyed.

**Comment by tmm1** [comment]
Thanks for the pointer. I will double check to see if any iterators are leaking.

What's strange is that this is only happening on Windows (Windows 10 Pro
10.0.17763 Build 17763) and only on some machines.

**Comment by cmumford** [comment]
Closing as answered. Please reopen if necessary.
