### ISSUE TITLE
Production compilation options

### ISSUE THREAD

**Issue by tmm1** [google/leveldb#709]
Since the switch over to cmake, is it still recommended to use custom compilation flags similar to the old build systems' `OPT="-O2 -DNDEBUG"`?

I guess the equivalent in cmake would be `cmake -DCMAKE_CXX_FLAGS="-O2 -DNDEBUG"`?

**Comment by cmumford** [comment]
Those (-O2/NDEBUG) should be set correctly when setting [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html). Please reopen if you have followup questions.

**Comment by tmm1** [comment]
Thank you! Looks like I missed this in the readme: https://github.com/google/leveldb/blob/53e280b56866ac4c90a9f5fcfe02ebdfd4a19832/README.md#build-for-posix

**Comment by tmm1** [comment]
Are there any other flags added by `CMAKE_BUILD_TYPE= Release`? I'm having a hard time finding where that's defined in the project.

**Comment by tmm1** [comment]
> I'm having a hard time finding where that's defined in the project.

It's part of CMake: https://stackoverflow.com/a/34314956/332798
