### ISSUE TITLE
LevelDB keeps on creating new table files but won't delete any of them

### ISSUE THREAD

**Issue by Qiao-Jin** [google/leveldb#711]
By chance I will run into the following scenarios:

1. sst table files keep on increasing until my disk blows up, during which no sst deletion occurs;

2. Restart leveldb, and thousands of deletion occurs until db size returns to normal

Is there anyone else with the same problem? What might be the cause? Such as compaction fails to delete older table files due to some reason?

**Comment by july2993** [comment]
maybe you create snapshot in your application but you never release it

**Comment by cmumford** [comment]
@Qiao-Jin can you post a sample program that demonstrates what you are seeing?

**Comment by Qiao-Jin** [comment]
> @Qiao-Jin can you post a sample program that demonstrates what you are seeing?

The reason is unrealeased snapshots prevent compaction deleting outdated files. After fixing by releasing forgotten snapshots the problem never occurs . Thanks!
