### ISSUE TITLE
How enable leveldb in Debian after Build?

### ISSUE THREAD

**Issue by akudryav** [google/leveldb#712]
I've made compilation in Debian using readme instructions:

```bash
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
```

But when I start program required leveldb it says:
```
./minter: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory
```

And there is no libleveldb.so files at all.

**Comment by cmumford** [comment]
Your call to cmake will result (by default) in a static library (`libleveldb.a`). To build a shared library you need to:

```bash
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
```

**However** you will almost certainly need to rebuild your minter program as it was compiled against an earlier version of leveldb.

**Comment by akudryav** [comment]
Fine, after you command I've execute make and make install, then ldconfig and it works now! Thanks a lot)
