### ISSUE TITLE
[Noob Question] Better way to store HashMap/Array into LevelDB

### ISSUE THREAD

**Issue by bcashier** [google/leveldb#714]
Hi,

I am willing to store HashMap / Array into LevelDB, is there a feature for this ? Or a best approach to do that please ?

I am thinking to store them in form of JSON as value, but that will not let me make modifications quickly since I have first to deserialize the JSON and then make modification, and finally serialize back.

Thanks in advance

**Comment by pwnall** [comment]
LevelDB doesn't support structured values, or partially updating a value.
