### ISSUE TITLE
[Noob Question] Use wildcard to display ordered keys 

### ISSUE THREAD

**Issue by bcashier** [google/leveldb#715]
Hi,

Is there a way to use wildcard in order to display ordered keys (By ASC => Time of insertion) ?

For example, I am inserting keys in this format:

```
db.put('save:1', 'test 1');
db.put('save:2', 'test 2');
...
```

And then, iterate to display all keys containing: "`save:*`"

Thank you

**Comment by pwnall** [comment]
You'll generally get faster response times for usage questions on StackOverflow.

Create an Iterator, seek to `save:` and iterate (via Next) over keys until you see a key that doesn't start with `save:`, or until you get to the end of the database.
