### ISSUE TITLE
how to convert float vector and storage to LevelDB with C++? 

### ISSUE THREAD

**Issue by wkj0121** [google/leveldb#720]

**Comment by originalsouth** [comment]
Not entirely sure what you want but you could either serialize he float vector to a string and than store it as a value or you could use the indexes as keys and store the float values as values.

**Comment by cmumford** [comment]
Here's how to [serialize a float](http://www.cplusplus.com/forum/general/201675/). Make sure to read the section about Endian'ness. Then just do it for each float in the vector.
