### ISSUE TITLE
Buildtime error@ Xcode11.1

### ISSUE THREAD

**Issue by KeiKur0** [google/leveldb#748]
I did "pod update" and current version is 1.2.2. (leveldb-library (~> 1.22))
"leveldb-library" is used in the swift application, which uses Firebase.
Xcode version is 11.1.

I can't find out what is the cause and how to measure.. 

![buildtime error](https://user-images.githubusercontent.com/51199500/67760296-6514cd80-fa84-11e9-821c-30f11f91e04d.png)

**Comment by cmumford** [comment]
This project doesn't create or produce pod configuration files - this is done by another downstream project.
