### ISSUE TITLE
"LevelDBError: Corruption: CURRENT file does not end with newline"  database recovery was not possible

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#75]
Original [issue 69](https://code.google.com/p/leveldb/issues/detail?id=69) created by vera.voropaeva@phystech.edu on 2012-01-26T14:04:40.000Z:

<b>What steps will reproduce the problem?</b>
1. we tested synchronous and async write operations
2. while writing a big block of data we turned of the PC
3. on the next computer start: LevelDBError: Corruption: CURRENT file does not end with newline 

Database recovery did not start automatically. 
We were unable to recover the database

**Comment by ne0ark** [comment]
I am getting this also. {"level":"error","message":"Could not get usedSpace: Corruption: CURRENT file does not end with newline","timestamp":"2017-03-17T12:29:29.015Z"} when using mounted google drive with fuse.
