### ISSUE TITLE
CMakefile.txt macro issues

### ISSUE THREAD

**Issue by kinglezhuang** [google/leveldb#758]
if (WIN32)
  set(LEVELDB_PLATFORM_NAME LEVELDB_PLATFORM_WINDOWS)
  add_definitions(-D_UNICODE -DUNICODE)
else (WIN32)
  set(LEVELDB_PLATFORM_NAME LEVELDB_PLATFORM_POSIX)
endif (WIN32)

if (WIN32)
  target_sources(leveldb
    PRIVATE
      "util/env_windows.cc"
      "util/windows_logger.h"
  )
else (WIN32)
  target_sources(leveldb
    PRIVATE
      "util/env_posix.cc"
      "util/posix_logger.h"
  )
endif (WIN32)

Very confuse about above script. Is it correct?

I think we need win32 & unix condition

**Comment by pwnall** [comment]
The expressions next to `else` and `endif` are optional, and repeat the `if` condition. https://cmake.org/cmake/help/latest/command/if.html
