### ISSUE TITLE
DestroyEmptyDir test fails with Chromium env

### ISSUE THREAD

**Issue by kaadam** [google/leveldb#772]
Hi All,

If I run leveldb test from Chromium environment, DestroyEmptyDir test case fails, because Chromium's env implementation[1] filters out '.' and '..'. So the number of children will be zero. 

[1]: https://cs.chromium.org/chromium/src/third_party/leveldatabase/env_chromium.cc?rcl=21d8ff1e1b8eaaa253bc7e8a79aa7d2c96b1d907&l=766

![DestroyEmptyDir](https://user-images.githubusercontent.com/1853930/72159490-c3cbc100-33bc-11ea-9573-5b54ba67711a.png)

What do you think if I open a PR, where I guarded the check like this? 

#if !defined(LEVELDB_PLATFORM_CHROMIUM) 
  ASSERT_EQ(2, children.size());
#endif

Thanks Adam

**Comment by pwnall** [comment]
This is a bug in Chromium's env implementation, and should be fixed in Chromium. We're tracking it at https://crbug.com/865343
