### ISSUE TITLE
Encryption of LevelDB

### ISSUE THREAD

**Issue by berrycof** [google/leveldb#782]
I need to encrypt my LevelDB files.
I'll decrypt them in memory when I need them.
How to load LevelDB from memory?
If not, can you add this feature, or make another package for this feature?
I won't decrypt them and write them back to disk for loading.

**Comment by cmumford** [comment]
Hi @berrycof. leveldb doesn't support encryption and we don't plan on adding it as the goal is to keep the API simple and avoid feature creep. However there are two ways for you to encrypt data in leveldb today. The first, if I understand your idea, is to encrypt the data before you write to the db. This will likely result in poor performance if the keys are encrypted. Alternatively you can implement your own leveldb::Env, or override the provided one. This has the advantage of encrypting all data being written to disk - not just your key/value pairs. Good luck.

**Comment by thanhlv93** [comment]
Hello @cmumford ,I'm new in C++ and level db. Can you make clear your idea for encrypt the data before you write to the db please : 

> lternatively you can implement your own leveldb::Env, or override the provided one

Thank you.

**Comment by cmumford** [comment]
I just meant that just before the Env did the actual write (like by
calling WriteUnbuffered) it would encrypt the data. However, in practice,
this would be very difficult. An alternative is to get a library that does
the file encryption for you, and just use it. File based encryption is
difficult to implement. Adding encryption properly is *extremely* difficult
to get right. I strongly recommend going with an existing solution instead
of implementing your own. Like can you use the OS features to encrypt the
entire hard drive?

**Comment by thanhlv93** [comment]
Thank you for the explanation @cmumford . I will try your approach, decrypt data before WriteUnbuffered in env_posix.cc file and decrypt data in db_impl#Get .

**Comment by thanhlv93** [comment]
After putting the log in WriteUnbuffered, I can see that the method not only I call but also other places in the system also call (example: write MANIFEST data ...). How can I tell which data is mine?

**Comment by cmumford** [comment]
You can't do it here if you only want your data encrypted. In that case
encrypt your keys/values before using the leveldb API.

**Comment by suntzu93** [comment]
But as you said : I just meant that just before the Env did the actual write (like by
calling WriteUnbuffered) it would encrypt the data. -> This is process write data to a file so It does not have the same meaning as encrypt a file. 

I logout ( using __android_log_print ) data in WriteUnbuffered method but I dont understand what happend with data, can you explain or suggest how can encrypt data with this format :

> WriteUnbuffered  size = 1029 ,data = �z
    ��

and java code to put to db :

>      char[] data = new char[1000];
>       Arrays.fill(data, 'f')
>       String str = new String(data);
>       db.put("test-0", str.getBytes());

Thank you.
