### ISSUE TITLE
leveldb function, GetStats(), has error

### ISSUE THREAD

**Issue by bwanaaa** [google/leveldb#787]
I installed the python wrapped version of leveldb from here:
https://github.com/happynear/py-leveldb-windows
I created a test db to explore what properties leveldb includes

```
import leveldb
path = '../data/icons-db4'       #some random database in .sst format
db = leveldb.LevelDB(path)
print(dir(db))
```
The output is

`['CompactRange', 'CreateSnapshot', 'Delete', 'Get', 'GetStats', 'Put', 'RangeIter', 'Write', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
`

Since these are interesting method names I need to find out more about them

```
object_methods = [method_name for method_name in dir(db)
                  if callable(getattr(db, method_name))]
for x in object_methods:
    print(x+'\n++++++++++\n',x.__doc__+'\n++++++++++\n',str(getattr(db, x).__doc__),'\n==================\n\n')
```
The output includes one entry that is

```
GetStats
++++++++++
 str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.
++++++++++
 get a mapping of all DB statistics 
```

So i tried it `print(db.GetStats())` and got

```
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-8-3754af55670c> in <module>
----> 1 print(db.GetStats())

SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!
```

okaaaay.

otherwise leveldb seems to work fine in python

**Comment by pwnall** [comment]
This repository is focused on the C++ library. I suggest you try StackOverflow, or the Issues page of the repository you mentioned above.
