### ISSUE TITLE
if leveldb's sequence number has run out, what show we do?  😄

### ISSUE THREAD

**Issue by sfwtoms2030** [google/leveldb#792]
the sequence number has 56 bit, if we run out,  what show we do ?

**Comment by sfwtoms2030** [comment]
any idea ?

**Comment by ghemawat** [comment]
This shouldn't happen in any foreseeable time: let's assume that we are
writing at 1M per second.  That means we will run out of sequence numbers
after 2^56/1000000 seconds, which is over 2000 years.
