### ISSUE TITLE
Build on MacOs failed due to undefined symbols in skiplist_test

### ISSUE THREAD

**Issue by Tjianke** [google/leveldb#801]
Hello, I'm building LevelDB according to official instruction:
1. git clone --recurse-submodules https://github.com/google/leveldb.git
2.  mkdir -p build && cd build
3. cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

Met following problem while Linking CXX executable skiplist_test:

Undefined symbols for architecture x86_64:
  "leveldb::ConcurrentTest::K", referenced from:
      leveldb::ConcurrentTest::ReadStep(leveldb::Random*) in skiplist_test.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [skiplist_test] Error 1
make[1]: *** [CMakeFiles/skiplist_test.dir/all] Error 2
<img width="837" alt="image" src="https://user-images.githubusercontent.com/34013484/80547647-52eff980-89eb-11ea-9bec-581bbefecb6b.png">

System config:
Mojave 10.14.5
Clang:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix

Not sure why it happens

**Comment by pwnall** [comment]
I think this problem was fixed in https://github.com/google/leveldb/commit/23d67e7c1f4396919bd0c73c0eced13a0dac37f3

Can you try doing a fresh build off of master?

**Comment by Tjianke** [comment]
fixed! thx
