### ISSUE TITLE
LZW common dictionary key index

### ISSUE THREAD

**Issue by ohhmm** [google/leveldb#802]
Hi,

I have very long string keys.
So I have an idea to use its LZW representation as a key. 
But then I think, hey, LevelDB could do that feature for common gain.
Than I think that all keys can use common LZW dictionary for storage and performance gain.
What do you think? Could LevelDB take this feature?

Thanks,
Serg

**Comment by pwnall** [comment]
This doesn't seem like something that would be generally useful.

LevelDB needs the uncompressed keys in memory, to do comparisons. Your particular application may get away with compressing the keys before storing them if you only need random access, and not sorted access.

LevelDB compresses data blocks using snappy. You can plug your choice of compression algorithm by searching for "snappy" in the codebase and seeing how it's plumbed through. The main touch points are in ReadBlock() in table/format.cc and TableBuilder::WriteBlock() in table/table_builder.cc

I'm not sure what it'd entail to use a common dictionary. If you're thinking of feeding a static dictionary into the compression algorithm at initialization time, that should be fairly easy to do. If you want to build and update a central dictionary on the fly, this may be quite complicated.

**Comment by ohhmm** [comment]
Hi @pwnall ,

Does snappy provide common dictionary for all keys?

Thanks,
Serg

**Comment by ohhmm** [comment]
I got that sorted access. How it dealt with snappy? Maybe same thing but with common dictionary may give a significant boost?
