### ISSUE TITLE
Feature Request: Custom Comparator with Custom Next Function on Subset of Keyspace

### ISSUE THREAD

**Issue by trenta3** [google/leveldb#821]
The set of keys I use in the database are only a subset of all bytestring, since they come from the [msgpack](http://msgpack.org) encoding. I'm using a custom comparator than unpacks the encoding before comparison and this allows me to create multi-level indexes using a lexicographic order on tuples.

This works well when only using `get`, `put` and `delete` operations.
Unfortunately it does not always work when using prefix iterators, since it may happen that the comparator is given a key outside of the encoding (for example if an inserted key ends in `\x0a\xff` then the comparator may be given the key `\x0b` to test for. I think this is due to `\x0b` being the end of the range) which is ok if the comparator can accept all bytestrings but in general (with custom encoding) this is a source of errors.

I'm asking if it is possible also to delegate a custom `next` function to the implementer of the comparator, so that a key inside of the encoding keyspace can be returned.

Thanks in advance for your time.

**Comment by trenta3** [comment]
Sorry for opening the issue, I've seen that it is probably an issue with the python wrapper I'm using for accessing LevelDB and not with the implementation itself.
If the question makes no sense to you, it can be closed.

**Comment by cmumford** [comment]
No problem @trenta3 . leveldb does allow for custom comparators, but that would need to be supported by the Python wrapper. Good luck!
