### ISSUE TITLE
[Question] Is there any plan to replace StringPiece with string_view?

### ISSUE THREAD

**Issue by hcoona** [google/leveldb#823]
Is there any plan to replace StringPiece with string_view or span?

**Comment by chengchenwish** [comment]
I don't know---Original---From: "Shuai Zhang"<notifications@github.com>Date: Tue, Jul 21, 2020 13:57 PMTo: "google/leveldb"<leveldb@noreply.github.com>;Cc: "Subscribed"<subscribed@noreply.github.com>;Subject: [google/leveldb] [Question] Is there any plan to replace StringPiece with string_view? (#823)
Is there any plan to replace StringPiece with string_view or span?

**Comment by pwnall** [comment]
This codebase is still on C++11.

With that being said, there's definitely a future where we'll jump to C++17, to match the rest of the Google ecosystem. We haven't figured out more concrete details. For now, I think it's worth noting that we haven't switched to smart pointers in the API when we adopted C++11.
