### ISSUE TITLE
how to build .a library for iOS 

### ISSUE THREAD

**Issue by yuzhiyunAtTencent** [google/leveldb#830]
I just run these 2 commands after cloning the project:

mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

Then I drag build/libleveldb.a to my xcode project, xcode shows the error:

Building for iOS Simulator, but the linked library 'libleveldb.a' was built for macOS.

**Comment by pwnall** [comment]
You may be able to get better answers around using LevelDB on StackOverflow.

This forum is for issues in the LevelDB codebase.
