### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by DavidKorczynski** [google/leveldb#846]
Hi maintainers.

I have integrated leveldb into OSS-Fuzz, which is a service for running continuous fuzzing of open source projects. Please take a look here: https://github.com/google/oss-fuzz/pull/4636

If you are happy to have leveldb fuzzed, could you please provide me with emails that should receive reports on the fuzzing, e.g. bug reports. Also, I would be happy to merge the build and fuzzers to the leveldb repository rather than having them on the OSS-Fuzz repository.

**Comment by pwnall** [comment]
The PR above was merged with contacts from the Chrome team. I think this resolves the question here.
