### ISSUE TITLE
Is LevelDB architecture independent?

### ISSUE THREAD

**Issue by mahrud** [google/leveldb#856]
Are the database files produced by LevelDB usable by LevelDB running on another platform?In particular, I'm wondering if the database files depend on word size (32-bit/64-bit) or default endian-ness, as for instance GDBM databases do.

**Comment by pwnall** [comment]
I am pretty sure the format is platform-independent. The code for reading from / writing to disk is supposed to use the functions in `util/coding.h`, which are platform-independent.

That being said, as far as I know, we don't have format stability tests, and we don't run any tests on big-endian platforms.

**Comment by mahrud** [comment]
Thank you!
