### ISSUE TITLE
Leveldb is taking more native memory than allocated

### ISSUE THREAD

**Issue by Krishna7557** [google/leveldb#860]
Hi, 

We are having linux server, where we have a java process which uses leveldb for writing the key value pairs to disk and reads those key value pairs on condition basis. We have integrated the leveldb with our java application using leveldb-jni-all.jar. Currently we are using leveldb version 1.20 and jni version 1.8.1 in our application 
Please find the below settings which we have used for leveldb in our application:

# write buffer and cache size in MB
writebuffersize=64
cachesize=3072
compressiontype=SNAPPY
#Bloom filter policy bit count for db
bitcount=100

# Repair Db settings
writebuffersize=4
compressiontype=SNAPPY
cachesize=4
#Bloom filter policy bit count for repair db
bitcount=10

We have allocated 3 GB from our physical RAM for the LevelDB. Here when we run the tests with LevelDB, in a couple days of our test we could see that our java application is taking 8GB to 10GB more memory than we have allocated. When we tracked the native memory used by Java libraries we could see those are using 3GB of extra memory. When we have taken the pmap output of our java process, we could see more 64MB and 128MB allocations which are anonymous. We suspect remaining 5-7 Gb is being taken by Leveldb.

When the run the same test by disabling leveldb(In our application we have option to enable and disable the usage of leveldb), we couldn't see any issues.

Please let us your opinions or thoughts on this. AAny specific tool you use to track the native memory allocation of leveldb?

Regards,
Krishna

**Comment by nshishov** [comment]
It is opened memory mapped files

**Comment by Krishna7557** [comment]
Can you please elaborate more and how I can track these files

**Comment by Krishna7557** [comment]
If those are opened mmapped files, how to control the amount of this mmap content? Is there any configurable parameter

**Comment by pwnall** [comment]
The memory-mapping behavior is all in LevelDB's POSIX environment. The best way to customize it is to fork (copy and rename) `util/env_posix.cc` and tweak the implementation to meet your needs.

Your question suggests that you're using LevelDB through Java, and this approach requires changing C++ code. Depending on your familiarity with JNI and C++, this may be quite difficult. StackOverflow is more likely to get you better answers to questions on LevelDB *usage* (as opposed to *development*).

**Comment by Krishna7557** [comment]
Hi pwnall.

I have understood that we need to fork the POSIXENV file to our requirements. I have seen a similar issue as ours in the ticket number 866, where you have suggested as below:

They are mapped into the virtual address space read-only/shared, and are backed by the file contents. So the OS will consume physical RAM for those file contents, but will release the RAM when it comes under memory pressure as the data is backed by the file. You can verify this by changing g_mmap_limit to zero, which will cause leveldb to fallback to opening/closing files when needed.

I hope Changing the g_mmap_limit is applicable for us also. If we change like that will be there any impact in leveldb writing .ldb files or I/O stress on the disk.

Regards,
Krishna
