### ISSUE TITLE
Cygwin build error: ‘strdup’ was not declared in this scope 

### ISSUE THREAD

**Issue by Ericyuanhui** [google/leveldb#872]
Hi All
I am trying to build LevelDB master branch with commit ID "commit 1998c0ef15".  I set option  "LEVELDB_BUILD_TESTS"  and "LEVELDB_BUILD_BENCHMARKS" are OFF. I used README doc command to build LevelDB "cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build ."  but I met this error. I know it maybe using "-std = gnu++0x" to replace "-std = c++11". But I do not know how to replace it. Who can tell me how to do it . thank you.
`[  2%] Building CXX object CMakeFiles/leveldb.dir/db/c.cc.o
/home/Kitty/Project/leveldb/db/c.cc: 在函数‘bool SaveError(char**, const leveldb::Status&)’中:
/home/Kitty/Project/leveldb/db/c.cc:150:15: 错误：‘strdup’ was not declared in this scope; did you mean ‘strcmp’?
`

**Comment by Ericyuanhui** [comment]
my Cygwin g++ info is below 
`$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/10/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-10.2.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-10.2.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)`

**Comment by pwnall** [comment]
In general, we don't support Cygwin.

That being said, this particular build error seems like a IWYU omission on our end -- `c.cc` uses `strdup`, which is declared in `<cstring>` / `<string.h>`, but does not include the header. I'll fix this problem.

Can you try adding `#include <cstring>` at the top of `src/db/c.cc`? This should get you unblocked until we push new code.

**Comment by Ericyuanhui** [comment]
I had try it. But the error also happened. I think it is Cygwin standard GCC is "-std = gnu++0x" not "-std = c++11". But when I use this build command "cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build ."  the LevelDB project config would be using "-std = c++11" . I do not know how to modify it. Anyone can help me? thank you.

**Comment by Ericyuanhui** [comment]
Anyone know it ? thank you.

**Comment by Ericyuanhui** [comment]
Finally I find out fix method. Because Cygwin use GCC is "gnu++0x", I change LevelDB CMakeList.txt set CXX flag option.  then I can finish LevelDB build. thank you.

![image](https://user-images.githubusercontent.com/13159415/105864125-9506a400-602c-11eb-8722-b4041abed534.png)
