### ISSUE TITLE
issue: codeblocks linking does not work correctly

### ISSUE THREAD

**Issue by daveisonline** [google/leveldb#873]
when I try to run my c++ code  in Code::Blocks IDE 
I ge : 

```
/usr/bin/ld: /home/kalivm/cpp_files/student/main.o: in function `main':
main.cpp:(.text+0x17d): undefined reference to `Student::toString[abi:cxx11]()'
```
 
hier is my Code: 

```c++
//main.cpp
#include "Student.h"
#include <iostream>
using namespace std;

void printPerson (Person* p){
   cout << "Die Person heisst: " + p->getfullname() << endl;
}

int main(){

    Student* s = new Student("familyname", "name", 23324);
    cout << s->toString() << endl;
    printPerson(s);
    cout << s->matrikelNummer<<endl;

  while(0);
  return 0;
}
```

```c++
//Student.h
#ifndef STUDENT_H
#define STUDENT_H
#include "person.h"

using namespace std;

class Student: public Person {
    public:
        int matrikelNummer;
        int getmatrikelNummer();
        string toString();

        Student(string name, string familyname, int nr) :Person(name,familyname){
            matrikelNummer = nr;
        }
};
#endif // STUDENT_H
```

```c++
//Student.cpp
#include "Student.h"
#include <iostream>
#include <string>
using namespace std;

int Student::getmatrikelNummer(){
    return matrikelNummer;
}

string Student::toString(){
            return (Person::toString() +" ist ein Studen\n" + "Die Matrikelnummer dieser Person lautet: " + to_string(getmatrikelNummer())+ "\n");
 }
```

```c++
//person.h
// person.h
#include <iostream>
using namespace std;

class Person{
    public:
        string name;
        string familyname;
        string getfullname(){
            return (familyname + " "+ name);
        }
        string toString(){
            return "Die Person: " + getfullname();
        }
    //string tostring();//{
       // return ("Person: "+getfullname());
  //  }
        Person(string n, string v):familyname(v),name(n){
            familyname = v;
            name = n;
    }


};
```

Any ideas how to solve it? Thanks.

EDIT: Edited to add proper code blocks

**Comment by cmumford** [comment]
How are you compiling/linking your program?

**Comment by pwnall** [comment]
In general, this kind of question (building software on top of LevelDB) will get better answers quicker on StackOverflow. This repository's issues are good for discussing the development of LevelDB itself.

**Comment by Small25** [comment]
> when I try to run my c++ code  in Code::Blocks IDE 
> 
> I ge : 
> 
> 
> 
> ```
> 
> /usr/bin/ld: /home/kalivm/cpp_files/student/main.o: in function `main':
> 
> main.cpp:(.text+0x17d): undefined reference to `Student::toString[abi:cxx11]()'
> 
> ```
> 
>  
> 
> hier is my Code: 
> 
> 
> 
> ```c++
> 
> //main.cpp
> 
> #include "Student.h"
> 
> #include <iostream>
> 
> using namespace std;
> 
> 
> 
> void printPerson (Person* p){
> 
>    cout << "Die Person heisst: " + p->getfullname() << endl;
> 
> }
> 
> 
> 
> int main(){
> 
> 
> 
>     Student* s = new Student("familyname", "name", 23324);
> 
>     cout << s->toString() << endl;
> 
>     printPerson(s);
> 
>     cout << s->matrikelNummer<<endl;
> 
> 
> 
>   while(0);
> 
>   return 0;
> 
> }
> 
> ```
> 
> 
> 
> 
> 
> ```c++
> 
> //Student.h
> 
> #ifndef STUDENT_H
> 
> #define STUDENT_H
> 
> #include "person.h"
> 
> 
> 
> using namespace std;
> 
> 
> 
> class Student: public Person {
> 
>     public:
> 
>         int matrikelNummer;
> 
>         int getmatrikelNummer();
> 
>         string toString();
> 
> 
> 
>         Student(string name, string familyname, int nr) :Person(name,familyname){
> 
>             matrikelNummer = nr;
> 
>         }
> 
> };
> 
> #endif // STUDENT_H
> 
> ```
> 
> 
> 
> ```c++
> 
> //Student.cpp
> 
> #include "Student.h"
> 
> #include <iostream>
> 
> #include <string>
> 
> using namespace std;
> 
> 
> 
> int Student::getmatrikelNummer(){
> 
>     return matrikelNummer;
> 
> }
> 
> 
> 
> string Student::toString(){
> 
>             return (Person::toString() +" ist ein Studen\n" + "Die Matrikelnummer dieser Person lautet: " + to_string(getmatrikelNummer())+ "\n");
> 
>  }
> 
> ```
> 
> 
> 
> ```c++
> 
> //person.h
> 
> // person.h
> 
> #include <iostream>
> 
> using namespace std;
> 
> 
> 
> class Person{
> 
>     public:
> 
>         string name;
> 
>         string familyname;
> 
>         string getfullname(){
> 
>             return (familyname + " "+ name);
> 
>         }
> 
>         string toString(){
> 
>             return "Die Person: " + getfullname();
> 
>         }
> 
>     //string tostring();//{
> 
>        // return ("Person: "+getfullname());
> 
>   //  }
> 
>         Person(string n, string v):familyname(v),name(n){
> 
>             familyname = v;
> 
>             name = n;
> 
>     }
> 
> 
> 
> 
> 
> };
> 
> ```
> 
> 
> 
> Any ideas how to solve it? Thanks.
> 
> 
> 
> EDIT: Edited to add proper code blocks
> 
>
