### ISSUE TITLE
Empty submodules in release tarball?

### ISSUE THREAD

**Issue by fagg** [google/leveldb#879]
Hello,

I'm the maintainer of the OpenBSD port of leveldb.

Updating from 1.22 to 1.23, it seems that the third_party submodules are *not* populated in the tarball - that means, when you untar, you can't actually build leveldb (with the test suite enabled) since the googletest and benchmark directories are empty. What's more is that since the release tarball isn't actually a git repo, you also can't manually pull the submodules.

I am wondering if this is an oversight, or an intentional change?

If it is intentional, we will have to change the way we build our package and this would turn what is a mostly automated process into something a little more manual - since we would be forced to check out the repo at the release tag, submodule update and then create our own release tarball since our ports build system doesn't allow for this automatically.

I have just submitted a diff to our ports mailing list to update to 1.23, the caveat being the test suite is turned off which is less than ideal. Hoping to understand whats going on so I know what course of action to take going forward.

(We also have a build issue, but I don't think that's your problem - it seems to be related to gmock, which I'll try to work through when I have a little more time).

Thanks.

**Comment by pwnall** [comment]
@cmumford Do we build the tarball? I was under the assumption that GitHub builds a tarball based on the release tag.

**Comment by fagg** [comment]
Victor Costan <notifications@github.com> writes:

> @cmumford Do we build the tarball? I was under the assumption that
> GitHub builds a tarball based on the release tag.

I would expect if you are using git archive, this would be why. For
whatever reason, it does not include populated submodules when creating
the tarball (I expect this is a safe default for dealing with submodules
that are licensed differently to the rest of the project). The automated
system that Github uses to build release archives uses git archive
underneath, so presumably this is why.

**Comment by pwnall** [comment]
The above is correct.

Ideally, GitHub would change the process they use to auto-generate the release archives. I agree that they would be more useful if they included submodules.

I can't justify investing in tarballs, because all Google products consume LevelDB by fetching the code directly from a repository. Assuming we can't change how GitHub generates the archives, I'd be interested in the possibility of disabling them altogether.
