### ISSUE TITLE
'db/version_edit.h' file not found

### ISSUE THREAD

**Issue by naissa12** [google/leveldb#882]
I upgraded to leveldb version 1.22. When I archive my IOS codebase, I get the following error:

'db/version_edit.h' file not found

I'm using Firebase Realtime Database that uses leveldb as a dependency. 

Can anyone please help? 

Here are my settings

<img width="824" alt="Screen Shot 2021-03-06 at 8 21 02 PM" src="https://user-images.githubusercontent.com/951837/110226047-82984980-7eb9-11eb-888d-d375edff38ab.png">

**Comment by pwnall** [comment]
This seems like a better question for StackOverflow. The issue is in your build configuration, not in the LevelDB codebase.
