### ISSUE TITLE
Undefined reference to `typeinfo for leveldb::Comparator'

### ISSUE THREAD

**Issue by mdorier** [google/leveldb#891]
I have a code using LevelDB, which worked fine until version 1.22 (included). However switching to 1.23 gives me the following error at link time:

```
undefined reference to `typeinfo for leveldb::Comparator'
```

LebelDB itself builds fine. This error appears when linking code that uses LevelDB against the LevelDB libraries.

**Comment by liviaerxin** [comment]
In `leveldb` 1.23, it disable `RTTI` with `-fno-rtti`. So if you compile your code and link a static built `libleveldb.a` which did not have `RTTI`, it also need to add `-fno-rtti`

**Comment by mdorier** [comment]
I'm compiling and linking against a dynamic library (libleveldb.so).

**Comment by pwnall** [comment]
We can only support the build configuration used in official Google products, like Chrome. This doesn't include RTTI.

LevelDB should work just fine with RTTI, but you'll need to figure out build configuration changes, and any other workarounds.

**Comment by xkszltl** [comment]
@pwnall 
We hit similar issues when using ubsan, which requires rtti. And combining no-rtti with other rtti components in our project also cause various strange issues.
The majority of leveldb is probably fine with ABI discrepancy, but the custom comparator can have a lot of issue.

We're also seeing other people complaining about this:
- https://github.com/google/leveldb/issues/731
- https://github.com/google/leveldb/issues/927

The current approach forcefully remove -frtti in CMAKE_CXX_FLAGS and then add -fno-rtti.
Can we, instead, check for -frtti there and only add -fno-rtti when it's not presented?
That way people can at least choose what they need.

**Comment by mzygQAQ** [comment]
@pwnall Hi~ Can we consider making the disabling of rtti in leveldb CmakeLists.txt configurable, with the default value being disabled. In this way, external users can still control the behavior of RTTI through switches. Forcefully disabling RTTI makes it impossible for projects that depend on RTTI to customize the comparator.
