### ISSUE TITLE
Downstream projects must find the Threads package on their own

### ISSUE THREAD

**Issue by jasonvaccaro** [google/leveldb#907]
Hi LevelDB folks!

The leveldb project finds the Threads package so downstream projects must also find the Threads package. 
Currently, downstream projects need to figure out how to find the Threads package on their own but we can add the following to levelDbConfig.cmake.in to help them

`include(CMakeFindDependencyMacro)
find_dependency(Threads)`

I'll open a PR with this change momentarily.

(I am new to leveldb and not especially skilled with cmake so this may be wrong)

**Comment by pwnall** [comment]
Thank you for your contribution!

We're not currently interested in contributions to the build configuration. We now have a paragraph explaining the situation in  https://github.com/google/leveldb/blob/master/README.md#contributing-to-the-leveldb-project
