### ISSUE TITLE
how to build leveldb to shared libs

### ISSUE THREAD

**Issue by sangli00** [google/leveldb#916]
```
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
```
only build libleveldb.a ,how to build libleveldb.so?

**Comment by fzj200069** [comment]
Have you solved this problem?
When I tried to use braft,I met the same problem.

**Comment by Coding-Brathan** [comment]
Eda File Ayachutha Da Manda !!!
