### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by ehsandu15** [google/leveldb#921]
When I try to build v 1.23 It gives me the following output:

> CMake Error at CMakeLists.txt:299 (add_subdirectory):
>   The source directory
> 
>     /Users/ehsan687/Desktop/work/testing-rtree/rltms/leveldb-1.23/third_party/googletest
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at CMakeLists.txt:304 (add_subdirectory):
>   The source directory
> 
>     /Users/ehsan687/Desktop/work/testing-rtree/rltms/leveldb-1.23/third_party/benchmark
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at CMakeLists.txt:308 (set_property):
>   set_property could not find TARGET gtest.  Perhaps it has not yet been
>   created.
> 
> 
> CMake Error at CMakeLists.txt:310 (set_property):
>   set_property could not find TARGET gmock.  Perhaps it has not yet been
>   created.
> 
> 
> -- Looking for sqlite3_open in sqlite3
> -- Looking for sqlite3_open in sqlite3 - found
> -- Performing Test HAVE_KYOTOCABINET
> -- Performing Test HAVE_KYOTOCABINET - Failed
> -- Configuring incomplete, errors occurred!
> See also "/Users/ehsan687/Desktop/work/testing-rtree/rltms/leveldb-1.23/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/ehsan687/Desktop/work/testing-rtree/rltms/leveldb-1.23/build/CMakeFiles/CMakeError.log".

**Comment by ChnWuyue** [comment]
hi, How do you solve this issue? I have the same issue. could you give me some advice

**Comment by cmumford** [comment]
Are you getting the submodules?

https://github.com/google/leveldb#getting-the-source

**Comment by ehsandu15** [comment]
> hi, How do you solve this issue? I have the same issue. could you give me some advice
It turned out I didn't download it with all the submodules, you can do that by this command:

> git clone --recurse-submodules https://github.com/google/leveldb.git

**Comment by ehsandu15** [comment]
> > hi, How do you solve this issue? I have the same issue. could you give me some advice
 It turned out I didn't download it with all the submodules, you can do that by this command:

`git clone --recurse-submodules https://github.com/google/leveldb.git`
