### ISSUE TITLE
Can different leveldb share the same Block Cache Object?

### ISSUE THREAD

**Issue by halibobo1205** [google/leveldb#923]
Hi, As the title，Can different leveldb's share the same Block Cache Object? As far as I know, rocksDB can do . 
![image](https://user-images.githubusercontent.com/82020050/127142638-b500d24c-275c-4f87-93f1-db7141384677.png)

**Comment by ghemawat** [comment]
No, different leveldb instances cannot share the same Cache. The keys passed to the caches by different leveldb instances may clash and so a lookup may end up returning a block from a different leveldb instance if you share the cache.
