### ISSUE TITLE
Limiter class bug in env_posix

### ISSUE THREAD

**Issue by kiner-shah** [google/leveldb#946]
https://github.com/google/leveldb/blob/c5d5174a66f02e66d8e30c21ff4761214d8e4d6d/util/env_posix.cc#L96

If `Release` is called multiple times (instead of calling once), the count can increase `max_acquires`. This can later lead to violation of the constraint to limit the resources to `max_acquires`.

Suggested fix:
1. Store `max_acquires` passed in the constructor in a `const` variable, say `resource_limit_`.
2. Check inside `Release()` if `acquires_allowed_` is greater than `resource_limit_`. If yes, ignore adding.

**Comment by duststarr** [comment]
It is only used in the same source file.

**Comment by kiner-shah** [comment]
@duststarr it doesn't matter, it's a bug which needs to be fixed.

**Comment by ghemawat** [comment]
This is not a bug. It is a responsibility of the user of Limiter to match
one Release per Acquire. Allowing redundant releases would be unsafe.

Consider the following sequence of operations:

Thread 1: Acquire
Thread 2: Acquire
Thread 1: Release
Thread 1: Release (redundant)
Thread 2: Release

The redundant release by Thread 1 (if allowed and supported, instead of
being considered a bug) would prematurely cancel Thread 2's Acquire.

**Comment by kiner-shah** [comment]
@ghemawat I think this is a bug due to the design of the Limiter class. The issue is "who owns what" and requirement is to allow only the owners to release the resources only as many times they have acquired. So in your example, if Thread 1 has already released the resource, next time calling Release again should have no effect (somehow mark that Thread 1 has released the resource and check next time if it's already marked, and if yes, ignore the Release).

Regarding your statement of allowing users to ensure they are not calling Release more than once, it should ideally be a two-way responsibility: user should avoid calling Release twice, but by chance (or mistake) if Release is called twice, Limiter should automatically make sure that it doesn't affect the availability of resources.

@duststarr appreciate your efforts for creating a pull request :-) but I think my suggested solution isn't a proper one. It probably will be more complex than I initially thought.

**Comment by duststarr** [comment]
I agree that it's not necessay to make this class too complex.

**Comment by pwnall** [comment]
335876a1335c765f818ae10d9c4d18f563cdfce5 adds some asserts that clarify the responsibilities of the `Limiter` users.
