### ISSUE TITLE
crash when i run a basic demo

### ISSUE THREAD

**Issue by ChunelFeng** [google/leveldb#959]
crash when i try to open a db on my computer (macOS, m1, Monterey)

can u tell me why?

![image](https://user-images.githubusercontent.com/37905059/144706405-35efe6d7-d315-4beb-bfd3-9a39fef01e0a.png)

**Comment by rezamahdi** [comment]
Would you report the commit you used?
this failure may be produced from two places:
 1. the move assignment of class `Status`, that I checked the current commit, it has no issue
 2. Access to `db` object and internal mechanism.
 
by the way, if you used the latest commit, would you please use the 1.23 release and check it works or not?

**Comment by ChunelFeng** [comment]
i install leveldb by brew on my m1 macbook pro, with the command : `brew install leveldb`   

version is 1.23 

![image](https://user-images.githubusercontent.com/37905059/144857236-40354133-b578-4bbe-a905-e7fb1951f622.png)

and it works well on my intel macbook pro by the same way. the version is also 1.23

**Comment by rezamahdi** [comment]
Well, it seems the failure is due to some runtime libraries problems :thinking: .
If you can debug the program, this will be a good issue to fix but I suggest building leveldb by hand and checking it personally.
If custom build worked well (hopefully), the failure is due to the building mechanism of brew, else, this is a bug in leveldb or runtime.

**Comment by ChunelFeng** [comment]
also, python version not work on my m1 macbook pro.
when i try to install it by `pip3 install leveldb` ， it does not worked...

![image](https://user-images.githubusercontent.com/37905059/144867546-026dd3d1-2865-4b84-baa5-425fff7c3297.png)

and still, this command works well on my inter macbook pro.

so, i want to make sure weather this project has been tested on m1 device,
or can it worked well on m1 device?

**Comment by rezamahdi** [comment]
Unfortunately, NO. leveldb uses Github actions to test itself on various hosts and Github actions don't support M1 yet :frowning_face: .
By the way, the python version event doesn't compile. It doesn't mean it doesn't work.  it is a separate issue and I will search for a solution.

If you need such storage for your project I suggest [RocksDB](http://github.com/facebook/rocksdb). It may work and is completely API compatible with LevelDB (just replace `leveldb` namespace with `rocksdb`).

**Comment by ChunelFeng** [comment]
thank you all the same.

i will user this project on my intel macbook pro.

**Comment by pwnall** [comment]
Hey folks! I think that you'll get better answers to basic build / installation / usage questions on StackOverflow.

The issue tracker is for reporting problems in the LevelDB code.
