### ISSUE TITLE
I wish I could kill google staff

### ISSUE THREAD

**Issue by ghost** [google/leveldb#969]
Death to google. Death to the loser bunch of worthless idiots that work for this garbage slave fool company. You are not Engineers, not even close, and will never be. You are cheap slave losers who need to be punished for working for this evil terrorist google. Death to google for promoting the disgusting and stupid so called "health sector". Death to google (and every single trashy app they've worked on or purchased). Death to "universities". 
Death to the stupid so called "health sector". Death to the UK and death to its garbage "national"(death)"service". Death to everyone who supports or works for them. Death to everyone who mentions stupid "titles" with names. Hope you all have a tragic and painful life and death.

**Comment by DanielCorleone2001** [comment]
dude，what‘s happening?
