### ISSUE TITLE
Implementing LevelDB in QT

### ISSUE THREAD

**Issue by Loopite** [google/leveldb#970]
Hello I just compiled the level DB like it was told in the readme.md.
I obtain a dll and I put it into a folder with his includes.

I want integrate this db into a Qt Project so I open a .pro file and I do :

INCLUDEPATH += C:\Users\User\Documents\Project\leveldb
LIBS += -LC:\Users\User\Documents\Project\leveldb\lib -lleveldb

Then, I want test, so I saw the [doc](https://github.com/google/leveldb/blob/master/doc/index.md).

And I put exactly the same thing to test if it works but it isn't.
I can't use the lib I don't know why but I've this error :
error: undefined reference to `leveldb::Options::Options()' In function `qMain(int, char**)': undefined reference to `leveldb::Options::Options()'

error: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'.

But I include files like the doc.

Can you help me to solve this problem.
Cordially, L.

**Comment by pwnall** [comment]
This is better suited for StackOverflow. This forum is for bugs in the LevelDB code.
