### ISSUE TITLE
Compile the library - Error 

### ISSUE THREAD

**Issue by Loopite** [google/leveldb#982]
Hi, I downloaded recently Visual Studio. I followed the [readMe ](https://github.com/google/leveldb#building-for-windows) for windows only. I executed the cmake command, and I obtain this error :
`
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for crc32c_value in crc32c
-- Looking for crc32c_value in crc32c - not found
-- Looking for snappy_compress in snappy
-- Looking for snappy_compress in snappy - not found
-- Looking for malloc in tcmalloc
-- Looking for malloc in tcmalloc - not found
-- Looking for fdatasync
-- Looking for fdatasync - not found
-- Looking for F_FULLFSYNC
-- Looking for F_FULLFSYNC - not found
-- Looking for O_CLOEXEC
-- Looking for O_CLOEXEC - not found
-- Performing Test HAVE_CLANG_THREAD_SAFETY
-- Performing Test HAVE_CLANG_THREAD_SAFETY - Failed
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS - Failed
-- Performing Test HAVE_CXX17_HAS_INCLUDE
-- Performing Test HAVE_CXX17_HAS_INCLUDE - Success
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:299 (add_subdirectory):
  add_subdirectory given source "third_party/googletest" which is not an
  existing directory.

CMake Error at CMakeLists.txt:407 (add_subdirectory):
  add_subdirectory given source "third_party/benchmark" which is not an
  existing directory.

-- Looking for sqlite3_open in sqlite3
-- Looking for sqlite3_open in sqlite3 - not found
-- Performing Test HAVE_KYOTOCABINET
-- Performing Test HAVE_KYOTOCABINET - Failed
-- Configuring incomplete, errors occurred!
See also "C:/Users/Pierre/Desktop/leveldb-main/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Pierre/Desktop/leveldb-main/CMakeFiles/CMakeError.log".
`

**Screen :** 
![image](https://user-images.githubusercontent.com/70860774/151373807-9ab8b6e1-e185-4606-b824-29db5c3d3de5.png)

**Helpful :**
- Cmake version 3.22.1, CMake suite maintained and supported by Kitware (kitware.com/cmake).
- Visual Studio 15 (2017, v15.9)

I let you here to your disposition my CMakeOutput.log/CMakeError.log on **pastbin** for readable reasons.
- https://pastebin.com/3EvTAFc7 (CMakeOutput.log)
- https://pastebin.com/Ys1ma6jd (CMakeError.log)

I hope you'll be able to help me for that.
Cordially.

**Comment by Loopite** [comment]
Hi, issue is closed.
I found the bug.

**Comment by nxtstep** [comment]
@PalinaSh try: 
```
git submodule init
git submodule update
```
